### ISSUE TITLE
Importing old passman passwords from owncloud / manually decrypting passwords

### ISSUE THREAD

**Issue by davidrohr** [nextcloud/passman#11]
The structure of the new app seems to be slightly different than the old having vaults.
It would be good if there would be a dialog to import passwords from the old passman app from owncloud.

In addition, for retrieving passwords in the future, it would be really convenient to have a simple tool that can extract all passwords from the sql database in a standalone way. For instance in case passman becomes incompatible with a future nextcloud version.

As I have been in this situation recently with passman in owncloud, I put together a simple php script (see attachment) that encompasses all the required js code and is able to extract the passwords. I could clean this up a bit and make it use the actual passman js files if you are interested.

[owncloud-pw.zip](https://github.com/nextcloud/passman/files/484408/owncloud-pw.zip)

**Comment by s-brand** [comment]
Hi,
Thanks for the contribution, import / export is in development, you reminded me of it.
Will create separate issue's for the import and export.

**Comment by brantje** [comment]
Please see #12 and #13
