### ISSUE TITLE
Export Credentials

### ISSUE THREAD

**Issue by brantje** [nextcloud/passman#13]
Passman should be able to export passwords / credentials from the current vault

The following formats will be supported

- [x] CSV

If you're missing an export format, please comment =)

**Comment by davidrohr** [comment]
I would suggest that the export should also work in a "standalone" way, without a working nextcloud implementation, but simply with access to the mysql database.

**Comment by animalillo** [comment]
@davidrohr i don't think that export is going to be compatible with a non working nextcloud instance that would require of an special tool to directly access the database and decipher the stored data.

If you ever find yourself in this case scenario, you could simply setup a temporary nexcloud, intall passman on it and import passman tables from the other database, changing the user fields of all the records to your temp instance. Once this is done, you could simply use passman as usual and export the data from the vaults.

**Comment by davidrohr** [comment]
@animalillo Well, I think this can work well with a standalone tool. I have created a simple mockup in php for the old passman for owncloud, which was attached to the original issue #11.

**Comment by brantje** [comment]
Fixed in 5c95911b25017f8bb1f537f1b7e65b8e0aa304f4
