### ISSUE TITLE
Share with link expiration widget difficult to change to sensible time

### ISSUE THREAD

**Issue by thatscoteng** [nextcloud/passman#131]
When selecting share with link, there is a default date set to the year 2999.

Can't see any obvious way to set to a sensible date (such as in 5 days time) without changing the month a silly number of times.

![datewidget](https://cloud.githubusercontent.com/assets/3950932/20175754/46d25458-a73c-11e6-8e9f-f9a992ba5a73.png)

Suggest either a 'set to 24 hours' button or let you type a date in directly.

**Comment by brantje** [comment]
Good point, maybe an idea to share it for 1 month by default?

**Comment by thatscoteng** [comment]
1 month seems fair.

**Comment by brantje** [comment]
Fixed in a14e38c2e0c389c44fb67125b840ee03f1f1a714
