### ISSUE TITLE
Unabled share.

### ISSUE THREAD

**Issue by zhangfisher** [nextcloud/passman#132]
**Unabled share**

**Database:** pgsql
**OwnCloud:** 9.1.2

Exception: {"Exception":"OCP\\AppFramework\\Db\\DoesNotExistException","Message":"Did expect one result but found none when executing: query \"SELECT * FROM `*PREFIX*passman_credentials` WHERE guid = ? and `user_id` = ? \"; parameters Array\n(\n [0] => 16AF79A5-490F-4FE2-87CF-58EC6810FE93\n [1] => admin\n)\n; limit \"\"; offset \"\"","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/public\/AppFramework\/Db\/Mapper.php(372): OCP\\AppFramework\\Db\\Mapper->findOneQuery('SELECT * FROM `...', Array, NULL, NULL)\n#1 \/var\/www\/owncloud\/apps2\/passman\/lib\/Db\/CredentialMapper.php(191): OCP\\AppFramework\\Db\\Mapper->findEntity('SELECT * FROM `...', Array)\n#2 \/var\/www\/owncloud\/apps2\/passman\/lib\/Service\/CredentialService.php(149): OCA\\Passman\\Db\\CredentialMapper->getCredentialByGUID('16AF79A5-490F-4...', 'admin')\n#3 \/var\/www\/owncloud\/apps2\/passman\/controller\/credentialcontroller.php(113): OCA\\Passman\\Service\\CredentialService->getCredentialByGUID('16AF79A5-490F-4...', 'admin')\n#4 [internal function]: OCA\\Passman\\Controller\\CredentialController->updateCredential(1481767530, 1481767502, 4, 'eyJpdiI6ImdaeGl...', 0, '16AF79A5-490F-4...', 'eyJpdiI6IitUYTU...', 'eyJpdiI6ImthNVp...', 0, NULL, 'eyJpdiI6IlpnMlJ...', '16AF79A5-490F-4...', 0, '\\xE7\\xA0\\x94\\xE5\\x8F\\x91\\xE9\\xA1\\xB9\\xE7\\x9B\\xAE\\xE7\\xAE\\xA1...', 'eyJpdiI6Iis5eDh...', 'eyJpdiI6Imd5Y20...', NULL, 'eyJpdiI6ImNPK0J...', 'eyJpdiI6ImRMM0R...', 'eyJpdiI6IlBYU1N...', 2, NULL, NULL, NULL, true, NULL, true)\n#5 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(159): call_user_func_array(Array, Array)\n#6 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Passman\\Controller\\CredentialController), 'updateCredentia...')\n#7 \/var\/www\/owncloud\/lib\/private\/AppFramework\/App.php(99): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Passman\\Controller\\CredentialController), 'updateCredentia...')\n#8 \/var\/www\/owncloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(46): OC\\AppFramework\\App::main('CredentialContr...', 'updateCredentia...', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#9 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#10 \/var\/www\/owncloud\/lib\/private\/Route\/Router.php(280): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#11 \/var\/www\/owncloud\/lib\/base.php(891): OC\\Route\\Router->match('\/apps\/passman\/a...')\n#12 \/var\/www\/owncloud\/index.php(54): OC::handleRequest()\n#13 {main}","File":"\/var\/www\/owncloud\/lib\/public\/AppFramework\/Db\/Mapper.php","Line":288}

**Comment by animalillo** [comment]
We havn't tested it on pgsql. Our fully supported and tested databases are: SQL Lite and MySQL / MariaDB.

I'm currently a bit busy, but i might take a look on this when i have some time.

Also, could you please specify the steps to reproduce?

**Comment by brantje** [comment]
Closing due inactivity, feel free to re-open this issue if you have more info.
