### ISSUE TITLE
Bookmarklet

### ISSUE THREAD

**Issue by brantje** [nextcloud/passman#14]
Passman 1 has a bookmarklet. User drags the bookmarklet to the bookmarks toolbar and can add passwords with a simple click.
Things like label and url are prefilled from the current page.

- [x] Add bookmarklet route
- [x] Create bookmarklet page

**Comment by animalillo** [comment]
I've actually never used this feature

**Comment by brantje** [comment]
Fixed in c907bb540d89547ec29b1b3dc8f4169c4c8cd7c7
