### ISSUE TITLE
Optimize travis test matrix

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/passman#168]
Hi,

I just noticed that you seem to have a rather big test matrix for your CI tests on travis: https://travis-ci.org/nextcloud/passman/builds. Since that blocks CI runs of other projects, it would be great if you could try to optimize the matrix. I'm sure some of the jobs can be combined. Often it's not necessary to test all possible combination.

Here's an example of another Nextcloud app where we cover most setups and still do not have to run as many jobs for every build: https://github.com/nextcloud/mail/blob/master/.travis.yml. Our CI runs take up to 2 minute, where this repo blocks travis for up to 30min per run.

Let me know if I can help optimizing this. Thanks

**Comment by brantje** [comment]
Hi,
Travis is a bit new for me, so yea i'm sure the travis config could be improved.
However i need to be sure that the app runs on NextCloud and ownCloud at the same time.

Maybe merge the phpunit and  codechecks to 1?

**Comment by ChristophWurst** [comment]
> Maybe merge the phpunit and codechecks to 1?

Yes, that makes sense 👍
