### ISSUE TITLE
custom 3rd party appdir not supported

### ISSUE THREAD

**Issue by scheppi2610** [nextcloud/passman#171]
If you set a 3rd party appdir in config/config.php like
'apps_paths' => array ( ....
Passman does not work. The App-Icon is not found, texts are not being filled in and there is no functionality.

My apps_paths variable looked like this one below and passman was copied into '/3rdparty'. Other Apps do work.
```
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/volume1/web/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/volume1/web/owncloud/3rdparty',
      'url' => '/3rdparty',
      'writable' => true,
    ),
  ),
```

**Comment by brantje** [comment]
Thanks for reporting this issue. Anything in the logs what can help/
Because it should work normally, i don't use absolute paths in the app.

**Comment by brantje** [comment]
Investigated this issue, seems to happen also with other apps.
Maybe @BernhardPosselt or @LukasReschke can shine some light on it.


Steps to reproduce: 
- Install in to a random dir (mine was /var/www/temp)
- Add an app path (mine pas /var/www/addons)

Example config:
```
'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/temp/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/addons',
      'url' => '/3rdparty',
      'writable' => true,
    ),
  ),
```
The following things happen:
Passman can't find the files in sub folder `3rdparty`, news app can't be enabled, not sure what the result will be for other apps.

**Comment by BernhardPosselt** [comment]
I don't think that option is supported that well. Think of naive approaches where app developers simply cd up the apps directory and expected the data folder to be present (or other files).

**Comment by brantje** [comment]
Strange because that approach is used in the https://hub.docker.com/r/wonderfall/nextcloud/ docker image.
I use that on my nas, but don't have any problems with passman or news.

**Comment by BernhardPosselt** [comment]
Another thing that comes to my mind: 3rdparty is the directory where PHP libs are stored. You might get conflicts.

**Comment by brantje** [comment]
@scheppi2610 Can you change the folder name to eg `apps2` and try again?

**Comment by brantje** [comment]
Closing due inactivity, @scheppi2610 you're welcome to re-open this issue.
