### ISSUE TITLE
LassPass import broken

### ISSUE THREAD

**Issue by moso** [nextcloud/passman#178]
I'm trying to import my exported LastPass data, however, I'm not able to.

I have installed Passman through my Nextcloud.
Passman version: 2.0.0-RC2.
Nextcloud version: 10.0.2

I've exported my data from LastPass into a nice csv, which is even openable by LibreOffice and everything looks neat and clean. When I go to *Import credentials*, select *LastPass csv* from the dropdown, select my file, and click Import, nothing happens.

In Chrome Dev Tools I get the following error when clicking Import:
```JavaScript
Uncaught TypeError: Cannot read property 'replace' of undefined
    at Object.PassmanImporter.toObject_ (passman.min.js?v=f377f9c…:19)
    at Object.PassmanImporter.readCsv (passman.min.js?v=f377f9c…:19)
    at C_Promise.<anonymous> (passman.min.js?v=f377f9c…:20)
```
When trying the same thing in the demo app, I get the same error, but in `importer-lastpasscsv.js`.

**Comment by brantje** [comment]
Ouch, what lastpass version do you use?

**Comment by moso** [comment]
LastPass is in version 4.
I exported through the website.

**Comment by brantje** [comment]
Quick question, does the export contain data with a comma in it? (except for the separators)
What i'm thinking there is a password or username with a comma in it, that bugs the importer.
If that's the case i can start working on a fix.

**Comment by moso** [comment]
There is data in the `extra` column that contains a comma.
Like "Login for following domains: abc.com, xyz.com" etc.

**Comment by brantje** [comment]
Thanks, with that bit more info i can exactly reproduce the problem.
Thanks for reporting it.

**Comment by brantje** [comment]
@moso Do you use the git version or the one from the appstore?

**Comment by moso** [comment]
The app store version. Nextcloud mentioned the app on their Facebook page, linking to the [apps page](https://apps.nextcloud.com/apps/passman), so I assumed this would be the best way to install.

**Comment by brantje** [comment]
Ok =), i'll provide you with a updated passman.min.js when i'm done.

**Comment by brantje** [comment]
You can try RC3 here: https://releases.passman.cc/passman_2.0.0-RC3.tar.gz

**Comment by brantje** [comment]
Should be fixed in c9f29fdf21f4d9fb8216a0ba1e39c727e1348427 (for git users).
Feel free to open this issue again if the problem persists.

**Comment by moso** [comment]
New error with RC3

```JavaScript
Uncaught ReferenceError: Papa is not defined
    at Object.PassmanImporter.readCsv (passman.min.js?v=552e7c3…:19)
    at C_Promise.<anonymous> (passman.min.js?v=552e7c3…:20)
```
And I get a boatload of `debugger`'s in Chrome Dev Tool, but I guess that's intended :)

**Comment by brantje** [comment]
Weird, the release script didn't pickup

**Comment by brantje** [comment]
Updated version of passman.min.js this one includes the PapaParse lib.
Replace passman.min.js in the js folder.
 [passman.min.js.tar.gz](https://github.com/nextcloud/passman/files/693505/passman.min.js.tar.gz)

**Comment by moso** [comment]
Works perfectly, thanks! :)
