### ISSUE TITLE
Delete vault

### ISSUE THREAD

**Issue by brantje** [nextcloud/passman#185]
Suggested in the [Nextcloud](https://help.nextcloud.com/t/release-passman-rc3/7212/7?u=brantje) forums
To delete a vault
- [ ] User must be signed in to the vault
- [ ] User must type his vault password to confirm
- [ ] Process is NOT reverseable
- [ ] All non-shared credentials get deleted
- [ ] Credentials shared with this vault are unshared
- [ ] Shared items in the vault will disappear

**Comment by brantje** [comment]
Planned for RC4

**Comment by animalillo** [comment]
i would make user reenter the password instead of making him type weird stuff, also it could happen that a troll gets to an unlocked vault somehow and does that, so typing the password is best imho, what do you think?

**Comment by brantje** [comment]
Good, maybe better indeed.

**Comment by brantje** [comment]
Example:
![image](https://cloud.githubusercontent.com/assets/2758767/21869882/f7e9d844-d859-11e6-824f-4c8bddef456d.png)

**Comment by brantje** [comment]
Fixed in 97d0fb2aaee965a1c9e17b889d5eb3ebe2ea7781
