### ISSUE TITLE
iOS App / Safari Plugin

### ISSUE THREAD

**Issue by kenthinson** [nextcloud/passman#186]
Hello. I would love to dump 1Password for this so I can host my own password and not use Dropbox. a iOS and Safari Plugin would be great 👍

**Comment by brantje** [comment]
Thanks, this is related to #138 
Once Passman hits 2.0 stable we start developing extensions for various browsers.

**Comment by maestroi** [comment]
@kenthinson please add any suggestions on [Passman-Chrome](https://github.com/brantje/passman-chrome)

**Comment by brantje** [comment]
Closed in favor of https://github.com/brantje/passman-webextension/issues/1
