### ISSUE TITLE
Feature Request : Ability to manually enter the TOTP values by hand.

### ISSUE THREAD

**Issue by KeithIMyers** [nextcloud/passman#198]
On the Passman TOTP Scree, the only option I see is to upload a QR Code, I would love to see the option to manually enter the token code as a text field

**Comment by maestroi** [comment]
you can add a manual field to a do it for now, but the function is for one time password only so what do you want to store?

**Comment by brantje** [comment]
@KeithIMyers Do you just want to enter the secret or the url?
For example: `	
otpauth://totp/alice@google.com?secret=JBSWY3DPEHPK3PXP`

**Comment by brantje** [comment]
Function is implemented in the `V2.1.0` branch, if you want you can test it.

**Comment by KeithIMyers** [comment]
I just want to say that I have tested this in V2.1.0 and it works perfectly!
