### ISSUE TITLE
Feature Request : Require Password for Exports

### ISSUE THREAD

**Issue by KeithIMyers** [nextcloud/passman#199]
Exporting the unencrypted CSV file from Passman could put the user at risk. As such, a warning should be displayed to the user advising that their passwords will be available in Plain Text. They should be forced to confirm this by entering their password prior to an export.

Last one tonight, I promise

**Comment by maestroi** [comment]
My  suggestion is export a zipfile with a password.
Buy if an attacker already have the rights to export those credentials  you are done anyway, this wil not help security.

Disabling exporting is a way better solution to make it save.

**Comment by brantje** [comment]
Requiring a password before exporting seems a good idea to me.
@maestroi, password protected zip's are as far i know not possible in javascript.
It is however possible to create a normal zip (without password), using (JSZip)[https://stuk.github.io/jszip/]

**Comment by animalillo** [comment]
i have created #203 which might solve the problem of exporting with a password protected zip! (Which happens to be a completely unrelated thing to this issue).

I also agree with requiring to enter vault password before export.

**Comment by brantje** [comment]
Function is implemented in the `V2.1.0` branch, if you want you can test it.

**Comment by brantje** [comment]
Fixed in 2.1
