### ISSUE TITLE
Wrong string interpretation

### ISSUE THREAD

**Issue by XelaNimed** [nextcloud/passman#202]
For more details look on a screenshot:

![nextcloud](https://cloud.githubusercontent.com/assets/685832/21886702/35d5e5fe-d8bd-11e6-9b58-125de130dadd.png)

**Comment by brantje** [comment]
Thanks for reporting this issue. What language did you selected?

**Comment by brantje** [comment]
@XelaNimed Do you remember the language you used?

**Comment by animalillo** [comment]
@XelaNimed also what's the browser and version you are using?

**Comment by brantje** [comment]
Closed due inactivity, feel free to reopen.

**Comment by XelaNimed** [comment]
Google Chrome 56.0.2924.87 (64-bit)

**Comment by animalillo** [comment]
Language? Passman version?
