### ISSUE TITLE
Translation precission

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/passman#206]
Hi,

I's like to translate the two new strings to german.
It is
- controller/translationcontroller.php:192 
- controller/translationcontroller.php:194

But what means precious passwords? It not 100% clear to translate.

**Comment by brantje** [comment]
The 'precious passwords' refers to the passwords in the vault.
Those strings are used here:
![image](https://cloud.githubusercontent.com/assets/2758767/21987293/3c5b8af2-dc03-11e6-8760-9c6471477421.png)
I call them precious, why? Well no reason for that.
In Dutch we'll use the word `kostbaar` for precious.

**Comment by Siggi0904** [comment]
google says:
(of an object, substance, or resource) of great value; not to be wasted or treated carelessly.
"precious works of art"
Synonyme: valuable, costly, expensive, invaluable, priceless, beyond price

then "valuable" is the best one? Thats ok an I can translate it.

You can close this one.

**Comment by brantje** [comment]
Valuable seems like a acronym. You can use valuable indeed.
