### ISSUE TITLE
Antivirus Software reports threat

### ISSUE THREAD

**Issue by zmbcgn** [nextcloud/passman#207]
Hi,

everytime I open Passman within my nextcloud instance, my company installed virus scanner (Symantec) reports that a virus was found (JS.Downloader) and moves the cached file into the quarantine.

here is what the symantec website says:
https://www.symantec.com/security_response/writeup.jsp?docid=2003-102718-1528-99

is that a false positive because of the implementation of passman?

I'm currently using google chrome (Version 55.0.2883.87)

Best regards
zmbcgn

**Comment by animalillo** [comment]
Could we know what is the file that is being detected by your antivirus?
Also, does this also happen if you access passman on https://demo.passman.cc ?

**Comment by brantje** [comment]
There is nothing wrong with Passman, the code is clean and can be viewed by anyone.
Norton might see our implementation for downloading files as a virus.

Also, no means to assault you, but Symantec products are absolute rubbish, they are eating memory / cpu.
If you like i can advise some good anti-virus tools:
- Avast (using this on my game desktop)
- Eset

For Avast, turn off the webshield as that proxy's all web requests to a proxy on local host with a self signed cert. I'm sure Symantec does the same, if you want to keep the software, disable the webscan, it's [rubbish](https://www.symantec.com/connect/forums/do-not-buy-symantec-endpoint-protection)  anyway.

**Comment by maestroi** [comment]
@zmbcgn can you tell me what browser and instance you are running?

**Comment by zmbcgn** [comment]
@animalillo  the filename seem to be random.

f_0024be
f_002878
f_002aab
f_0035dc

no problems on https://demo.passman.cc/. only with my instance.


@brantje  Unfortunately on my company I have neither a choice of which antivirus product I want to use nor how it is configured (in terms of webshield).  After Symantec has quarantined the file successfully I am able to use passman without any problems. And, as long i don't close the browser this alert message doesn't reappear.

screenshot:
https://i.imgsafe.org/e0c153bff4.png

@maestroi  i'm running nextcloud 11.0.1 and passman 2.0.0-RC4

So I consider this as a bug whitin my antivirus software?

**Comment by brantje** [comment]
Oh crap, company AV. Sorry then, didn't read that the first time.

What you could do is reporting the false positive to Symantec: https://submit.symantec.com/false_positive/https://submit.symantec.com/false_positive/

Also, could you upload that file to here, would like to take a look.

**Comment by maestroi** [comment]
@zmbcgn  we scanned the latest release of passman with virus total [https://www.virustotal.com/nl/file/c2fb8817968c64ab8f8663c8ded72432fc25a4d655577ed4d9493ab377f2d3ba/analysis/1484655627/](Virustotal)

**Comment by zmbcgn** [comment]
I noticed that I only have that problem with Chrome 55.0.2883.87, and not with Firefox 50.1.0.

@brantje I'm not able to. Once the file is in the quarantine I'm not able to open it anymore. And before that happens I don't have a chance to intercept it.

@maestroi: Thanks. I also don't think it is an actual virus. On that page it passed the test with Symantec. My version is 12.1.16, maybe they are testing with a newer software then. I get this screen as soon as I click on the "key"-icon and when I have to select my container.

**Comment by animalillo** [comment]
@zmbcgn I don't think this is a problem on passman, maybe is a plugin or some other kind of malicious code targeted towards you or your company

Also, what's the nextcloud instance your passman is hosted on? If it's your company you should tell them and redirect them to this issue.

As far i can tell this options are the most likely issues:
- Your operating system / browser has a virus.
- You are not using HTTP**S** to access passman and a malicious script gets injected on the page by someone external to your control.
- Your nextcloud instance has been compromised and infected, or some malicious app has been installed in your nextcloud instance.

I have tested https://demo.passman.cc with firefox and AVG and it reported no issues. 
Keep in mind than the latest release of passman is: 2.0.0-RC4. You can find your current version under passman settings (once you login into a vault). If you are not running 2.0.0-RC4 upgrade and try again.

**Comment by maestroi** [comment]
@zmbcgn i agree with @animalillo

My suggestion is check the instance its running on.
with something like: http://www.clamav.net/

**Comment by zmbcgn** [comment]
The instance is hosted on my private server. There is ClamAV already running with no infected files found and the site is HTTPS only. 

Installed version of passman is the latest release.

I noticed that I also don't have a problem when I open the vault inside a "incognito" window (hence: all plugins disabled). So I think it is some chrome plugin (Adblock maybe?) which is causing difficulties. Due to policy restrictions I cannot disable the plugins one by one. 

I don't think that anybody else will run into the same problem. Therefor I will close the question and will investigate any further with my company support.

Thanks to all for your quick help and thoughts!  

best regards
zmbcgn

**Comment by maestroi** [comment]
@zmbcgn no problem!!
