### ISSUE TITLE
Add checksums and signatures

### ISSUE THREAD

**Issue by animalillo** [nextcloud/passman#208]
To help with issues like #207 would be neat to have a comment along each release tag with an md5 and an sha sum and also a way to verify the downloaded file is really comming from us with, maybe a pgp signature or something.

 @brantje what do you think?

**Comment by brantje** [comment]
I think you have been sleeping :p releases.passman.cc

**Comment by animalillo** [comment]
i mean, they click the zip download from the git repo and they have no way to check it unless they download from releases.passman.cc

**Comment by animalillo** [comment]
i was thinking in someething like this, kind of
https://github.com/irazasyed/telegram-bot-sdk/releases

**Comment by brantje** [comment]
Good idea, i'll add creating releases to our release script for now it only creates tags

**Comment by brantje** [comment]
Done: https://github.com/nextcloud/passman/releases
