### ISSUE TITLE
Cannot delete vault

### ISSUE THREAD

**Issue by tflidd** [nextcloud/passman#212]
When I first started the app, I tried to create a new vault. First I needed some passwords until I found one which was secure enough. Once I had it, I clicked on created but nothing happened. So I clicked several times on create. Later I found out that I created a ton of different vaults (all with the same name). Unfortunately, you can't delete them directly, you have to access them first, then confirm the deletion with your password.

Now, I tried to delete one, but I got a similar error as this one. So I was not sure if it was deleted, so I took another one, renamed it and deleted it. It shows this error:

{"reqId":"yEdnB0NKvBYKsa2PqlxI","remoteAddr":"ip","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\Db\\\\DoesNotExistException\",\"Message\":\"Did expect one result but found none when executing: query \\\"SELECT * FROM `*PREFIX*passman_vaults` WHERE `guid`= ? and `user_id` = ?\\\"; parameters Array\\n(\\n    [0] => \\n    [1] => user\\n)\\n; limit \\\"\\\"; offset \\\"\\\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php(373): OCP\\\\AppFramework\\\\Db\\\\Mapper->findOneQuery('SELECT * FROM `...', Array, NULL, NULL)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/passman\\\/lib\\\/Db\\\/VaultMapper.php(56): OCP\\\\AppFramework\\\\Db\\\\Mapper->findEntity('SELECT * FROM `...', Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/passman\\\/lib\\\/Service\\\/VaultService.php(68): OCA\\\\Passman\\\\Db\\\\VaultMapper->findByGuid(NULL, 'user')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/passman\\\/lib\\\/Service\\\/VaultService.php(115): OCA\\\\Passman\\\\Service\\\\VaultService->getByGuid(NULL, 'user')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/passman\\\/controller\\\/vaultcontroller.php(162): OCA\\\\Passman\\\\Service\\\\VaultService->deleteVault(NULL, 'user')\\n#5 [internal function]: OCA\\\\Passman\\\\Controller\\\\VaultController->delete(NULL)\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Passman\\\\Controller\\\\VaultController), 'delete')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Passman\\\\Controller\\\\VaultController), 'delete')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('VaultController', 'delete', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/apps\\\/passman\\\/a...')\\n#13 \\\/var\\\/www\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/public\\\/AppFramework\\\/Db\\\/Mapper.php\",\"Line\":289}","level":3,"time":"2017-01-17T19:25:47+00:00","method":"DELETE","url":"\/nextcloud\/index.php\/apps\/passman\/api\/v2\/vaults\/412C6E0F-53C8-4361-8393-FE4AD402A37D","user":"user","version":"11.0.1.2"}

Now it disappeared. Either it was deleted or renamed (there are so many that it is hard to tell. So it could have worked but generated this irritating error.

**Comment by animalillo** [comment]
@tflidd Your issues with this seems to be related with an slow network/server and maybe (we will check this before the final stable release is published) the button of vault creation and vault deletion is not disabled after the first click, allowing you to submit the action several times before the action completes.

If there is some sort of error on the client side, it would appear on the browser developer console (press F12 and switch to the console tab). If you find any errors there, please report them too!

About the password strength required to create a vault, there is a setting on the nextcloud admin menu that lets you set custom minimum strength, if you find the default to be too high, please go to the administrator menu and change it. We have set the default we think the average system administrator would desire for their users password privacy!

It would also help us debugging this issue to know your system setup: 
- Your nextcloud instance version
- Installed Passman version (found in passman settings)
- Where did you download Passman from.
- Your browser and it's version.
- Database type and version.

**Comment by tflidd** [comment]
Sorry, it was in my first posting. NC 11.0.1, Passman 2.0.0-RC4 (downloaded manually from apps.nextcloud.com), FF 50.1.0, maria-db (on debian 8).

I tried to start over again, disabling the passman app, then I deleted all tables with oc_passman_*. If I now open the passman-app I get an error:
![screenshot from 2017-01-17 23-01-21](https://cloud.githubusercontent.com/assets/8111200/22041880/f085b010-dd08-11e6-8788-188092d88d85.png)

(this was chromium 55.0.2883.87, but same error on firefox). Did I forget something to clean out the tables?

**Comment by animalillo** [comment]
The crypto stuff initialized warning is just a debugging line shown on the initialization of the sharing key generators setup, it's not actually an error, just a warning telling you than that engine has been successfully loaded. We must remove it before final stable release.

If you could, please tell us if the same problems described on this issue repeat if you click the button and wait for a bit without clicking any buttons, that would help.

Seems delete vault method has a bug on it, other than that, I have found no issues on [the demo](demo.passman.cc)

**Comment by brantje** [comment]
> 
![image](https://cloud.githubusercontent.com/assets/2758767/22076248/9e773b48-ddaf-11e6-8f5d-cbe46402964f.png)


Thats anti-debug protection, this is only enabled in the app store version.
Will add a setting to disable this.

**Comment by animalillo** [comment]
Altought it's not dissabling console output, so you can get the errors anyway, can't you?
