### ISSUE TITLE
create vault window does not disappear after creating vault

### ISSUE THREAD

**Issue by himbeere** [nextcloud/passman#222]
Hello Devs.

First thanks for that app. I really like it.

Here is my question. Whenever i create a vault the vault creation windows stays. I would expect it to disappear after a successfull vault creation. Is that a known issue?

thanks and cheers

**Comment by brantje** [comment]
Can you provide a bit more info?
What browser are you using? 
Go to here: https://cloud.azirly.nl/settings/admin/additional#passman-settings
And uncheck: Disable context menu and Disable javascript debugger.

Next go back to the passman app, and open up the console, are there any errors?

**Comment by himbeere** [comment]
I'm using Firefox and Chrome. Current versions. What do you mean by "open the console". Do you mean Firebug or something?

Aside from that. This window is supposed to close I understand?

thanks and cheers

**Comment by animalillo** [comment]
@himbeere to open the console press the f12 key on your keyboard
The vault creation window should close upon a successful vault creation.
As far as we tested, it works for us, so we would need a bit of extra info if this problem keeps happening to you.

**Comment by himbeere** [comment]
F12 opens Firebug. Firebug itself is silent. But the error logs from nextcloud have related information. Only as screenshot, sorry.
![bildschirmfoto 2017-02-03 um 16 14 58](https://cloud.githubusercontent.com/assets/631865/22596516/29392ca4-ea2c-11e6-988f-4a64a7e7cfee.png)

Also i get:

Method OC_L10N_String::__toString() must return a string value at /var/www/fluffycloud.de/htdocs/lib/private/L10N/L10N.php#85

and

vsprintf(): Too few arguments at /var/www/fluffycloud.de/htdocs/lib/private/legacy/l10n/string.php#72

Does that help?

**Comment by brantje** [comment]
What version of passman do you have installed? 
Screenshot is very helpful thanks!

**Comment by himbeere** [comment]
RC4.

**Comment by himbeere** [comment]
I just removed the screenshot. I f you like to have it again i can upload it any time.

**Comment by himbeere** [comment]
@brantje Just installed 2.0.0 from 12 hours ago. Problem still there.

thanks and cheers

**Comment by enoch85** [comment]
I can confirm. 

@brantje I think this is what I described to you on IRC.

**Comment by brantje** [comment]
Fixed in 2.0.1

**Comment by enoch85** [comment]
Great! Please ref the commit here. Thanks! :)

**Comment by himbeere** [comment]
Eager to try but i am not able to update:

```
{"reqId":"WJjDCH8AAAEAABKSyioAAAAP","remoteAddr":"xxx.xxx.xxx.xxx","app":"core","message":"App with id passman has invalid signature","level":3,"time":"2017-02-06T18:40:08+00:00","method":"POST","url":"\/index.php\/settings\/ajax\/updateapp.php","user":"user","version":"11.0.1.2"}

**Comment by brantje** [comment]
Strange, i'll force an reupload

**Comment by brantje** [comment]
@himbeere Is that via nextcloud self? If so, i've just upload the newly signed version.

**Comment by himbeere** [comment]
Works now. Bug also gone. Thanks a lot.

cheers
t.
