### ISSUE TITLE
Can not share passwords

### ISSUE THREAD

**Issue by witte1000** [nextcloud/passman#229]
Hello Passman,

Thank you for this lovely app.

But we experience some issue,

I cannot share the passwords, it's saying that it's saved but we don't see anything also not in the logging

![screenshot from 2017-02-07 16-34-47](https://cloud.githubusercontent.com/assets/23100546/22698781/cdda51f8-ed55-11e6-9ab3-e8dac5ccb522.png)

Also if we go to sharing we have following

![screenshot from 2017-02-07 16-35-21](https://cloud.githubusercontent.com/assets/23100546/22698799/dda912a4-ed55-11e6-8c77-a247c9716c6f.png)

And on the admin page we have 

![screenshot from 2017-02-07 16-40-54](https://cloud.githubusercontent.com/assets/23100546/22698810/e9d07766-ed55-11e6-8ff8-a0b0adf24607.png)

Yesterday evening I had installed 2.0.0
But today we upgraded to 2.0.1 but it's still the same

We running omnios 11 version 151020
and NextCloud 11.0.1 (stable)

Any suggestion how to fix this ?

Thank you very much 

Kind Regards,

Dirk

**Comment by jondale** [comment]
When you get the name in the box, don't forget to hit the + button to choose permissions before sharing.

**Comment by brantje** [comment]
In passman settings disable the following:
- Disable context menu
- Disable javascript debugger

After that please to the share page and open up the console (by pressing F12).
Are there any errors visible?

**Comment by witte1000** [comment]
Hello,

Thank you for your quick feedback ;)

When I hit the + button it's still the same

![screenshot from 2017-02-08 14-37-11](https://cloud.githubusercontent.com/assets/23100546/22740456/1ecf62fa-ee10-11e6-9d68-515da6318185.png)



and get following error 
![share](https://cloud.githubusercontent.com/assets/23100546/22740190/087acba8-ee0f-11e6-96a8-e9f5e9356be2.PNG)

on the sharing page I have following error

![sharing](https://cloud.githubusercontent.com/assets/23100546/22740207/1e99c22c-ee0f-11e6-9485-8b88140d2293.PNG)

Thank you very much 

Kind Regards,

Dirk

**Comment by brantje** [comment]
Ok i'll investigate it.
Meanwhile, can you update to V2.0.1 and try again?

**Comment by witte1000** [comment]
Hello brantje,

I'am already running V2.0.1

![screenshot from 2017-02-08 15-22-18](https://cloud.githubusercontent.com/assets/23100546/22741148/7879e45e-ee12-11e6-96a3-3adc4caa691c.png)

Thanks,

KR,

Dirk

**Comment by brantje** [comment]
@witte1000 You're welcome to join [here](https://mattermost.passman.cc/signup_user_complete/?id=549o395qr7rxzk8pwje8e81cty) to investigate your issue.

**Comment by brantje** [comment]
@witte1000 I think the issue is solved, we solved it via chat. What do you think?

**Comment by witte1000** [comment]
@brantje Yes indeed I close this case

Thanks a lot !!!
