### ISSUE TITLE
Change vault password

### ISSUE THREAD

**Issue by brantje** [nextcloud/passman#23]
Users should have the ability to change the vault password.
However all files, custom fields and credentials need to be re-encrypeted.
Not sure what the impacts is of this on sharing, therefore a cc for @animalillo

**Comment by animalillo** [comment]
lots of impact, we will know when we finish sharing xD

**Comment by brantje** [comment]
Fixed in ca590057b5125d4810d17f85020a29a6457aa4a0 @animalillo will make it more informative (progress per credential)

**Comment by brantje** [comment]
Fixed
