### ISSUE TITLE
decryption error after share and delete the share of a password

### ISSUE THREAD

**Issue by jones4410** [nextcloud/passman#232]
When I share a Passwort by link and then delete the share, there is a decryption error and passman can't decrypt anything anymore:
![grafik](https://cloud.githubusercontent.com/assets/22591354/22784594/edc5bc56-eed0-11e6-9e55-3b6a35421324.png)
I hope this helps finding the issue... If I can help you with more details - ask me...

**Comment by brantje** [comment]
I've just had the same. Will be fixed in next release

**Comment by jones4410** [comment]
ok, perfect!
I'm interestedly watching this project growing...

**Comment by budachst** [comment]
Also, when deleting such a modifed password, passman will not remove that from the database and still count it as if it was avaiable. E.g. deleting such a password, which was the only password in a vault will cause passman to show "1 of 1 passwords shown" until the faulty password is removed from the database manually.

**Comment by gpkvt** [comment]
@brantje We just experienced this issue with Passman 2.1.2 on Nextcloud 12.0.0, using a group shared password.
