### ISSUE TITLE
hex2bin(): Input string must be hexadecimal string

### ISSUE THREAD

**Issue by raptwa** [nextcloud/passman#234]
After upgrade from 2.0.0-RC3 to 2.0.1, it is not possible to access any existing vaults.

Error message:
hex2bin(): Input string must be hexadecimal string at /var/www/nextcloud/apps/passman/lib/Service/EncryptService.php#146

It wouldn't be a problem to export and import all vaults, but the exporter omits url's and custom_fields. So this is no option for me at least.

Thanks in advance!

**Comment by brantje** [comment]
Hmm seems that nextcloud failed the part of executing our upgrade hooks.
In RC4 we've introduced server side encryption. 
Nextcloud have ran the following migration script: https://github.com/nextcloud/passman/blob/master/migration/serversideencryption.php

Are you on the git version or the app store version?

**Comment by raptwa** [comment]
app store version. So should I try to run the serversideencryption.php manually  while upgrading?

**Comment by brantje** [comment]
I have another idea, if you have some time to chat (goes a lot faster then GH).
Then you can go to here: 
https://mattermost.passman.cc/signup_user_complete/?id=549o395qr7rxzk8pwje8e81cty
Click on 'Gitlab Single-Sign-on'   
You get redirected to our gitlab, at the bottom choose github login.
If you don't want to use your github login, then you're also free to create a account.
