### ISSUE TITLE
Version check fails if proxy used

### ISSUE THREAD

**Issue by manfred-mp** [nextcloud/passman#237]
Cannot check version info against github if behind proxy.

**Comment by brantje** [comment]
Anything in the error log?

**Comment by manfred-mp** [comment]
Error  PHP  Undefined variable: githubVersion at /usr/pbi/owncloud-amd64/www/owncloud/apps/passman/templates/part.admin.php#39  2017-02-10T12:19:08+00:00

BTW. This is great app for owncloud, thx!

**Comment by brantje** [comment]
@manfred-mp Can you provide the config you use? Censor out all sensitive info

**Comment by manfred-mp** [comment]
Fork attached. After googling a bit it is clear that DOMdocument->load is not the best option with proxies and many suggested using curl. Anyway this approach is using OC's internal HTTPclient and works great.


[part.admin.php.txt](https://github.com/nextcloud/passman/files/776311/part.admin.php.txt)

**Comment by manfred-mp** [comment]
Error PHP Undefined variable: githubVersion at /usr/pbi/owncloud-amd64/www/owncloud/apps/passman/templates/part.admin.php#39 is caused by missing check for $checkVersion boolean where compare is done (or define it in code or change code order)

**Comment by brantje** [comment]
Thanks, will implement it in the `part.admin`.

**Comment by manfred-mp** [comment]
I think you got this $checkVersion fix wrong from my bad explanation, sry. $githubVersion is never defined if version check is not enabled and later on it is used in compare here: `<?php
		if (version_compare($githubVersion, $localVersion) === 1) {
			p($l->t('A newer version of passman is available'));
		}
		?>`

It should be something like this: `<?php
		if ($checkVersion && version_compare($githubVersion, $localVersion) === 1) {
			p($l->t('A newer version of passman is available'));
		}
		?>`

**Comment by manfred-mp** [comment]
FYI: isset($checkVersion) still in code in two places

**Comment by brantje** [comment]
ATM busy with the android app, if you want you can make a PR to the V2.1.0 branch.

**Comment by manfred-mp** [comment]
But you added those in this fix. Just leave those as they were in original code.

**Comment by brantje** [comment]
Fixed in 2.1
