### ISSUE TITLE
Translation missing/error log lines after passman enabled

### ISSUE THREAD

**Issue by manfred-mp** [nextcloud/passman#238]
Error  PHP  Method OC_L10N_String::__toString() must return a string value at /usr/pbi/owncloud-amd64/www/owncloud/lib/private/L10N/L10N.php#84  2017-02-10T11:46:57+00:00  
Error  PHP  vsprintf(): Too few arguments at /usr/pbi/owncloud-amd64/www/owncloud/lib/private/legacy/l10n/string.php#71  2017-02-10T11:46:57+00:00

**Comment by brantje** [comment]
See #209

**Comment by manfred-mp** [comment]
Hmm... don't get any of these log lines from other apps. If really being a core problem assuming all apps had this same issue?

**Comment by brantje** [comment]
You've got a stack trace?

**Comment by manfred-mp** [comment]
Have to study how to get it

**Comment by brantje** [comment]
Related:
https://help.nextcloud.com/t/php-errors-and-ramdisk/8028
https://github.com/nextcloud/server/issues/3309

**Comment by brantje** [comment]
@icewind1991 do you know what might cause this?

**Comment by mind22** [comment]
@brantje  i get the same error and i think its due to the language strings. For example iam using german language and i get the error log when iam opening the passman app. On this first page, the "Create a new vault" didnt get translated at all, but the rest on this page is correctly translated.

**Comment by simmarn** [comment]
Seen in 12.0.2 when activating the Mail app. If I activate the Mail app when language is set to "Swedish" I get this error. If language is set to "English (US)" there is no error. Same with Passman.

**Comment by brantje** [comment]
We're following the [docs](https://docs.nextcloud.com/server/12/developer_manual/app/l10n.html?highlight=translations#php), if it causes errors then Nextcloud should update their docs.
@BernhardPosselt do you know why this is happening?

**Comment by BernhardPosselt** [comment]
No idea

**Comment by brantje** [comment]
Found it:
![image](https://user-images.githubusercontent.com/2758767/29512873-d51894aa-8663-11e7-87c0-7b7cbed401eb.png)

**Comment by OS3DrNick** [comment]
As brantje commented, 

Change line 44 on 'controller/translationcontroller.php' to:
`'generating.sharing.keys' =>  $this->trans->t('Generating sharing keys ( %s / 2)','%step'),`
