### ISSUE TITLE
Emergency sharing

### ISSUE THREAD

**Issue by brantje** [nextcloud/passman#24]
Idea copied from windows only pw manager :x: 

Designate access to all or selected passwords in the event of an emergency.
Access is only granted following a pre-selected period of time.

Enlight this @animalillo

**Comment by brantje** [comment]
Not sure what we gonna do with this...

**Comment by maestroi** [comment]
how do you determine if it is a emergency

**Comment by animalillo** [comment]
By setting a time of inactivity after which a password will be accessible by the end target user, but i'm not so sure about this feature

**Comment by maestroi** [comment]
@animalillo i think it is a bad idea to make this feature

**Comment by brantje** [comment]
Closing. We have link sharing, good enough imo.
