### ISSUE TITLE
Cannot Delete Vault

### ISSUE THREAD

**Issue by hooray4me** [nextcloud/passman#240]
I forgot the password I used to create a vault. I want to delete it and start over, but I can't seem to find a way to do that. How can I accomplish this?
![image](https://cloud.githubusercontent.com/assets/12399138/22840381/efc04d6a-ef92-11e6-9591-ff4330fce063.png)

**Comment by brantje** [comment]
You need to be logged into a vault to delete it.
If you don't have access to the vault, you can delete them from the table `oc_passman_vaults`.
Also, delete the credentials with the matching vault_id from `oc_passman_credentials`

**Comment by animalillo** [comment]
Due to the security implications of deleting a vault without knowing the password, we have not implemented that option, the only option is to manually do that on the database.

**Comment by hooray4me** [comment]
@brantje much appreciated... Sidenote, the vault I _was_ using will not accept my credentials after updating to 2.0.1

**Comment by brantje** [comment]
From what version are you coming?

**Comment by hooray4me** [comment]
I _think_ it was the previous available release... I was on NC10 with passman installed and working. I upgraded to NC11 and it was still working. Then I upgraded the app to 2.0.1... and cannot log it in... Its not too big of an issue as I have still have an offline copy of passwords.

**Comment by brantje** [comment]
We had RC1, RC2, RC3, RC4(Introduced server side encryption) and then 2.0.0

**Comment by brantje** [comment]
@hooray4me Is the issue solved now you know how to delete your vaults?

**Comment by hooray4me** [comment]
yes thanks
