### ISSUE TITLE
Mobile App

### ISSUE THREAD

**Issue by Happyfeet01** [nextcloud/passman#241]
Hello, i switched from @fcturner Passwords plugin to this, works the same App with this password Plugin? https://play.google.com/apps/testing/com.intirix.cloudpasswordmanager

if not, is it possible to create one?

**Comment by brantje** [comment]
Hi, 
That app is not compatible with passman. 
Seems that there is not really client side encryption, since i see my passwords in plaintext :/ (network inspector.

A mobile app for passman is in the works, we can't give an ETA yet we just started an we're only 2 devs.

**Comment by Happyfeet01** [comment]
thanks for the answer
