### ISSUE TITLE
share dialog doesn't autocomplete local users or groups

### ISSUE THREAD

**Issue by budachst** [nextcloud/passman#242]
When trying to share a password, while entering a user or group that exists on the nextcloud instance, there is no hint of that reflected in the dialog. Usually, any sharing dialog will provide a pop-up some sort of suggestion for auto-completion.

**Comment by animalillo** [comment]
Did that user already create a vault on passman?

**Comment by budachst** [comment]
Well… no. I didn't thought about that. However, one seems to be so used to the client popluating the sharing dialog. Maybe a brief comment that no other password vault could be detected would be helpful.

**Comment by animalillo** [comment]
We will think on this for a later release, thanks for the idea!

**Comment by brantje** [comment]
Fixed in 2.1
