### ISSUE TITLE
Add import functionality for Teampass

### ISSUE THREAD

**Issue by rudolfpietersma** [nextcloud/passman#244]
## Feature request

**User type**: Logged-in or public user

**User level**: Beginners, intermediate or advanced

### Benefit / value
Importing from Teampass allows users to switch from teampass to passman

### Risk / caveats
Please create the ability to import Teampass data via CSV

### Sponsorship

 
**Are you a developer willing to implement this feature?**: yes/no

**Can you sponsor the development of this feature or do you know someone who can?**: yes/no

**Comment by rudolfpietersma** [comment]
[simonecsvteampass.zip](https://github.com/nextcloud/passman/files/773661/simonecsvteampass.zip)

**Comment by brantje** [comment]
Thanks, i'll take a look!

**Comment by rudolfpietersma** [comment]
Great, tnx! (dank je :-))

**Comment by brantje** [comment]
@rudolfpietersma I can't seem to open this in gedit. Getting the error that the file contains invalid UTF8 chars.The CSV export must be unencrypted, plaintext utf8.
I think the problem lies in the password field, see below screenshot.
![image](https://cloud.githubusercontent.com/assets/2758767/22923580/5cf7917e-f2a2-11e6-8a34-8b1f413b2935.png)

**Comment by brantje** [comment]
Example for teampass

[teampass-example.csv.zip](https://github.com/nextcloud/passman/files/773676/teampass-example.csv.zip)

**Comment by rudolfpietersma** [comment]
Donwloaded it as this from Teampass.

**Comment by rudolfpietersma** [comment]
Should I still do anything or do you have enough information?

**Comment by brantje** [comment]
I think teampass exports the passwords encrypted, does it has an option to export them in plaintext?

**Comment by rudolfpietersma** [comment]
I downloaded a new file and it's uncrypted. Don't know why the first time it added these "strange" looking passwords :-)
You need the file?

**Comment by brantje** [comment]
Yes please. But replace the passwords with some random strings.
Or random [generated passwords](https://www.random.org/passwords/?num=5&len=15&format=html&rnd=new)

**Comment by rudolfpietersma** [comment]
Here you go
[rudolfnewcsv.zip](https://github.com/nextcloud/passman/files/773819/rudolfnewcsv.zip)

**Comment by brantje** [comment]
@rudolfpietersma Can you describe the steps you made to create the export?

**Comment by rudolfpietersma** [comment]
Enabled "Export to PDF or CSV enabled" (https://github.com/nilsteampassnet/TeamPass/issues/731)
Exported the selected folder to CSV and added the file to a zip because GitHub doesn't allow the upload of CSV files.

**Comment by brantje** [comment]
Ok, thanks. If you want you can checkout the `v2.1.0` branch and test the importer.

**Comment by rudolfpietersma** [comment]
Tnx, will try it right away

**Comment by rudolfpietersma** [comment]
Yes! It's working, tnx!

**Comment by brantje** [comment]
Np, enjoy!

**Comment by rudolfpietersma** [comment]
One additional question. Will the Nextcloud iPhone app be able to open the Passman app items? Or will there be an addional app available?

**Comment by brantje** [comment]
Nextcloud app will not be able to open passman, as fair i know, that is only for files.

We don't have any iOS devices to program / test on, we might setup a kickstarter for that if there is enough interest in an OSX / iOS app.

**Comment by rudolfpietersma** [comment]
Would love the ability to use the Passman on my phone :-) 
Tnx anyway, bedankt!

**Comment by animalillo** [comment]
An android app it's on its way

**Comment by brantje** [comment]
Fixed in 2.1
