### ISSUE TITLE
Deleting a vault doesn't remove tags

### ISSUE THREAD

**Issue by oparoz** [nextcloud/passman#245]
##Issue

### Steps to reproduce
1. Create a vault
2. Add passwords + tags
3. Delete vault
1. Create the same vault again (same name)
1. Open vault

### Expected behaviour

The vault should be completely empty

### Actual behaviour

I see all the tags of the old vault.
It's unsettling and makes the user wonder what else hasn't been removed.

**Comment by brantje** [comment]
Fixed in 2.1
