### ISSUE TITLE
activity feed shows now entry of passman althoug there is the option to filter for it and it shows all the other entrys

### ISSUE THREAD

**Issue by jones4410** [nextcloud/passman#246]
##Issue

### Expected behaviour
The filter for passman in nextcloud activity-stream either shouldn't exist or it should show entries of passman. 
### Actual behaviour
The filter for passman in nextcloud activity-stream shows all other activities and nothing from passman

### Configuration
**Passman version**:    2.0.2
**cloud server:** Nextcloud
**cloud version:** 11

**Comment by brantje** [comment]
I have an option to filter on Passwords:
![image](https://cloud.githubusercontent.com/assets/2758767/22950602/7923451e-f306-11e6-8065-8b80cfdf50bc.png)
And it's working
