### ISSUE TITLE
When a user forgets their vault password

### ISSUE THREAD

**Issue by Luticus** [nextcloud/passman#247]
What a user forgets their vault password, how can that vault be removed?  Can an admin remove it? 

Thanks.

**Comment by brantje** [comment]
Hi, see #240

**Comment by Luticus** [comment]
Oh, that's unfortunate.  Normal admins aren't always great with sql.  Luckily I can do it just fine, bit of a pain though.  Especially once that database gets complex.  I understand the security implications but people forget their passwords all the time.  Perhaps a system where a user makes a request to remove a vault and an admin confirms before it actually gets deleted?  If not that then maybe print a uniqe id for the vault on the vault label somewhere so users can say "remove this vault id" and I can use a script to purge it? 

Thanks for the reply.

**Comment by brantje** [comment]
@animalillo 2nd time in a short period. Maybe add a section to the admin page to delete vaults from a user? What do you think?

**Comment by brantje** [comment]
Closing, we will add some kind of request system to delete vaults.
