### ISSUE TITLE
Importer support for "Passwords" app for OwnCloud/NextCloud

### ISSUE THREAD

**Issue by r3pek** [nextcloud/passman#248]
##Issue

### Steps to reproduce
1. Try to import an export from the "Passwords" app for ownCloud/NextCloud

### Expected behaviour
Should import the passwords on the csv.

### Actual behaviour
No compatible imported available

### Configuration
**Operating system**:   Arch Linux

**Browser**:      Chrome

**Extensions that might cause interference**:   

**Passman version**:    2.0.2

**Operating system**: Arch Linux

**Web server:** Apache

**Database:** MariaDB

**PHP version:**
      
**cloud server:** Nextcloud or ownCloud

**cloud version:** 7.1.1

## Feature request

**User type**: Logged in

**User level**: Beginners

### Description

There should be a module to import from this App, since there could be users migrating to Passman

### Benefit / value

Same as above

### Risk / caveats

None that I know

### Sponsorship
 

**Are you a developer willing to implement this feature?**: no

**Can you sponsor the development of this feature or do you know someone who can?**: no

I can read javascript, but not knowing the API makes it more time consuming for me than any dev that already knows how this works :)
The format of the export is like follows:
"Website","Username","Password","FullAddress","Notes"
"Site.com", "r3pek", "$ub3rdup3r*p@ssw0rd", "https://www.site.com", "Very powerfull password!"
(...)

**Comment by brantje** [comment]
@r3pek Can you describe the steps you need to take to create an export?

**Comment by r3pek** [comment]
- Backups for the Passwords app need to be enabled on the Admin panel (they are disabled by default).
- On the Passwords App, in the bottom left corner, press Settings
- Press "Download Backup"
- Confirm the export and save the file
