### ISSUE TITLE
Sharing with users and groups doesn't work

### ISSUE THREAD

**Issue by MMoudry3** [nextcloud/passman#249]
##Issue
Sharing with users or groups doesnt work under latest Chrome.

### Steps to reproduce
1. Create a credential using Chrome web browser
2. Attempt to share it with a group or a user - not using link

### Expected behaviour
When trying to share with other users and groups, the textbox 'Search users and groups' works like elsewhere in nextCloud.

### Actual behaviour
There are no selections proposed, writing full name or username and clicking on plus just makes the textbox red.

### Configuration
**Operating system**:   Client WIndows 10, server ubuntu 16.04

**Browser**: Chrome 56.0.2924.87 (64-bit), Firefox 

**Extensions that might cause interference**:   None

**Passman version**:    2.0.2

**Operating system**: Windows 10

**Web server:**
Apache2

**Database:**
Mysql

**PHP version:**
7.0
      
**cloud server:** Nextcloud

**cloud version:** (see admin page or version.php)
11.01
  
   
          
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>   

#### Cloud log

<details>
<summary>Cloud log</summary>

```
Insert your cloud log here
```
</details>

## Feature request

**User type**: Logged-in or public user

**User level**: Beginners, intermediate or advanced

### Sponsorship

 
**Are you a developer willing to implement this feature?**: yes/no

**Can you sponsor the development of this feature or do you know someone who can?**: yes/no

**Comment by brantje** [comment]
I think #242 is related

**Comment by animalillo** [comment]
Do the target user have created any vaults?
We have added a warning message on passman v2.1 which will be the next release

**Comment by MMoudry3** [comment]
Nope I don't think so, lemme try that

**Comment by MMoudry3** [comment]
yes, that fixed it however now the share button stays greyed...

**Comment by MMoudry3** [comment]
For me, I am admin the button ungreys itself, for other users it stays greyed
