### ISSUE TITLE
Can't delete passwords within vault

### ISSUE THREAD

**Issue by jonsparks** [nextcloud/passman#252]
## Bug report
I'm unable to delete individual passwords within my vaults.

### Steps to reproduce
1. Open vault
2. Click password to open right sidebar
3. Click 'Delete', password disappears but shows back up on refresh/reopening vault.

### Expected behaviour
The delete button should do as it says and delete passwords. I get that there's a 'Deleted Passwords' section, but once a password is deleted it should not show up in the main list.

### Actual behaviour
Password goes away only to come back after reloading the page/vault.

### Configuration
**Operating system**:   
Desktop: Ubuntu 16.10
Server: Ubuntu Server 16.04

**Browser**:      
Chrome, latest

**Extensions that might cause interference**:   
Using Passman Chrome extension, but the problem occurs when it is disabled, and in Firefox.

**Passman version**:    
2.1.0

**Web server:**
Apache2

**Database:**
MySQL

**PHP version:**
7
      
**cloud server:** Nextcloud or ownCloud
Nextcloud

**cloud version:**
  11.0.1

**Comment by brantje** [comment]
Did you wait until the notification disappears?

**Comment by brantje** [comment]
Can you disable the following under Admin -> Additional settings -> Passman Settings:
![image](https://cloud.githubusercontent.com/assets/2758767/23083387/ab5e5bdc-f55d-11e6-87e2-a434b74a065e.png)

Do you get any error in the javascript console?

**Comment by jonsparks** [comment]
Just some content security policy errors with a couple fonts I have in a custom theme, but aside from that everything looks fine. I am getting a 500 error when I try to destroy passwords from the 'Deleted Credentials' page, though-

```
DELETE https://cloud.{mydomain}.net/apps/passman/api/v2/credentials/36B98609-CFE3-47A8-8738-10641C335EB4 500 (Internal Server Error)
(anonymous) @ passman.min.js?v=0c08f80…:4
n @ passman.min.js?v=0c08f80…:4
(anonymous) @ passman.min.js?v=0c08f80…:4
(anonymous) @ passman.min.js?v=0c08f80…:4
$eval @ passman.min.js?v=0c08f80…:5
$digest @ passman.min.js?v=0c08f80…:5
$apply @ passman.min.js?v=0c08f80…:5
(anonymous) @ passman.min.js?v=0c08f80…:7
dispatch @ jquery.min.js?v=0c08f80…:3
r.handle @ jquery.min.js?v=0c08f80…:3
```

**Comment by brantje** [comment]
Can you post the nextcloud.log?

**Comment by jonsparks** [comment]
```
{"reqId":"tcIHZrPe\/qcC3Yq2pABR","remoteAddr":"{IPAddr}","app":"PHP","message":"vsprintf(): Too few arguments at \/cloud\/owncloud\/lib\/private\/legacy\/l10n\/string.php#72","level":3,"time":"2017-02-17T21:17:51+00:00","method":"GET","url":"\/apps\/passman\/api\/v2\/language?lang=en","user":"admin","version":"11.0.1.2"}

{"reqId":"tcIHZrPe\/qcC3Yq2pABR","remoteAddr":"{IPAddr}","app":"PHP","message":"Method OC_L10N_String::__toString() must return a string value at \/cloud\/owncloud\/lib\/private\/L10N\/L10N.php#85","level":3,"time":"2017-02-17T21:17:51+00:00","method":"GET","url":"\/apps\/passman\/api\/v2\/language?lang=en","user":"admin","version":"11.0.1.2"}

{"reqId":"IeKkn4tTfstxyPhf5l2h","remoteAddr":"{IPAddr}","app":"index","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to a member function getId() on array\",\"Code\":0,\"Trace\":\"#0 \\\/cloud\\\/owncloud\\\/apps\\\/passman\\\/controller\\\/credentialcontroller.php(277): OCA\\\\Passman\\\\Controller\\\\CredentialController->deleteCredentialParts(Object(OCA\\\\Passman\\\\Db\\\\Credential))\\n#1 [internal function]: OCA\\\\Passman\\\\Controller\\\\CredentialController->deleteCredential('C0D799A4-FFE6-4...')\\n#2 \\\/cloud\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#3 \\\/cloud\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Passman\\\\Controller\\\\CredentialController), 'deleteCredentia...')\\n#4 \\\/cloud\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Passman\\\\Controller\\\\CredentialController), 'deleteCredentia...')\\n#5 \\\/cloud\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('CredentialContr...', 'deleteCredentia...', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#6 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#7 \\\/cloud\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#8 \\\/cloud\\\/owncloud\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/apps\\\/passman\\\/a...')\\n#9 \\\/cloud\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/cloud\\\/owncloud\\\/apps\\\/passman\\\/controller\\\/credentialcontroller.php\",\"Line\":295}","level":3,"time":"2017-02-17T21:18:16+00:00","method":"DELETE","url":"\/apps\/passman\/api\/v2\/credentials\/C0D799A4-FFE6-4F40-B8AC-71C3E1BD0D63","user":"admin","version":"11.0.1.2"}
```

**Comment by brantje** [comment]
So when you mean delete credential you actually meant destroy?

**Comment by jonsparks** [comment]
Both, I think. After I hit the Delete button, the credential does appear in the deleted list, but after I reopen the vault, it's in both the main list and the deleted credentials list. If I've already deleted a credential, I can hit the Delete button and it goes away again, but still temporarily. The Destroy button is the only thing that actually seems to throw an error, though.

**Comment by brantje** [comment]
Are you using the git version or app store?

**Comment by jonsparks** [comment]
I'm using the app store version- it was doing the same thing for me with version 2.0.2 so I updated it in hopes that the bug was fixed already, but it's doing the same thing.

**Comment by brantje** [comment]
I think i have a fix ready, if you can switch to git you can test it out.

**Comment by jonsparks** [comment]
Sure, I can switch over. It may be later this evening/sometime tomorrow before I get a chance, but I'll test it out and let you know if it works.

**Comment by brantje** [comment]
Thanks you can checkout the `v2.1.1` branch.

**Comment by jonsparks** [comment]
Great, looks like it's working now- deleting a password from the main list lowers the total number of credentials, and they don't show back up after reloading the page. 

The 500 error on the Deleted Credentials page is gone, but a JS error is popping up now (although it doesn't seem to impact functionality in any way)-
```
TypeError: Cannot read property 'credentials' of undefined
    at countCredentials (credentialcounter.js?v=0c08f80…:48)
    at credentialcounter.js?v=0c08f80…:66
    at m.$digest (angular.min.js?v=0c08f80…:143)
    at m.$apply (angular.min.js?v=0c08f80…:146)
    at angular.min.js?v=0c08f80…:20
    at Object.invoke (angular.min.js?v=0c08f80…:41)
    at c (angular.min.js?v=0c08f80…:20)
    at Bc (angular.min.js?v=0c08f80…:21)
    at fe (angular.min.js?v=0c08f80…:20)
    at HTMLDocument.<anonymous> (angular.min.js?v=0c08f80…:317)
```

**Comment by brantje** [comment]
Thanks, i already fixed that one local =)

**Comment by ScreamingDev** [comment]
This seems again to be an issue and relate to #454, #264 and other. There is an "undefined" in Firefox and Chrome @brantje .
Got 2.1.4 here.
