### ISSUE TITLE
deleted passwords are taken into account for showing total in header

### ISSUE THREAD

**Issue by andristeiner** [nextcloud/passman#253]
### Steps to reproduce
1. Delete random password

### Expected behaviour

In "Showing X of Y credentials" in title, Y shoud decrease by one and not count the deleted password anymore.

### Actual behaviour

Deleted passwords are still taken into account for showing total.

### Configuration

**Passman version**:    2.1.0

**cloud server:** Nextcloud

**cloud version:** 11.0.1

**Comment by brantje** [comment]
The credentials are counted in `js/app/directives/credentialcounter.js`.
Wanna give it a try @andristeiner ?

**Comment by andristeiner** [comment]
Yeah sure. I'm still struggling a bit with debugging this javscript stuff but i hope i'll figure it out soon :smile:

**Comment by brantje** [comment]
Don't know if you have telegram, otherwise you're welcome to join the channel is you need help =)

**Comment by andristeiner** [comment]
In `js/app/directives/credentialcounter.js`, countedCredentials gets raised if the following is true:

`credential.delete_time >= scope.deleteTime && credential.hidden === 0`

I don't exaclty understand the idea behind `scope.deleteTime` (it is 0), and if we should change `scope.deleteTime` from `=` to something else, or just adapt the if condition to something like:

`credential.delete_time != scope.deleteTime && credential.hidden === 0`

Im happy to join mattermost or telegram but was not figure out the appropriate locations :blush:

**Comment by brantje** [comment]
Telegram @passman_dev
