### ISSUE TITLE
Selected tag in vault-view doesn't stick after returning from sharing or editing

### ISSUE THREAD

**Issue by budachst** [nextcloud/passman#255]
##Issue
Selected tag in vault-view doesn't stick after returning from sharing or editing

### Steps to reproduce
1. open vault
2. select a tag from the left hand pane
3. click on a credential to edit or share
4. return to vault

### Expected behaviour
The credentials displayed should still be filtered according to the tag, which is still displayed as selected.

### Actual behaviour
All credentials are loaded again and no tag filtering is applied

### Configuration
**Operating system**:  Raspian Jessie 

**Browser**: Firefox

**Extensions that might cause interference**:   

**Passman version**:    2.1.0

**Operating system**: macOS 10.12.2

**Web server:** Apache 2

**Database:** MariaDB

**PHP version:** PHP 5.6.27-0+deb8u1 (cli) (built: Oct 24 2016 18:22:27)
      
**cloud server:** Nextcloud 

**cloud version:** 11.0.1 (production)

**Comment by brantje** [comment]
Thanks for reporting, i've fixed the issue in the `v2.1.1` branch
