### ISSUE TITLE
Can't delete empty vaults

### ISSUE THREAD

**Issue by polkillas** [nextcloud/passman#257]
## Feature request - Deleting vaults

**User type**: Logged-in user

**User level**: Beginners

### Description
I tried this app a month ago and seemed promising but not mature enough. As I've seen there is now a Firefox/Chrome extension, I'm trying it again. Looks great! However, I've seen a lot of empty vaults which where created in a matter of seconds (32 vaults, from 07-01-2017 @ 10:55:55 to  07-01-2017 @ 10:57:09). I don't know the password of these vaults, and wanted to delete them. How can I do it? Do I have to do it in the database?

### Benefit / value
Old vaults with lost passwords will clutter the GUI.

### Risk / caveats
Deleting a non-empty vault is dangerous.
 
**Are you a developer willing to implement this feature?**: no

**Comment by brantje** [comment]
I'm actually implementing a system that allows users to request vault removal if they forgot the password.
Think will be ready for a 2.1.1 release =)

**Comment by polkillas** [comment]
Very good news indeed!

**Comment by brantje** [comment]
![image](https://cloud.githubusercontent.com/assets/2758767/23133143/629a89ae-f790-11e6-8685-8ee189a40c14.png)

**Comment by brantje** [comment]
Closing. V2.1.1 is released.
