### ISSUE TITLE
Cant retrieve files on passman

### ISSUE THREAD

**Issue by luisbrandao** [nextcloud/passman#259]
Hello, 

I was testing passman, and tried to store an ssh key. I created 2 new fields, one for the public part and one for the private part. After the save, it seems that i cant retrieve the files, clicking then dont do anything. 

This is a bug or i am doing something wrong?

**Operating system**:   
Server: fedora 25

**Browser**:      
chrome and firefox

**Passman version**:    
2.1.0

**Web server:**
centos 7 - apache 2.4.6-45

**Database:**
mariaDB

**PHP version:**
PHP 5.6.30

**Comment by brantje** [comment]
I've pushed a fix to the `v2.1.1` branch, can you test it?

**Comment by luisbrandao** [comment]
It is downloading now, but sometimes the ouput is invalid. a .pub file turn out as:

data:application/vnd.ms-publisher;base64,c3NoLXJzYSBBQ(...)
