### ISSUE TITLE
Question: can I share password with a group?

### ISSUE THREAD

**Issue by mkola-greenliff** [nextcloud/passman#262]
Hi,

Is it possible to share password with a group of people? I see this option below, but it does not work for me (group "users" exists, but I cannot use it for sharing):
![1](https://cloud.githubusercontent.com/assets/20461234/23205033/c5cf68ba-f8e8-11e6-9556-b70b562330f6.jpg)

Am I missing something?
Thanks,
Matthias

**Comment by witte1000** [comment]
Hello Matthias,

No I don't think you miss something.
Under your dropbox it says "Only users that have vaults are shown" 
For the moment it's only possible for users witch have created a vault, but I'm sure Brantje and co will come with a solution for it ;)

Kr,

**Comment by kolorafa** [comment]
So it's a broken feature or in planning?
As it's a deal breaking.

**Comment by brantje** [comment]
If it's deal breaking then you're welcome to implement it.
At the moment Passman doesn't has such feature because the complexity it brings.
