### ISSUE TITLE
Sharing with other users seems broken

### ISSUE THREAD

**Issue by Luticus** [nextcloud/passman#265]
### Steps to reproduce
1.open users 1's vault, create credential
2.Share credential with user 2
3.open user 2's vault, accept notification
4.observe that user 2 cannot see password/credential, even if user 2 logs out and then back in.
5. user 1's password share page will be in an odd state that when you try to navigate away it says that you will corrupt the credential if you do.  There is no way to navigate away without accepting that popup.  Credential doesn't appear corrupt afterward though.
6. even though user 1's vault shows the key as shared and lists user 2 as being shared with, user 2's vault still does not show the shared credential.

In my case both users have only 1 vault.

### Expected behaviour
user 1 shares credential. user 2 accepts credential, user 2 sees credential.  (preferably without refreshing or logging out of the vault and logging back in.)

Also the share notification should probably be shown without the user having to log out and then back into the vault.

### Actual behaviour
Tell us what happens instead
user 1 shares credential. user 2 accepts credential, user 2 does not see credential.

Share notification is only shown once user logs out and then back into their vault.

### Configuration
**Operating system**:   
debian 8

**Browser**:      
vivaldi/chrome/firefox

**Extensions that might cause interference**:   
none

**Passman version**:    
2.1.1

**Web server:**
apache

**Database:**
mysql

**PHP version:**
5.6.30+dfsg-0+deb8u1
      
**cloud server:** Nextcloud or ownCloud
Nextcloud

**cloud version:** (see admin page or version.php)
  11.0.2

**Comment by Luticus** [comment]
Seems it may have been fixed by regenerating the share keys (vault for user 2 was fresh).  Although the share acceptance process is a little jarring as the notification doesn't popup in the vault right away.  It does pop up in the notification center and can work if the notification is clicked.  Not sure it's intuitive enough for novice users but it does seem to work.

**Comment by animalillo** [comment]
The notification does pop-up on vault login, as nextcloud does not provide a method to provide real time updates, we would have to ping the server continuously to mimic a real time notification.

Glad to see you found the way to make it work, in older passman versions the was an issue with sharing key generation, maybe that was your problem.

**Comment by Luticus** [comment]
Yea I've been testing passman with my environment for a while now so it is possible that an old issue bled through.  I'm going to keep testing it with other users so if it persists or if I get more info on it I will certainly let you guys know.

Its a shame nextcloud had no real-time update mechanism, I'm sure constant pinging might have performance considerations.  Wonder if there is a way to just add the accept button to the notification in the notification center as that does seem appear in real time?

Anyhow, I appreciate the response and all.  The app as a whole is fantastic and I look forward to seeing how it evolves.


Thanks,

Joe McEntire
getjoe@live.com
On Feb 28, 2017, at 3:43 AM, Marcos <notifications@github.com<mailto:notifications@github.com>> wrote:

The notification does pop-up on vault login, as nextcloud does not provide a method to provide real time updates, we would have to ping the server continuously to mimic a real time notification.

Glad to see you found the way to make it work, in older passman versions the was an issue with sharing key generation, maybe that was your problem.

**Comment by brantje** [comment]
@Luticus Is this still an issue? We also have #288 or #285

**Comment by Luticus** [comment]
I'm thinking this one can probably safely be closed now.  At any rate if there is an issue here a fix to #288 would probably resolve it.
