### ISSUE TITLE
I want to help to craft good design for passman app

### ISSUE THREAD

**Issue by milapbhojak** [nextcloud/passman#266]
Dear community,

Milap here from India, I am Product Designer at Finomena. Previously i was at Shadowfax #1 product designer and UX designer at Koru technologies. Also worked with Y combinator start ups as a design consultant. In my free time i contribute as a designer to airbnb's open source project called Superset.

I could see you guys are looking for designer[1] I would like to work on this project. Let me know how to get started. 

Looking forward to hear back from you :)

thanks,
milap

[1] http://opensourcedesign.net/jobs/jobs/2017-02-22-android-passman-app-design

**Comment by elioqoshi** [comment]
Hey @milapbhojak 

Great to have your interest here! I recently joined the Passman team as I saw the same announcement which you saw. However, every helping hand is appreciated, so I'd be happy to work with you on UX if you like to.

You also seem to have great experience in what you do! A few things about me: https://elioqoshi.me/speaking/

Let me know if you would like to help and we can chat!

**Comment by elioqoshi** [comment]
@milapbhojak Hey mate. Are you still interested to help? Let us know :)

**Comment by brantje** [comment]
@milapbhojak If you're still up for helping us, feel free to reopen it.

**Comment by milapbhojak** [comment]
@elioqoshi Hey, Yeah. I am interested in helping. Let's take it forward. :)

**Comment by elioqoshi** [comment]
@milapbhojak do you have Telegram? Let's chat there

**Comment by milapbhojak** [comment]
@elioqoshi Yes, I do have Telegram. Tell me how to contact you there?

**Comment by elioqoshi** [comment]
ping me @elioqoshi :)
