### ISSUE TITLE
Import from csv contain 35 fake password

### ISSUE THREAD

**Issue by Mte90** [nextcloud/passman#267]
### Steps to reproduce
1.Taken a csv exported from keepassx and use the generic importer
2.Import
3.Go to my folder and find 165 password but the csv contain 113

### Expected behaviour
Only the 113

### Actual behaviour
all that password like for weber.biz with domain http://api.namefake.com/en.., doyle.com to the same doman etc.
I have to remove them manually (there is not multiple selection)

### Configuration
**Passman version**:    2.1.1
      
**cloud server:** Nextcloud

**Comment by brantje** [comment]
Are you sure you didn't import random data?

**Comment by Mte90** [comment]
Nope the csv contain my stuff the importaer says that imported 113 password but became 165, maybe they are demo data for developers?

**Comment by brantje** [comment]
Namefake is the service passman uses for generation of test credentials. This way passman can easily be tested in demo instanced.

**Comment by Mte90** [comment]
Ok but i got that in my installation (from the store of the app) in nextcloud 11 and i am using in a stable way (third part service)

**Comment by brantje** [comment]
What importer did you use? We have a keepass importer, but that one doesn't work for keepassx

**Comment by Mte90** [comment]
I don't find also a way to remove the labels/tags created (but I think that is another issue) they are empyt but are showed on the left sidebar, now i removed all that password manually.

**Comment by Mte90** [comment]
I used the generic csv importer that imported everything without issue

**Comment by brantje** [comment]
What browser did you use?

**Comment by Mte90** [comment]
Firefox nightly

**Comment by brantje** [comment]
I think i've found the culprit, pushed a tiny fix to `v2.1.2` branch, mind to give it a try?

**Comment by Mte90** [comment]
I cannot do it, my installation is not mine is on a third part service.
the only issue now is how to remove the tags :-/

**Comment by brantje** [comment]
@Mte90 I close this one, your tag issue will be solved with #270, i tend to implement it this weekend.

**Comment by Mte90** [comment]
thank you!
