### ISSUE TITLE
Change Individual Tag Names All At Once

### ISSUE THREAD

**Issue by cwmke** [nextcloud/passman#269]
## Feature request

**User type**: Logged-in

**User level**: Beginners

### Description
I would like to be able to change individual tag names all at once. Currently I need to open each individual password entry and manually change the tag associated with each. It would be much quicker and less painful to be able to simply change the tag name for all entries at once.

### Benefit / value
Although it's not a very high priority issue, it allows users to update, correct or change undesirable tags much faster than with the current implementation.

### Risk / caveats
None that I can think of.

### Sponsorship
Not sure what this is but I donated 10 minutes ago if that's what is meant?
 
**Are you a developer willing to implement this feature?**: no

**Can you sponsor the development of this feature or do you know someone who can?**: no

**Comment by brantje** [comment]
Hi,
At the moment this is not yet possible.
However, for a newer version of passman we will a new tag system that will allow the user to change the tags.
I will close this and make a feature request.
Thanks for using Passman =)
