### ISSUE TITLE
Imported password (with EnPass) are sometimes saved as password AND as additional field

### ISSUE THREAD

**Issue by ajira86** [nextcloud/passman#271]
### Steps to reproduce

1. Import passwords from EnPass (didn't try from another)
2. Select an imported line and look the right panel for informations
3. Sometimes password as text, sometimes as password field
4. Enter in credentials data: password is automatically filled but not the good one
5. In additional field you will find "Mot de passe" in french for me

### Expected behaviour

The password should imported as password field

### Actual behaviour

The password is imported as text field but not all the time.

### Configuration

**Browser**: Google. Chrome

**Extensions that might cause interference**:   

**Passman version**: 2.1.1

**Operating system**: Debian Jessie

**Web server:** 

**Database:** MySQL

**PHP version:**
      
**cloud server:** Nextcloud 

**cloud version:** 11.02

**Comment by brantje** [comment]
So the password field is in French? If so, passman can't detect the field and adds it as a custom field.

**Comment by ajira86** [comment]
I take a look on EnPass text file and figure out that some fields are translated and some other are not. Perhaps because I have multiple working EnPass software installed on different languages. This issue have to be reported to EnPass. Sorry for this report and thank your for your great software ;)
