### ISSUE TITLE
Feature Request: Share by Tag

### ISSUE THREAD

**Issue by benyanke** [nextcloud/passman#272]
Lastpass, which I'm looking to use this to replace, automatically provides sharing for any password tagged with a given tag. Is this on the roadmap for this as well? For example, you could have a tag for individual departments within a business, and then simply by adding tags to a cred set, it could be shared to everyone in that given department.

**Comment by brantje** [comment]
Please use the feature template.

**Comment by benyanke** [comment]
Excuse my cluelessness, but where do I find that?

**Comment by brantje** [comment]
No problems
When you create a new issue you see text in the textarea.
Scroll a bit down there you will see: `## Feature request`, remove the rest above it.
Thanks for trying Passman

**Comment by benyanke** [comment]
Sounds good, will do.

I've become increasingly unsettled by the direction of Lastpass, so if I can use this as a replacement, I'd be thrilled.
