### ISSUE TITLE
Repeat password

### ISSUE THREAD

**Issue by ddanielww** [nextcloud/passman#273]
If i enter a custom password not a generated one , it does not force me to repeat the password , intact i can type something completely different in and it still saves ? Should it not check these two match ?

**Comment by brantje** [comment]
Correct, in fact there is already a @todo in the code :P
![afbeelding](https://cloud.githubusercontent.com/assets/2758767/23612809/24c26942-027d-11e7-932c-8450763f8129.png)

**Comment by ddanielww** [comment]
I dont understand, is there a way to change this so it forces you to repeat the password ?

**Comment by maestroi** [comment]
@ddanielww for now there is no way it needs to be implemented

**Comment by ddanielww** [comment]
So what is the repeat password box used for as I see no use for it ?

**Comment by brantje** [comment]
`I dont understand, is there a way to change this so it forces you to repeat the password ?`
Yes, make a PR containing the check, or else wait for the fix.

**Comment by ddanielww** [comment]
How would I go about making a PR so it does the check , has this already been logged as a issue and when will it be fixed ?

**Comment by brantje** [comment]
You have to edit [this](https://github.com/nextcloud/passman/blob/master/js/app/controllers/edit_credential.js#L295) file. You should compare `storedCredential.password` and `storedCredential.password_repeat` for equality.

**Comment by ddanielww** [comment]
Is this a bug within the app or a feature ? Is this planned to be fixed ?

**Comment by brantje** [comment]
It's a bug, it will be fixed, when i don't know, we are doing this in our free time.

**Comment by ddanielww** [comment]
Do we have a reference of this defect ? As I can not see it logged as an issue

**Comment by animalillo** [comment]
Uhm... Did you notice th thread is called an issue, has an issue number and has been tagged as bug?
