### ISSUE TITLE
Web Crypto API

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman#276]
## Feature request

**User type**: Logged-in

**User level**: Does not matter

### Description
Switch to Web Crypto API.

### Benefit / value
Recent browser support it, potentially hardware support (-> certainly faster), maybe better algorithms

### Risk / caveats
needs backward-compatibility to read old vaults

### Sponsorship
 
**Are you a developer willing to implement this feature?**: no

**Can you sponsor the development of this feature or do you know someone who can?**: no

**Comment by brantje** [comment]
Thanks for filling the template.
At the moment we use SJCL as encryption lib, meaning that lib takes care of encryption / decryption.
If webcrypto is supported, then *i think* sjcl uses that.

**Comment by animalillo** [comment]
we also use Forge which i believe uses cryptoapi when available and works around when not

**Comment by animalillo** [comment]
but you are welcome to point any weakness into our code or the libraries we use, we will do our best to fix them!

Might I ask if you checked our code and found any special case that needs attention?

**Comment by rugk** [comment]
No, I just read "uses SCJL", so I thought it does not use Web Crypto.

**Comment by rugk** [comment]
@animalillo Anyway, I need to report something (potentially) security-critical. How should I do that?

**Comment by brantje** [comment]
you can mail that you brantje at-sign passmann [dot] cc

**Comment by animalillo** [comment]
or use github, depends how critical it is

**Comment by rugk** [comment]
The original issue was about Web Crypto… So why do you close it?

**Comment by brantje** [comment]
Because the libs we use make use of the web crypto api as @animalillo said.

**Comment by rugk** [comment]
Okay, however I am not sure whether they will do so… During last year [they declined adding WebCrypto support](https://github.com/bitwiseshiftleft/sjcl/issues/317)? I've asked in the thread there if they want to do it, but I am not sure they'll do.

**Comment by Nilos** [comment]
Hey, sjcl Maintainer here. sjcl does not support web crypto and there are no plans to support it due to large API changes required to do so.

**Comment by rugk** [comment]
So, @brantje, reopen?

Also do you know any wrapper lib for this?

**Comment by brantje** [comment]
I don't know any wrapper for this.
Also, i won't implement this by myself, we rather use an audited lib than implementing it wrong ;).
So of you know a nice lib, implement it, make a PR then we'll review it.
If we consider it's safe and it's not destroying any functionality then we might merge it.

**Comment by rugk** [comment]
In this case you could reopen this issue and mark it with "help wanted".

**Comment by rugk** [comment]
and it is still closed...
