### ISSUE TITLE
{{ 'http.warning' | 'translate' }}

### ISSUE THREAD

**Issue by himbeere** [nextcloud/passman#282]
Hi Devs.

From time to time i get the message {{ 'http.warning' | 'translate' }} while accessing passman. Usually the message disappears seconds after showing. See attached screenshot. 

![screenshot_20170319_140025](https://cloud.githubusercontent.com/assets/631865/24081927/6b5ab036-0cbd-11e7-88a1-45ddfa7b504f.png)

My system:

Nextcloud 11.0.2
Apache 2.4.25
PHP 7.1.3

Any hints how to solve this?

thanks and cheers

**Comment by himbeere** [comment]
Oh, maybe this log entry is helpfull?

```
{"reqId":"WJM1Bn8AAAEAAAW8-h8AAAAV","remoteAddr":"10.10.10.10.10","app":"PHP","message":"vsprintf(): Too few arguments at \/var\/www\\/htdocs\/lib\/private\/legacy\/l10n\/string.php#72","level":3,"time":"2017-02-02T13:32:54+00:00","method":"GET","url":"\/apps\/passman\/api\/v2\/language?lang=en","user":"himbeere","version":"11.0.1.2"}
```

**Comment by brantje** [comment]
I have seen this happing too. I think nextcloud is screwing the js, since after a refresh its gone.

**Comment by brantje** [comment]
Can you report this issue to the server repo?
Seems to be a core issue:
![image](https://cloud.githubusercontent.com/assets/2758767/25449238/76e19a16-2abb-11e7-98b6-d551409b62ea.png)
