### ISSUE TITLE
l10n: Two message parts are combined in app. Not manageable for translators

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/passman#287]
For my issue the template is not suitable. Please do not close and read on.

I am a translator at transifex and take care about issues opened their.

File:
passman/controller/translationcontroller.php

Lines 337 and 338:
'sharereq.line1' => $this->trans->t('If you want to put the credential in a other vault,'),
'sharereq.line2' => $this->trans->t('logout of this vault and login to the vault you want the shared credential in.'),

At transifex there are no comments and people do not know that both strings are related.
Is it possible to have this two messages in one message to get one full sentence?

**Are you a developer willing to implement this feature?**: yes/no
no

**Can you sponsor the development of this feature or do you know someone who can?**: yes/no
no

**Comment by brantje** [comment]
Yes, this is possible. However i'm very short on time at the moment. Will try to edit the strings this weekend,
