### ISSUE TITLE
Always Many Session

### ISSUE THREAD

**Issue by emresaracoglu** [nextcloud/passman#290]
Hi,

Passman have many session, its a normal status?
 
![sureklitalep fw](https://cloud.githubusercontent.com/assets/297968/25105796/dbf48fc4-23ce-11e7-9165-07823928a6d9.png)

**Comment by brantje** [comment]
How are you so sure that this is because of passman? Passman uses the nextcloud API, if it's causing many sessions then that's an issue in nextcloud not passman.

**Comment by emresaracoglu** [comment]
I am absolutely sure of that but I upgrade to 11.0.3 RC2 (beta) and now I can't see
