### ISSUE TITLE
Need to cancel Mozilla default password-remember screen

### ISSUE THREAD

**Issue by emresaracoglu** [nextcloud/passman#292]
Is it possible for Mozilla to replace the default password screen? 
I mean, do not need the default remember-password section of the mozilla when using Passman

![2015-06-02-16-51-47-8fe4c1](https://cloud.githubusercontent.com/assets/297968/25166759/8cd43404-24e5-11e7-951e-78bfc20210ea.png)

_### Do not consider the red circle._

**Comment by brantje** [comment]
We have an webextension for passman that does exactly that ;).
Link: https://github.com/nextcloud/passman-webextension

**Comment by emresaracoglu** [comment]
Wow. The shutdown speed was awesome. 
I already use it, Is there a way to turn off Mozilla's own feature?

**Comment by brantje** [comment]
Can you make an issue at the webextension repo?
Yea we have an github bot in our dev channel :P

**Comment by emresaracoglu** [comment]
Okey @brantje
