### ISSUE TITLE
removing shared passwords

### ISSUE THREAD

**Issue by jknockaert** [nextcloud/passman#295]
First share a password by user A to user B.
When removing the user A account in Nextcloud, the shared passwords are not removed from the vault of user B. And through the user interface it is not possible for user B to remove these shared passwords.

**Comment by brantje** [comment]
What you want? Deleting passwords when a user is deleted? I would be very careful with such feature.

**Comment by brantje** [comment]
Another option is to delete the ACL row which gives user B access, this will make sure user B can't see the password anymore, but user A doesn't lose it when the account is deleted and re-created.

**Comment by jknockaert** [comment]
Well, when a user is deleted all data owned by that user is removed from nextcloud, so that would be the expected default behaviour.
If there is an exception to be made for password vaults, then it creates a situation where passwords/vaults are orphaned: nobody owns them, so they can no longer be edited or deleted.
But even if we do so, I would provide an option for users to remove received shares (user B in my description) from their vault.

**Comment by jknockaert** [comment]
@brantje Do I understand correctly that when an account is re-created (whatever that may mean) the passwords are accessible again? Isn't that a security issue? Imagine a large scale nextcloud where a user account is deleted. Then someone else impersonates that user and recreates the account (perhaps through an automated interface). Then that someone else has access to the passwords?

**Comment by animalillo** [comment]
User b should be able to delete the references to the item at least, if that does not work there is something going wrong, please fill in the issue template so we can track down the issue

**Comment by brantje** [comment]
Closing, implementation of #296 will solve this.
