### ISSUE TITLE
Exports CSV doesn't export urls

### ISSUE THREAD

**Issue by welbert** [nextcloud/passman#297]
## Feature request
Add url to csv export

### Steps to reproduce
1. Click to export passwords
2. Check .csv file

### Expected behaviour
Export all important data "label","username","password","email","description","tags",**"url"**

### Actual behaviour
Url is missing on .csv file

### Configuration
**Operating system**:  

**Browser**:  Lastest Chrome

**Extensions that might cause interference**:   

**Passman version**:    2.1.1

**Operating system**: Raspbian

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.0
      
**cloud server:** Nextcloud

**cloud version:** 11.0.2 (stable)

**Comment by brantje** [comment]
Actually this is a feature request, not a bug ;)

**Comment by brantje** [comment]
Fixed
