### ISSUE TITLE
Shared items stuffs

### ISSUE THREAD

**Issue by animalillo** [nextcloud/passman#30]
# Stuff needed for sharing
- [x] Distinguish shared credentials from standard ones
- [x] Distinguish between owned shared credentials and foreign ones
- [x] Convert standard credential to shared credential
- [x] Load pending share requests
- [x] Ask users to import shared credentials on the vault
- [x] Let users know that there are shared credentials waiting for them once they open passman so they go to the vault they prefer them to be
- [x] Use shared credential unique shared key to decypher shared credentials
- [x] Get shared credential shared key
- [x] Store shared credential shared key
- [x] Revisions sstuff
- [x] Files
- [x] API to update shared credentials
- [x] Don't forget to check for edit permission server side.
- [x] Set a way to change users permissions without restarting the whole sharing process
- [x] Set a way to add users without regenerating sharing keys and bugging all users with a new share request
- [x] Convert shared credential to standard credential
- [x] Add activity's (@brantje)

**Comment by brantje** [comment]
1 -> Solved in 2e6de5c
2 -> The api already gives an `user_id` property

**Comment by animalillo** [comment]
Sharing working on sharing_no_groups branch since commit 762b5e6af22564882c35694615003f1f7b1d41c4

**Comment by brantje** [comment]
Sharing has been merged into master since: c52984f779d575888d66dc05d5f924467d14fd01
