### ISSUE TITLE
Packaging "broken"

### ISSUE THREAD

**Issue by jurgenhaas** [nextcloud/passman#301]
Inside the archive all apps have a subdirectory with the name of the app. With version 2.1.2 PassMan introduced a change to that by naming the high level directory passman-2.1.2, i.e. that name includes the version number as well.

This is (1) not necessary and (2) breaks automatic deployments processes that where extracting the archive into the apps directory and were just done.

Is there a way to get back to the previous structure and to what all other apps are doing as well?

**Comment by brantje** [comment]
Did you download it from github or the release site?

**Comment by animalillo** [comment]
We will check it out

**Comment by animalillo** [comment]
Thanks for reporting!

**Comment by jurgenhaas** [comment]
@brantje I downloaded from GitHub

**Comment by brantje** [comment]
Github messes up the releases. Please download it from releases.passman.cc or the Nextcloud appstore.
Meanwhile, i look how i can change the github behaviour.
