### ISSUE TITLE
Export the valut without the password

### ISSUE THREAD

**Issue by Mte90** [nextcloud/passman#307]
## Bug report
I am in the uncomfrotable situation where I have only a browser that has the vault already opened (remember it) and I cannot export from him because I don't remember the password.
There is a way to export or change the vault password without know it? actually is like impossible :-/

**Comment by brantje** [comment]
Nope, without vault key there is no decryption possible.

**Comment by Mte90** [comment]
So the only option that I have is to copy manually all the password and create a new vault?

**Comment by brantje** [comment]
Edit: https://github.com/nextcloud/passman/blob/master/js/app/controllers/export.js#L62
Remove the if statement

**Comment by animalillo** [comment]
It is a security feature so only the vault owner can export or change vault password

**Comment by Mte90** [comment]
I don't have the access to the owncube installation (third part service) so I am trying if maybe with the inspector on the browser I can get the vault key

**Comment by Mte90** [comment]
I recovered the password with:
```
angular.element('[ng-controller=MenuCtrl]').scope().active_vault.vaultKey
```
