### ISSUE TITLE
Bad UX in setup process

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman#310]
It's hard to say whether this is a bug or rather a suggestion, so I'll mix this template here.

### Configuration
**Operating system**: Linux

**Browser**:  Firefox 53.0.3

**Passman version**: 1.0.3 

**Operating system**: Linux

**cloud server:** Nextcloud

**cloud version:** 12
  
## Feature request

**User type**: Logged-in

**User level**: N/A

### Description

The first setup process happens in a pane. This is very ugly, as one might have to copy passwords from another (previously-used) password manager into this new fields.
Also when using 2FA in NextCloud, one has to copy the device password from the web UI.
Also, for convenience, one might want to copy the NextCloud URL.

So in the worst case you need to copy three things:
* NextCloud URL
* user password/device password
* vault password

Now there are some problems:
1. One cannot right-click in these fields. Ctrl+V can be used, but some users may rather prefer to right-click.
2. When one clicks on anything else (other window, website/tab) the pane disappears and one can do all the setup process again from the beginning.

### Benefit / value

Changing this would allow to copy some things in there without inadvertently cancelling the setup process again and again.

### Risk / caveats

none

### Sponsorship

 
**Are you a developer willing to implement this feature?**: no

**Can you sponsor the development of this feature or do you know someone who can?**: no

**Comment by brantje** [comment]
You sure this belongs here? I have the feeling it belongs to passman-webextension.

**Comment by rugk** [comment]
Yes, I'm moving it.

**Comment by rugk** [comment]
Done: https://github.com/nextcloud/passman-webextension/issues/79
