### ISSUE TITLE
1024 bit keys for sharing?

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman#311]
### Steps to reproduce
1. Create a vault.

### Expected behaviour

It somehow states in the small text at the bottom that my "share key" is 1024bit strong.

### Actual behaviour

This is completely confusing and probably also wrong. First, if this would be symmetrical encryption it would be quite insane given that AES **256 bit** is considered very secure, so two (mathematically said) second powers "lower" that what you use there.
However, if it would be asymmetrical encryption, this would be insecure as at least 2048bit is suggested for this as [1024bit is insecure for RSA/DH/…](https://freedom-to-tinker.com/2015/10/14/how-is-nsa-breaking-so-much-crypto/).

Anyway, what is this information supposed to mean anyway? Should I shout: "Ohh, how strong?" or what?
I assume you don't want such (wrong?) marketing claims in your app anyway.

So either change the wording to make it clear or just leave this information away…

**Comment by rugk** [comment]
When looking in the settings later, it gets even stranger. First, it is an RSA key, so 1024bit are insecure and can be cracked by nation-state attackers. So better remove this option at all and do not let users use it. (Security by default.)

However, actually a 2048bit key was used by default (which is fine) – contrary to what was stated in the vault generation text.

**Comment by animalillo** [comment]
The key you are talking about it's the RSA sharing key, it's 1024 bits by default altought you can generate a new one at any time.

This is a default value considered safe for most use cases and that generates in an acceptable time on all tested devices, going to longer keys make vault creation way slower than an average user that does not care about encryption that much expect.

If i'm not wrong there is a setting for the nextcloud admin to set the default sharing key length.

1024 bit long keys are not considered unsafe, just discouraged.
As of now, we are leaving this default, if you feel uncomfortable with the key length, feel free to generate a new one!

In the future, when faster mobile devices are more common we will think on increasing this default.

**Comment by rugk** [comment]
> make vault creation way slower than an average user that does not care about encryption that much expect.

So it only affects the vault generation? In this case, that's an one-time cost and IMHO not that important if one needs to wait some seconds longer…

> In the future, when faster mobile devices are more common 

Maybe suggest to create the vault on your desktop device… :wink: 

> 1024 bit long keys are not considered unsafe, just discouraged.

It is insecure. See https://freedom-to-tinker.com/2015/10/14/how-is-nsa-breaking-so-much-crypto/, read about [logjam](https://weakdh.org/):
> We further estimate that an academic team can break a 768-bit prime and that a nation-state can break a 1024-bit prime.

(stand: 2015; DH and RSA key lengths are similar)

In the [full paper](https://weakdh.org/imperfect-forward-secrecy-ccs15.pdf) (starting at p. 8) they also estimate the time:
> Thus we estimate that a 1024-bit descent would take about 30 core-days, once again easily parallelizable.
> […] Although 45M core-years is a huge computational effort, it is not necessarily out of reach for a
nation state.
> […] Our calculations suggest that it is plausibly within NSA’s resources to have performed number field sieve precomputations for at least a small number of 1024-bit Diffie-Hellman groups
> […] Our analysis suggests that 1024-bit discrete log may be within reach for state-level actors. As such, 1024-bit DHE (and 1024-bit RSA) must be phased out in the near term.

Still note this has been written in 2015.
