### ISSUE TITLE
Vault password generation only possible in settings

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman#313]
## Feature request

**User type**: ??

**User level**: Any
### Description
Currently one can generate/copy/… the vault password when changing it in the settings. However, this is not possible for the first-time the vault password is entered when creating the vault.

### Benefit / value

So either add a button there too or remove it from the change password settings. Maybe the first one would be better… Just allow users to do this.

### Risk / caveats

none

### Sponsorship

 
**Are you a developer willing to implement this feature?**: no

**Can you sponsor the development of this feature or do you know someone who can?**: no

**Comment by animalillo** [comment]
The vault password should be one you remember, so you better type it than have a random one that you are highly probably forgetting IMHO

**Comment by rugk** [comment]
But then why is there an option to generate it when changing the vault password? There, you don't have to remember it??

BTW: In any case you have to type/copy it in a second input field to confirm it.

**Comment by brantje** [comment]
Fixed
