### ISSUE TITLE
Import button missing…

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman#315]
### Steps to reproduce
Trying to follow https://github.com/nextcloud/passman-webextension/issues/82#issuecomment-307346714 I am using the general CSV importer, but an important button is missing.

### Expected behaviour
I can click on an import button.

### Actual behaviour
![grafik](https://user-images.githubusercontent.com/11966684/26989928-39fc19ca-4d55-11e7-8607-3891d9d434c9.png)

There is no button and the import does not not seem to be triggered automatically…
(Note: other import functions have that button, which is missing here)

### Configuration
**Operating system**: Linux

**Browser**: Firefox 53.0.3

**Passman version**: 2.1.2

**Database:** MySQL

**PHP version:** 7
      
**cloud server:** Nextcloud 12

**Comment by brantje** [comment]
![image](https://user-images.githubusercontent.com/2758767/26990110-d6a981c2-4d55-11e7-9524-8e0f72738feb.png)
Should look something like this.
Any errors in the javascript console?

**Comment by brantje** [comment]
Can you try to import with chrome / chromium?

**Comment by rugk** [comment]
Ahh, there does not even appear this table… I'll try.

**Comment by rugk** [comment]
Same behaviour in Chrome/ium. I actually found an error message in the console, however:
``` 
OTS parsing error: invalid version tag
```

BTW: In any case this erro should be shown to the user in the UI, not hidden in the console and cause such an unexpected behaviour as I see it.

Also, it was difficult to access the console. In Chrome/ium the debugger got mad always halting (and showing the exact same code (not only while doing this, however), in Firefox the whole browser got laggy. When closing the console the issues disappeared.
See:
![chromedebugger](https://user-images.githubusercontent.com/11966684/26992427-f312176c-4d5e-11e7-9478-80ece3b761e1.png)

I even removed the comment line (`#`) which was there at the beginning of the file, but it still does not work.

**Comment by brantje** [comment]
Yea you can enable the console via admin settings. 
Go to `/settings/admin/additional`  
![image](https://user-images.githubusercontent.com/2758767/26992955-40b0a414-4d61-11e7-93b2-684597550b81.png)

**Comment by budachst** [comment]
I think, the import button only activates, after the CSV importer has successfully scanned the import file and deems it ok. I had that, when I tried to import a CSV, which was exported from PasswortDepot, and I had to manually tidy up the CSV before Passman would import it.

However, since this was likely a one-timer, I didn't bother too much about that. Importers are parsers and parsers are inherently difficult to write and as we have been showen a lot lately, they are prone to some of the biggest security issues.

What would probably be a good idea, would be an indicator that the parser had some diffuculties parsing the imput, so one could take a look at it.

**Comment by rugk** [comment]
> Yea you can enable the console via admin settings.

Ah, so this is not a bug, but a feature… Crazy thing, however.

**Comment by brantje** [comment]
@rugk Can you give me the first 4 lines of the csv? Replace username / password with something random.

**Comment by rugk** [comment]
I basically copied the whole CSV into another file (in parts as I wanted to debug it) and it worked. So maybe it was just the file name (?). See the screenshot in https://github.com/nextcloud/passman/issues/315#issue-234910228 for it.
At least the lines/entries looked okay.

**Comment by brantje** [comment]
Seems fixed, if not feel free to re-open.

**Comment by rugk** [comment]
Maybe the real fix would be to show the error message(s) from the CSV parser or so instead of silently ignoring them… Then the user at least knows, that something is wrong.

**Comment by bl4ckOut** [comment]
I had the same error as rugk:
Exported ~500 usernames in Firefox via Addon as CSV but the table didn't appear during custom import.
I had to remove all quotation marks, replaced double commas with simple ones and saved the file as CSV with UTF-8 support because of umlauts.
Then it worked.
