### ISSUE TITLE
Can't share with more than two users

### ISSUE THREAD

**Issue by TheVillux** [nextcloud/passman#316]
### Steps to reproduce
1. Create an entry in your own vault.
2. Click share.
3. Attempt to share with more than two other users who also have vaults.

### Expected behaviour
Third user should be added to the share list, as the first two users were.

### Actual behaviour
Third user is not added to the share list.

### Configuration
**Operating system**:   CentOS 7

**Browser**: Firefox 52.1.1

**Extensions that might cause interference**:   None

**Passman version**:    2.1.2

**Operating system**: CentOS 7

**Web server:** Apache 2.4

**Database:** MariaDB 5.5

**PHP version:** 7.1
      
**cloud server:** Nextcloud

**cloud version:** 12.0.0
  
   
#### Browser log
<details>
<summary>Browser log</summary>

```
Error: shareWith[z] is undefined
$scope.shareWith@https://server.example.com/nextcloud/apps/passman/js/passman.min.js?v=55555555555555555555555555555555-8:31:15752
anonymous/fn@https://server.example.com/nextcloud/apps/passman/js/passman.min.js?v=55555555555555555555555555555555-8 line 6 > Function:2:479
b@https://server.example.com/nextcloud/apps/passman/js/passman.min.js?v=55555555555555555555555555555555-8:4:29399
Lc[b]</<.compile/</</e@https://server.example.com/nextcloud/apps/passman/js/passman.min.js?v=55555555555555555555555555555555-8:7:9952
vf/this.$get</m.prototype.$eval@https://server.example.com/nextcloud/apps/passman/js/passman.min.js?v=55555555555555555555555555555555-8:5:7253
vf/this.$get</m.prototype.$apply@https://server.example.com/nextcloud/apps/passman/js/passman.min.js?v=55555555555555555555555555555555-8:5:7485
Lc[b]</<.compile/</<@https://server.example.com/nextcloud/apps/passman/js/passman.min.js?v=55555555555555555555555555555555-8:7:10002
n.event.dispatch@https://server.example.com/nextcloud/core/vendor/core.js?v=55555555555555555555555555555555-8:3:6414
n.event.add/r.handle@https://server.example.com/nextcloud/core/vendor/core.js?v=55555555555555555555555555555555-8:3:3224
" passman.min.js:4:25217
e/<() passman.min.js:4
hf/this.$get</<() passman.min.js:4
vf/this.$get</m.prototype.$apply() passman.min.js:5
Lc[b]</<.compile/</<() passman.min.js:7
n.event.dispatch() core.js:3
n.event.add/r.handle() core.js:3
```
</details>   

#### Cloud log

<details>
<summary>Cloud log</summary>

```
{"reqId":"55555555555555555","level":3,"time":"2017-06-13T20:56:27+00:00","remoteAddr":"xx.xx.xx.xx","user":"xxxx","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/passman\/api\/v2\/language?lang=en","message":"vsprintf(): Too few arguments at \/var\/www\/html\/nextcloud\/lib\/private\/legacy\/l10n\/string.php#72","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:45.9) Gecko\/20100101 Goanna\/3.2 Firefox\/45.9 PaleMoon\/27.3.0","version":"12.0.0.29"}

{"reqId":"55555555555555555","level":3,"time":"2017-06-13T20:56:27+00:00","remoteAddr":"xx.xx.xx.xx","user":"xxxx","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/passman\/api\/v2\/language?lang=en","message":"Method OC_L10N_String::__toString() must return a string value at \/var\/www\/html\/nextcloud\/lib\/private\/L10N\/L10N.php#85","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:45.9) Gecko\/20100101 Goanna\/3.2 Firefox\/45.9 PaleMoon\/27.3.0","version":"12.0.0.29"}
```
</details>

**Comment by brantje** [comment]
Confirmed. 
Happens in share.js in the following function [shareWith()](https://github.com/nextcloud/passman/blob/master/js/app/controllers/share.js#L205-L228)

**Comment by TheVillux** [comment]
Okay, thank you for the quick confirmation.

**Comment by brantje** [comment]
I have a fix ready, but it's late and i'm tired, want to make sure it works well.
Will test it tomorrow and push it.

**Comment by TheVillux** [comment]
No problem; just sent you $10.00 as a thank you.

**Comment by brantje** [comment]
Whoa great! Thank you very much!

**Comment by zguithues** [comment]
+1 on this issue.
It's a showstopper for me, as i need to share with 4 people.

Not trying to rush you, but any estimate on when you think you'll be pushing the update?

Thanks for this awesome password manager!

**Comment by brantje** [comment]
`Not trying to rush you, but any estimate on when you think you'll be pushing the update?`
Currently at work, but i'll do my best to release an update this weekend.

**Comment by zguithues** [comment]
Awesome! 

Thanks for the quick reply!

**Comment by zguithues** [comment]
I hate to be a pest, but did you have a chance to test this update?
If not, is there any easy way for me to run from the updated branch?

**Comment by brantje** [comment]
You can git clone this repo and you will have the fix.

**Comment by animalillo** [comment]
note: only use master, the other branches are not as stable or tested
