### ISSUE TITLE
Fuzzing

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman#320]
As I see you are having heavy issues with https://github.com/nextcloud/passman/issues/319, could you please do some fuzzing to automatically test such problems? Or some unit tests? This is really the worst kind of issue, which should never happen with a password manager.
When your password manager destroys your passwords you're lost.

**Comment by brantje** [comment]
Use the issue template

**Comment by rugk** [comment]
Done: https://github.com/nextcloud/passman/issues/321
