### ISSUE TITLE
LastPass and General CSV Import fails. Does nothing. No error.

### ISSUE THREAD

**Issue by BetaLeaf** [nextcloud/passman#327]
### Steps to reproduce
1. sudo -i
2. cd /var/scripts/
3. wget https://raw.githubusercontent.com/nextcloud/vm/master/apps/passman.sh
4. bash passman.sh
5. Attempt to import LastPass CSV and Generic CSV

### Expected behaviour
Import Success

### Actual behaviour
Import does nothing, not even an error to the user.

### Configuration
**Operating system**:   Windows 10 Creators Update (Client)

**Browser**:      Chrome Version 59.0.3071.109 (Official Build) (64-bit)

**Extensions that might cause interference**:   Maybe LastPass or AdGuard? I doubt it.

### Server configuration
**Operating system**: Linux cloud.betaleaf.net 4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64

**Web server:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.18

**PHP version:** 7.0.18-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, redis, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, ldap, exif, mcrypt, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, shmop, SimpleXML, smbclient, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 12.0.0 - 12.0.0.29
  
   
#### Browser log
<details>
<summary>Browser log</summary>

[cloud.betaleaf.net-1498524585906.log.txt](https://github.com/nextcloud/passman/files/1103871/cloud.betaleaf.net-1498524585906.log.txt)
</details>   

#### Cloud log

<details>
<summary>Cloud log</summary>

[nextcloud.log.txt](https://github.com/nextcloud/passman/files/1103893/nextcloud.log.txt)
[other_vhosts_access.log.1.txt](https://github.com/nextcloud/passman/files/1103897/other_vhosts_access.log.1.txt)
[error.log.1.txt](https://github.com/nextcloud/passman/files/1103898/error.log.1.txt)

</details>

### Description

When I try to import a Lastpass CSV password file, nothing happens after I click the import button.

**Comment by brantje** [comment]
Is the format still `url,username,password,extra,name,grouping,fav` ?

**Comment by animalillo** [comment]
I have recently had to use the lastpass importer, it works well, you have to open the export page, select all, copy that and then paste it into a plain text (.txt) file

The generic importer wont work with lastpass, they do some dirty things and don't follow csv standards.

The most important part it to save the file without any formatting (plain text), because the guy i helped importing saved it as rtf and it as some weird characters to the file

**Comment by BetaLeaf** [comment]
Hmm I did that but it didn't work the first time. I select all, copy, then paste it into a notepad and saved it as lastpass.csv and that failed. This time, I select all, copy, then paste it into Notepad++.exe and saved it as lastpass.txt and it worked.

**Comment by animalillo** [comment]
Glad you made it!
Lastpass is really annoying for exports >_<

**Comment by BetaLeaf** [comment]
I started using enpass instead. Passman isn't mature enough on android to be used and I've had trouble keeping the NextCloud VM running stable. If at any time my internet goes down, I have to restart the host computer to get the internet inside the VM back up. I'm gonna move back to Google Drive for now, though I will probably return eventually.

**Comment by brantje** [comment]
cc @enoch85 for the VM problem.
The Android app need some work yea, we know that, just 2 of us dev and 3 big projects to manage...

**Comment by enoch85** [comment]
> keeping the NextCloud VM running stable

@BetaLeaf That's strange. What did you change? Which are the symptoms?

**Comment by BetaLeaf** [comment]
Like I said, if at any time my host computer goes offline, the VM remains offline, even after the host regains an internet connection. Even if I restart the VM, it still remains unable to connect. I have to restart the host every time. I suppose I could just write a small program to reboot if the computer ever goes offline, but I hate having any downtime. I try and run ```sudo ifup -a``` and then ping 8.8.8.8 and I get told destination unreachable. I can't ping my box from my host, nor can I ping it from outside. I think it has something to do with VMware Workstation 12.5. I came from OwnCloud. They had a script you could run once you set up the operating system. I've tried Ubuntu 14.04, Ubuntu 16.04, and CentOS 5 and 6 and they all had issues maintaining an internet connection. It would just go down randomly for no reason and I never could figure out the issue. I got tired of it and just made a script to shut down the VM if it ever went offline via Guest Tools. This worked fine, then the power blinked and I lost all my data because the file system corrupted. I gave up on OwnCloud and moved to Nextcloud, where I had none of those issues, but now if the internet goes down, I have to restart the host pc to get it back up.

**Comment by enoch85** [comment]
@BetaLeaf Of course it goes down if your host goes down. This sounds more like an host issue than a VM issue. During my almost 5 years developing and running VMs in both ESXi and Hyper-V and Proxmox I never had such issues, and I never heard anyone else report them either.

With that said. Are you running a clean Nextcloud VM, and if so which version do you run, and which one did you start with?

The scripts that the ownCloud VM runs on was partly [developed by me as well](https://github.com/owncloud/vm/graphs/contributors), but the Nextcloud VM scripts are far more complex and detailed. In other words, they are better IMO.

**Comment by BetaLeaf** [comment]
Yea I know its a host issue. I am running the NextCloud 12 VM found at Github.com/nextcloud/vm/releases. Downloaded about a month ago. NextCloud 11 VM didn't have this issue, tho it did have an issue getting online initially which made the setup script fail.

**Comment by BetaLeaf** [comment]
and ofc its suppose to go down when my host goes down, but I expect it to come back up when the host comes back up too.

**Comment by animalillo** [comment]
Which vm host do you use?

My cloud is on a proxmox instance i created from scratch, i don't really like premade VMS.

**Comment by BetaLeaf** [comment]
VMware 12.5

**Comment by BetaLeaf** [comment]
I've also used Hyper-V 10 (was really slow for some reason) and VirtualBox 5.

**Comment by BetaLeaf** [comment]
Honestly, if I ever decide to run NextCloud again, I'll probably wipe down my server computer and just install Ubuntu 16.04 LTS as host and run NextCloud natively. I assume I can just download the install script from the github.com/NextCloud/VM/Apps folder and run it. 

Also, Windows 10 now has Bash support. Does that mean Windows 10 can now run NextCloud Server?

**Comment by enoch85** [comment]
This is even better: https://github.com/nextcloud/vm#installation
