### ISSUE TITLE
More colums

### ISSUE THREAD

**Issue by maestroi** [nextcloud/passman#33]
Add more colums in the home password screen.
now you need to click on it to see details, but there is plenty of space.

maybe make it setting for hide or not.

**Comment by brantje** [comment]
We can add an option to display a grid of passwords instead of an table.

**Comment by brantje** [comment]
Rough make up: 
![image](https://cloud.githubusercontent.com/assets/2758767/18890293/d2c838a0-8500-11e6-8d12-f386c07b1b50.png)

**Comment by brantje** [comment]
Fixed in 389fd23b669451167e2e4c5eee0eb3e6274cd37c

**Comment by maestroi** [comment]
Looks cool!
