### ISSUE TITLE
Lost Password

### ISSUE THREAD

**Issue by herohamp** [nextcloud/passman#331]
So I was having it my password vault just auto unlock, and it did that for multiple month, and now all the sudden it requires a password that I forgot :/ any suggestions?

**Comment by maestroi** [comment]
it could be inside your browser autofill, or saved credentials.
For firefox follow [This link](https://support.mozilla.org/en-US/kb/password-manager-remember-delete-change-and-import) 
There is now way at the moment to recover a vault, offten the i forgot my password mechanism is used to hack users in serveral services.

**Comment by brantje** [comment]
What @maestroi said. Lost vault passwords can't be recovered.
