### ISSUE TITLE
Showing plain text password in custom fields

### ISSUE THREAD

**Issue by torn87** [nextcloud/passman#335]
## Bug report
Can't hide password in custom field.
### Steps to reproduce
1. Create new entry in your storage.
2. Add custom field.
3. Choose type 'Password' and enter name and value.
4. Save.
5. Browse enter you've just created/

### Expected behaviour
See '********' and must be button to show/hide password in custom field/

### Actual behaviour
See plain text password, no button to hide/show password.

### Configuration
**Operating system**:   
Ubuntu 16.04
**Browser**:   
FireFox 54.0
**Extensions that might cause interference**:   
no
**Passman version**:    
2.1.2
**Operating system**:
Debian 8
**Web server:**
nginx
**Database:**
mariaDB 10.0.30-0
**PHP version:**
7.0.19-1
**cloud server:** Nextcloud 
**cloud version:** 12.0.0.29
  
   
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>   

#### Cloud log

<details>
<summary>Cloud log</summary>

```
{"reqId":"UAWBQ1MtMIQyrN4VTo07","level":3,"time":"2017-07-12T21:02:44+02:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxxxx","app":"PHP","method":"GET","url":"\/apps\/passman\/api\v2\/language?lang=en","message":"vsprintf(): Too few arguments at \/var\/www\/nextcloud\/lib\/private\/legacy\/l10n\/string.php#72","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko\/20100101 Firefox\/54.0","version":"12.0.0.29"}
{"reqId":"UAWBQ1MtMIQyrN4VTo07","level":3,"time":"2017-07-12T21:02:44+02:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxxxxx","app":"PHP","method":"GET","url":"\/apps\/passman\/api\/v2\/language?lang=en","message":"vsprintf(): Too few arguments at \/var\/www\/nextcloud\/lib\/private\/legacy\/l10n\/string.php#72","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko\/20100101 Firefox\/54.0","version":"12.0.0.29"}
```
</details>

## Feature request

**User type**: Logged-in user

**User level**: Beginners, intermediate or advanced

### Description
If you need some more information let me know, please

### Benefit / value
Password fields should not be visible by default.

### Risk / caveats
Plain text password. No comments.

### Sponsorship

 
**Are you a developer willing to implement this feature?**: no

**Can you sponsor the development of this feature or do you know someone who can?**: no

**Comment by budachst** [comment]
Yeah, I am seeing this also sometimes. Haven't yet figured out, what causes it. Interestingly, it seems that once one particular field shows this behaviour, I can also delete and recreate it and it again will show this.

**Comment by brantje** [comment]
Same here, have seen it, but not yet been able to reproduce it :/

**Comment by noplanman** [comment]
Was having the same problem. But then it started working properly when I created new custom password fields. Really strange 😕 

Seems a bit difficult to debug without diving deeper into the code, having the data in the DB encrypted and all.

Would be nice to have plain text while editing though, or the same visibility toggle as the entry password.
