### ISSUE TITLE
sharing with more than 2 users not working

### ISSUE THREAD

**Issue by tripcreator** [nextcloud/passman#338]
## Bug report

When a password is shared with 2 users and I want to share it with another the username
won´t get added to the list (with the checkboxes)

### Steps to reproduce
1. share password with 2 users
2.try adding a third one

### Expected behaviour

user should be added and checkboxes should be visible

### Actual behaviour

nothing

### Configuration
**Operating system**:   ubuntu 16.04 / windows 10 / mac os

**Browser**:      chrome / firefox / safari same problem

**Passman version**:    2.1.2
      
**cloud server:** Nextcloud

**cloud version:** 12.0.0
  
   
#### Browser log
<details>
<summary>Browser log</summary>
same problem here:
sharing with other users works without problems just this one after selecting won´t get added to the
list (with the checkboxes)

Error: shareWith[z] is undefined
$scope.shareWith@https://x.x/apps/passman/js/passman.min.js?v=d45765c70c3075e276cf3d1229b859f7-19:31:15752
fn@https://x.x/apps/passman/js/passman.min.js?v=d45765c70c3075e276cf3d1229b859f7-19 line 6 > Function:4:479
b@https://x.x/apps/passman/js/passman.min.js?v=d45765c70c3075e276cf3d1229b859f7-19:4:29399
e@https://x.x/apps/passman/js/passman.min.js?v=d45765c70c3075e276cf3d1229b859f7-19:7:9952
$eval@https://x.x/apps/passman/js/passman.min.js?v=d45765c70c3075e276cf3d1229b859f7-19:5:7253
$apply@https://x.x/apps/passman/js/passman.min.js?v=d45765c70c3075e276cf3d1229b859f7-19:5:7485
compile/</<@https://x.x/apps/passman/js/passman.min.js?v=d45765c70c3075e276cf3d1229b859f7-19:7:10002
dispatch@https://x.x/core/vendor/core.js?v=d45765c70c3075e276cf3d1229b859f7-19:3:6414
add/r.handle@https://x.x/core/vendor/core.js?v=d45765c70c3075e276cf3d1229b859f7-19:3:3224
</details>   

#### Cloud log

<details>
<summary>Cloud log</summary>

```
Insert your cloud log here
```

Error | PHP | Method OC_L10N_String::__toString() must return a string value at /var/www/nextcloud/lib/private/L10N/L10N.php#85 | 2017-07-20T07:49:05+0200
-- | -- | -- | --
Error | PHP | vsprintf(): Too few arguments at /var/www/nextcloud/lib/private/legacy/l10n/string.php#72 | 2017-07-20T07:49:05+0200
Error | PHP | Method OC_L10N_String::__toString() must return a string value at /var/www/nextcloud/lib/private/L10N/L10N.php#85 | 2017-07-20T07:48:16+0200
Error | PHP | vsprintf(): Too few arguments at /var/www/nextcloud/lib/private/legacy/l10n/string.php#72 | 2017-07-20T07:48:16+0200
Error | PHP | Method OC_L10N_String::__toString() must return a string value at /var/www/nextcloud/lib/private/L10N/L10N.php#85 | 2017-07-20T07:37:09+0200
Error | PHP | vsprintf(): Too few arguments at /var/www/nextcloud/lib/private/legacy/l10n/string.php#72

</details>

**Comment by brantje** [comment]
This is fixed in master and, will be releases soon
