### ISSUE TITLE
Owncloud 10 installation

### ISSUE THREAD

**Issue by gschoenberger** [nextcloud/passman#339]
## Bug report
Signature validation throws an exception
### Steps to reproduce
1. Download latest release and extract to owncloud -> apps folder
2. Try to enable app via "Apps management"

### Expected behaviour
Successfully enable app and install passman

### Actual behaviour
App is not enabled, owncloud throws an exception:
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- passman-2.1.2
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [passman-2.1.2] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)
```

### Configuration
* cloud version: 10.0.2.1

## Possible fix
Create a valid signature.jsonp:
https://doc.owncloud.org/server/latest/admin_manual/issues/code_signing.html

**Comment by brantje** [comment]
Uch, seems they changed this again. Getting tired of supporting ownCloud.

**Comment by brantje** [comment]
Also seems they break their own programming logic:
```
Is Code Signing Mandatory For Apps?
Code signing is optional for all third-party applications.
```

**Comment by gschoenberger** [comment]
Any change to skip the code signing for passman?

**Comment by brantje** [comment]
Nope, that's ownCloud core. ATM we don't have time to their special little tricks, and it should work without signing, as stated on their page. If it doesn't open an issue at their core repo.
