### ISSUE TITLE
password groups and sharing

### ISSUE THREAD

**Issue by pafcioooo** [nextcloud/passman#340]
This is an enhancement.

There should be possibility to share multiple passwords at once, so when a new person joins a team, and we have some shared passwords we can share all of them at once not just sharing one by one.

This could be done by adding a folders or category entity for passwords and sharing entity with its containing passwords.

**Comment by animalillo** [comment]
We are currently working on #243 that would allow sharing complete vaults, I think that could solve your issue.

**Comment by brantje** [comment]
Yea dupelicate of #246

**Comment by pafcioooo** [comment]
Well, it is not the same. I suppose that sharing vault requires having different vault for different groups, and me changing them all the time when using web browser extensions (this requires entering password for the vault).
The enhancement here make easy to share passwords for a group of users within vault. Take this scenario:

- We can have vaults for different customers (actually what we do, we use only one vault so it is easier to use application extensions)
- Customer vaults can have different passwords, 
- Now we have internal teams, each team can have different access to different passwords within one vault
- When someone joins the team he is automatically allowed to access team passwords.
