### ISSUE TITLE
Different copy icons in add-on and web

### ISSUE THREAD

**Issue by rugk** [nextcloud/passman#348]
### Expected behaviour
The copy icons should be the same.

### Actual behaviour
add-on: 
![grafik](https://user-images.githubusercontent.com/11966684/29004520-f653bcea-7ac8-11e7-82f7-bcc72a06901d.png)

web:
![grafik](https://user-images.githubusercontent.com/11966684/29004523-fd6e6c96-7ac8-11e7-9eba-0e9e92c7114d.png)

The web version is actually a paste icon, so…

### Configuration
**Operating system**: Linux

**Browser**: FF 54.0.1

**Passman version**: 2.1.4

**PHP version:** 7
      
**cloud server:** Nextcloud

**cloud version:** 12

**Comment by brantje** [comment]
Correct icon class is `fa fa-files-o`
