### ISSUE TITLE
Password tool

### ISSUE THREAD

**Issue by maestroi** [nextcloud/passman#35]
Change name of Password tool to something like, "Password Audit".

- [ ] - Put it on a easyer to find place.
- [x] - Default set minimum password length to the global minimum password length (see other issue).
- [ ] - Put in the time to take to crack it with a normal desktop computer.
- [ ] - Some grammatical flaws.

**Comment by brantje** [comment]
Where do you have in mind?
What are the grammatical flaws?

**Comment by maestroi** [comment]
somewhere on main page should be good, also with import it should check for insecure passwords.

**Comment by brantje** [comment]
Closed due inactivity.
