### ISSUE TITLE
Not working with many (O(100)) passwords

### ISSUE THREAD

**Issue by FrederikLauber** [nextcloud/passman#350]
Hello,

I have some problems with passman, both for importing and deleting passwords.
Trying to import roughtly 300 passwords from a LastPass csv will gets stuck at roughtly 100 passwords.
The 100 passwords will get imported which means you cannot repeat the rpocess as it will lead to many dublicates.

Trying to delete this many passwords via the "Delete all my preious passwords" option gets tuck at roughtly 50 passwords.

Is there somethign I can do if I have to deal with many (O(100)) passwords?

Thansk in advance

### Steps to reproduce
1. Try to import somethign from a lastpass csv
2. See the importer get stuck ad roughtly 100 Passwords
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
All Passwords shoud be imported or none

### Configuration
**Operating system**: 
Windows 10

**Browser**: 
Firefox 55

**Extensions that might cause interference**:  

**Passman version**:    
2.1.4

**Operating system**:
CentOS 6

**Web server:**
Apache 2.2

**Database:**
MariaDB 10.0

**PHP version:**
7.0.5
      
**cloud server:** Nextcloud or ownCloud
nextcloud

**cloud version:** (see admin page or version.php)
11.0.3

**Comment by brantje** [comment]
Can you please fill in the issue template?

**Comment by brantje** [comment]
Also, can you try to paste the contents of the csv in a plain text file?
Make a new file using `notepad` (Windows) or something like `gedit`(Linux), and paste the contents from the export there.
Maybe #327, #233 or https://github.com/nextcloud/passman/issues/315#issuecomment-308862469 can help you out. 
Usually the CSV is malformed, and needs to be corrected.

**Comment by FrederikLauber** [comment]
Hi,

obviously I cannot jsut upload the csv file, it contains all my passwords but i will try the tipps in the appended tickets. 

Also, even if this was the rpoblem, deleting passwords shoud be working which it is not.

**Comment by brantje** [comment]
Will look at the delete vault functionality
