### ISSUE TITLE
Neutral screenshots

### ISSUE THREAD

**Issue by brantje** [nextcloud/passman#351]
Passman got uploaded to the ownCloud market.
But, ownCloud doesn't like that our screenshots contain Nextcloud:
```
We are happy to welcome you on board but i need to ask you kindly,   
if you could update the screenshots you uploaded within your app.       
As they show your app inside a Nextcloud installation we would    
love to see neutral or ownCloud branded screenshots.
```
If we switch to ownCloud screenshots, Nextcloud would complain.   
Therefore it seems logic to me to make some neutral screenshots.   
- Replace the Nextcloud logo with the passman one
- Change the color scheme a bit.

**Comment by animalillo** [comment]
Annoying bitching, this looks like some, sorry for the rent, had to share my thought with the community

**Comment by brantje** [comment]
Yea, but i think Apple doesn't allow Android screenshots in their store ;)

**Comment by animalillo** [comment]
Exactly my point, i dont like this kind of things, specially if you don't live from the project

**Comment by brantje** [comment]
Images have been updated on the image server.
