### ISSUE TITLE
Generic importer stops working with german umlauts (äöü...) in ansi coded csv file

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/passman#352]
### Steps to reproduce
1. Import csv file with umlauts in ansi coded file with generic importer
i.e. (exported from Firefox)
`# Generated by Password Exporter; Export format 1.1; Encrypted: false`
`"hostname","username","password","formSubmitURL","httpRealm","usernameField","passwordField"`
`"https://foo.com","fooname","foopass","https://foo.com","ä","field_username","field_passwort"`

Changing the coding to UTF-8 solves the issue.

### Expected behaviour
Import the password file

### Actual behaviour
Nothing happens

### Configuration
**Operating system**:   Windows
**Browser**:      Firefox, Chrome
**Extensions that might cause interference**:   None
**Passman version**:    2.1.4
**Operating system**: Linux
**Web server:** Apache
**Database:** MySQL
**PHP version:** 7.1
**cloud server:** Nextcloud 
**cloud version:** 12.0.0 and 12.0.1
  
#### Browser log
No info in log files

**Comment by brantje** [comment]
Can you encode as UTF-8 and try again?

**Comment by dartcafe** [comment]
As I said: It works, when I encode the file as UTF-8. The Password Exporter (Firefox Add-on) saves the export CSV encoded in ansi.

**Comment by dartcafe** [comment]
Additionally, maybe comment lines (the first in the example) should be ignored, when importing...

**Comment by brantje** [comment]
In browser are umlauts UTF-8 chars afaik. I think that's the reason it crashes.
Will give it a try this weekend

**Comment by brantje** [comment]
Jup, files with special chars need to be encoded as UTF-8 or import will fail.
Will add a proper message if the file is not UTF-8 encoded.
