### ISSUE TITLE
2 nodes

### ISSUE THREAD

**Issue by Arktorion** [nextcloud/passman#359]
Hello! I have one question: Where passman keep users vaults? I ask you about it because I want use next configuration: 2 nodes of owncloud with haproxy balancer and user base on separate server.

Thank you for your answer=)

**Comment by animalillo** [comment]
Hello, everything passman stores is stored on your configured nextcloud database. So to set up an HA balancer it should be pretty simple.

I would recommend checking the nextcloud tips on this matter, which I'm not currently aware of.

If you want to share your findings here it will be awesome to have it as a reference for other users tho!

I will gladly answer any further questions you might have.

**Comment by Arktorion** [comment]
Hello, it's really awesome and it works! (I used cfg with 2 nodes and database connected with nfs). I also tried use it with LDAP, but it can support only names in english.
Did you thinking about integration it with another languages?

**Comment by brantje** [comment]
Passman has an API. At the moment we are busy enough with the app, android and the browser extension. But we love to see what the community can build.

**Comment by animalillo** [comment]
I'm glad you made it work!
Did you take any passman specific steps?

**Comment by Arktorion** [comment]
Animalillo, I didn't make any specific steps. Only installed it on every owncloud server and used it.

**Comment by animalillo** [comment]
Cool! Bear in mind server side encryption is handled via the secret keys stored on your nextcloud config file, so that must be shared across all instances. Otherwise you might get unexpected results.

**Comment by brantje** [comment]
@Arktorion you ok if i close this issue?
