### ISSUE TITLE
No login for Android Firefox plugin?

### ISSUE THREAD

**Issue by chrislachance** [nextcloud/passman#366]
### Steps to reproduce
1. Install Passman for Firefox on Android.
2. Restart Firefox, click on Passman menu option. No way to login.
3. Click on extension itself, still no way to login.

### Expected behaviour
Tell us what should happen
I should be able to login to my Nextcloud instance somehow.

### Actual behaviour
Tell us what happens instead
Nothing, and no way to initiate process.

### Configuration
**Operating system**:   Android

**Browser**:      Firefox

**Extensions that might cause interference**:   None

**Passman version**:    Latest

**Operating system**: Android

**Web server:** N/A

**Database:**N/A

**PHP version:**N/A
      
**cloud server:** Nextcloud

**cloud version:** N/A
  
   
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:
Not sure how to do that in Firefox mobile.

a) The javascript console log
b) The network log
c) ...
```
</details>   

#### Cloud log

<details>
<summary>Cloud log</summary>

```
Insert your cloud log here
N/A
```
</details>

## Feature request

**User type**: Logged-in (or not in this case)

**User level**: Beginners

### Description

I just want to login

### Benefit / value

I can use it on my phone

### Risk / caveats

No more than on the desktop instance

### Sponsorship

?
 
**Are you a developer willing to implement this feature?**: No

**Can you sponsor the development of this feature or do you know someone who can?**: No

**Comment by brantje** [comment]
https://github.com/nextcloud/passman-webextension/issues/75
