### ISSUE TITLE
url arguments checking

### ISSUE THREAD

**Issue by witte1000** [nextcloud/passman#369]
Hello Brantje & Co,

First of all congratulations with all the work done it's amazing how fast you guy's are going !!!

## Feature request

We are testing your passman firefox addon witch is an illumination but we found a little small issue.
Like you know we are a DBA company with some special needs ;)

The little small issue what we encounter is following (try to explain).

when we go to http://www.site.com/logcontrol/f?p=123 and save the password for this site,
then we go to http://www.site.com/logcontrol/f?p=456 witch is a complete different site,
then the account of the first site /f?p=123 also appear or 

if we go to http://www.site.com/logcontrol/f?p=420 and save the password for this site,
going then to http://www.site.com/testapps/f?p=4550 witch are complete different sites then also appear the other account.
This can be very annoying specially if you have a bunch of those special sites. 
So would it be possible that you can add a checkbox where we can add the url arguments string.
So it wouldn't change anything (backward compatible) but for us a hole illumination.
There is no other password manager we know who has this feature !!!
Passman will become the first and best proper password manager ;)

Btw: I'm not able anymore to connect to the mattermost ...

Very much appreciation 
And thanks in advance,

Kind Regards,

witte

**Comment by brantje** [comment]
I think this issue belongs in the nextcloud/passman-webextension repo, can you move it to there?
Thanks in advance.

**Comment by witte1000** [comment]
I'm sorry 
i move it thanks
