### ISSUE TITLE
Credential - Save button is busy forever after the "passwords do not match" message.

### ISSUE THREAD

**Issue by rNoz** [nextcloud/passman#370]
### Steps to reproduce
1. Create a new credential
2. Set two different passwords
3. Click "Save"

### Expected behaviour
You should be able to try again by clicking to "Save" after some modification.

### Actual behaviour
You are warned about "passwords do not match" but the "Save" button is busy (gray and with a loading animation inside it). I have been waiting up to 40 seconds and nothing changes. So, it is impossible to try again. You have to cancel and start from zero to create a new credential.

### Configuration

Ubuntu 16.04

Firefox 55

Passman Local version: 2.1.4

Nextcloud 11.0.2 (stable)

PHP
Version: 7.0.17
Memory Limit: 512.0 MB
Max Execution Time: 3600
Upload max size: 4.0 GB

Database
Type: pgsql
Version: PostgreSQL 9.6.1 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2, 64-bit
Size: 48.0 MB

**Comment by barry-luijten** [comment]
I just installed Passman on my Nextcloud 12.03@Ubuntu 16.04 instance and I encountered this exact same behavior on my first entry.
PHP 7.1
Client: Chrome 60.0.3112.113 x64 on Windows 10
