### ISSUE TITLE
Clicking on the "home" icon does not go to home

### ISSUE THREAD

**Issue by synthead** [nextcloud/passman#372]
### Steps to reproduce
1. Open Passman in Nextcloud.
2. Click on the "home" icon.
3. Observe that nothing happens.

### Expected behaviour
Clicking "home" should go to the view with the available vaults.

### Actual behaviour
Nothing happens, as if the JS event isn't triggering the right thing.

### Configuration
**Operating system**: Arch Linux

**Browser**: Chromium 61.0.3163.100

**Extensions that might cause interference:** uBlock Origin

**Passman version:** 2.1.4

**Operating system:** Arch Linux

**Web server:** Nginx and uWSGI

**Database:** PostgreSQL 9.6.5

**PHP version:** 7.1.10
      
**cloud server:** Nextcloud

**cloud version:** 12.0.3

**Comment by OS3DrNick** [comment]
I used the button numerous of times and never noticed it, 
but it seems only to pop-up (the error) inside the main vault view.
The link to the logout is empty.

Fix:

Change line 6 on file 'templates/views/show_vault.html' to:
`<a ng-click="logout()"><i class="fa fa-home"></i></a>`
