### ISSUE TITLE
Enpass txt Importer doesn't work properly

### ISSUE THREAD

**Issue by TobiasMie** [nextcloud/passman#374]
Everything that is imported is a 'custom field' so that the passwords are displayed in plain text and the autofill doesn't work. I think it is caused by the different field names, but I dint know how the importer work.

**Comment by brantje** [comment]
That is intended behavior of the importer. 
Enpass uses field names in the native language of the user.
For example, the password field is called `Wachtwoord` here.
It would be possible to map those values, but then i need every single translation of the words `Username` and `Password`. Which would be a pain to maintain.

That is the reason why EnPass fields are added as custom fields.
