### ISSUE TITLE
Categories for passwords

### ISSUE THREAD

**Issue by phl0** [nextcloud/passman#375]
## Feature request

**User type**: Logged-in user

**User level**: Beginner

### Description

It would be helpful if passwords could be organized in categories. So you can have a set of account credentials for home use, one for office use for example. Currently passman only lists all passwords in a single list which itself (at least in my case) is not even sorted. Especially using the app on smartphones is very difficult due to this issue.

### Benefit / value

Especially if handling a large number of passwords it would be helpful to list accounts by category. On smart phones it is cumbersome to scroll hundrets of lines of (unsorted) accounts.

### Risk / caveats

none

### Sponsorship
 
**Are you a developer willing to implement this feature?**: no

**Can you sponsor the development of this feature or do you know someone who can?**: no

**Comment by brantje** [comment]
Passman doesn't has categories, instead we have a tag system that works imo, much better than categories.

You can use tags to categorize your passwords. 
Tags will appear on the left, in the menu.
When you click on a tag only credentials matching that tag will be shown.

**Comment by animalillo** [comment]
Check out the [https://github.com/nextcloud/passman/wiki/TAGS](TAGS documentation)
