### ISSUE TITLE
Questions about functions

### ISSUE THREAD

**Issue by emillod** [nextcloud/passman#380]
Hello.
1. Is there option to backup all credentials from SSH? In automate backup ?
2. Is there any chance to sync PassMan with KeePass database?

**Comment by animalillo** [comment]
Let me answer your questions:
1. You could backup your file database and the config file using ssh if you wanted. We don't have such feature or script, bit it's entirely possible.

If you choose to make that, keep in mind that everything would be still encrypted, by the key stored in the config file and by the key you used to set up the vault, so this method only prevents against hardware failure, not against brain failure ;)

2. We don't have any sync methods with external services however, we provide importers for a lot of password managers, they are on the vault config section.

**Comment by emillod** [comment]
Thanks for reply ! :) 
Back to question 1. I need something like backup to make sure, that i don't lose my passwords :)

**Comment by brantje** [comment]
You can use mysqldump for dumping the database. 
I use something like this:
```
mount /mnt/backup
mysqldump -u nextcloud -p"mySuperSecretPassword" nextcloud > /mnt/backup/db.sql
cp /var/www/config/config.php /mnt/backup/
```
This way you can backup your passwords.
Above script is out of my head, untested, but you get the idea.

**Comment by emillod** [comment]
G. thanks :) 
In this script i have dump everything from nextcloud database, right? Not just passman?
And also is there any chance to share my voult passman with someone else? I mean some other users of same nextcloud instance :)

**Comment by brantje** [comment]
Yea it will dump the whole database, and in my case the mounted backup folder is on my nas, which has BTRFS file system with snapshots. If you like a date in the file name, i can update the script =).

You can already share a single credential, see #243 for sharing of complete vaults.

**Comment by emillod** [comment]
I saw something about sharing, but i have in mind something like sharing the whole vault. :D 
About your script, maybe i'll try create VeraCrypt container for this :) 

Can you share with me some thoughts about Passman? I'm new here :D 
I heard few nice things about Passman, but few friends have also issues with Android App.

**Comment by brantje** [comment]
Welcome ^_^. Just ask away, i'll be happy to help you out.

**Comment by emillod** [comment]
You think Passman is comfortable? and secure ? :P

**Comment by brantje** [comment]
With about 1500 chrome extension users and 1000 firefox users i think i can call Passman comfortable.
The webextension allows you to use multiple vaults in the same browser. So you can have a work vault, a private vault, and so on.

For the security part i would like to refer you to the readme, section [storing credentials](https://github.com/nextcloud/passman#storing-credentials).
A TLDR for that info: As long you keep the vault key secure you're secure.
As an additional layer, Passman encrypts the passwords also server-side, just in case.

**Comment by emillod** [comment]
Thanks :)

**Comment by brantje** [comment]
Issue seems resolved, closing.
