### ISSUE TITLE
Export Vault to Keepass file in CLI

### ISSUE THREAD

**Issue by iMowgli** [nextcloud/passman#391]
It will be nice if we can export Vault to a keepass file , from Php CLI to easily backup passwords with a Cron

**Comment by brantje** [comment]
Can you please use the issue template? Thanks

**Comment by brantje** [comment]
Also exporting with a cron is not possible. Because then the server needs access to users password, which is against our design principle (server never knows users vault password)

**Comment by brantje** [comment]
Closing, impossible due clientside limitations
