### ISSUE TITLE
No Support Forum ?

### ISSUE THREAD

**Issue by compumatter** [nextcloud/passman#392]
Hello,

I have searched high and low and cannot find a forum for passman users to help each other or table questions.

Do you have this somewhere ?

In particular my question is this:

If I share a password with another nextcloud / passman user, and they in turn choose to export their passwords - will this export the one I shared with them and if so, how can I prevent this ?

I wish for my staff to have access to this password but I do not want them to be able to export it so easily.

Thanks.

Jay Lepore
CompuMatter

**Comment by centerboy88** [comment]
Make it not visible

mit freundlichen Grüßen

Dennis Scholz

Am 07.11.2017 3:50 nachm. schrieb "compumatter" <notifications@github.com>:

**Comment by brantje** [comment]
We have a sub forum on the Nextcloud forum: https://help.nextcloud.com/c/apps/passman
Although i'm not very often there (due lack of webhooks in their forum), i'll check it once in a while.
