### ISSUE TITLE
Shared with Groups Not Working

### ISSUE THREAD

**Issue by compumatter** [nextcloud/passman#396]
### Steps to reproduce
1. Login to vault
2. Share credential
3. Type Group name

### Expected behaviour
Existing Nextcloud Group should populate and allow me to share the credential with an entire group at once.

### Actual behaviour
The existing Nextcloud Group does not show up. I have tried with multiple groups but it ignores any Group entries in that field - Youtube Video: https://www.youtube.com/watch?v=nOQdhj-RAuc

### Configuration
**Operating system**:   Windows 7

**Browser**:      
Chrome

**Extensions that might cause interference**:   

**Passman version**:  2.1.4

**Operating system**: Windows 7

**Web server:** Apache 2+

**Database:** Mysql

**PHP version:** 7.0+
      
**cloud server:** Nextcloud 

**cloud version:** 12.0.3
  
   
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:
See attached firebug and chrome
```
</details>   

#### Cloud log

<details>
<summary>Cloud log</summary>

```
Insert your cloud log here (Tailed it.  No errors thrown)
```
</details>
![nextcloud-passman-group-field](https://user-images.githubusercontent.com/121611/32520060-92c9572c-c3c3-11e7-8847-30f7443da86e.png)
![nextcloud-active-groups](https://user-images.githubusercontent.com/121611/32520061-92e670c8-c3c3-11e7-8516-008b9d7e7835.png)
![nextcloud-chrome-debugger](https://user-images.githubusercontent.com/121611/32520063-93427a08-c3c3-11e7-8544-6658037695c8.png)
![nextcloud-firebug-debugger](https://user-images.githubusercontent.com/121611/32520064-935af6b4-c3c3-11e7-96dc-399bcc3770a9.png)

**Comment by animalillo** [comment]
groups are not supported in sharing

**Comment by brantje** [comment]
Sharing with groups is not supported. And won't be, as you need to be logged into your vault when you add   / remove users from groups.

**Comment by compumatter** [comment]
OK but it specifically offers the word Users and Groups as a sharing option?

**Comment by brantje** [comment]
Good one, will rephrase that in next version

**Comment by compumatter** [comment]
It is unfortunate as this would be a great feature to share a credential with a group of folks in one shot.

**Comment by brantje** [comment]
That is the one big down side of using client side encryption and the server not knowing the vault key.

**Comment by jcklpe** [comment]
@brantje Not to be a bug but this still seems to be an issue. I just set up an org to handle password management on nexcloud and the button still says "share with users and groups" when I try to share, and only individual usernames come up.
