### ISSUE TITLE
Importing Lastpass had to delete Lastpass notes from .cvs

### ISSUE THREAD

**Issue by leighss** [nextcloud/passman#399]
Import credentials would not work until I deleted the last entries that were for Lastpass 'secure notes'
Then worked perfectly
Not really a problem, but could help if this info on Wiki?

**Comment by brantje** [comment]
Did you see this one: https://github.com/nextcloud/passman/wiki/Importing:Lastpass ?

**Comment by leighss** [comment]
Yes, I thought that the extra info not included there about deleting any entries for 'Secure Notes' would be helpful

**Comment by compumatter** [comment]
I updated the wiki post to include your notes.  https://github.com/nextcloud/passman/wiki/Importing:Lastpass 

Will close it now.  

Thank you.
