### ISSUE TITLE
Errors on sharing password

### ISSUE THREAD

**Issue by Mte90** [nextcloud/passman#400]
### Steps to reproduce
1. Share a password
2. Set an user
3. Share Button not enabled

### Expected behaviour
Button enabled ready to share the link

### Actual behaviour
The share button is not enabled and the console is opened with the debugger (same on Firefox and Chrome).

### Configuration
**Operating system**:   Linux

**Browser**:   Firefox Nightly, Firefox Dev and Chrome

**Passman version**:   2.1.4
      
**cloud server:** Nextcloud

**cloud version:** 12.0.3
  
   
#### Chrome Browser log
<details>
<summary>Browser log</summary>
```
passman.min.js?v=96d016e173f0cd7874887e9bdf2dbf68-5:27 Crypto stuff initialized
initEngines @ passman.min.js?v=96d016e173f0cd7874887e9bdf2dbf68-5:27
core.js?v=96d016e173f0cd7874887e9bdf2dbf68-5:sourcemap:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ core.js?v=96d016e173f0cd7874887e9bdf2dbf68-5:sourcemap:4
/index.php/apps/passman/#/vault/6A815903-ADD9-4E7B-A780-E8FB7D3EE600/A1EB0410-966D-4056-A9AA-3B92EAD15861/share:1 Failed to decode downloaded font: https://domain/apps/passman/css/fontawesome-webfont.woff2?v=4.6.3
/index.php/apps/passman/#/vault/6A815903-ADD9-4E7B-A780-E8FB7D3EE600/A1EB0410-966D-4056-A9AA-3B92EAD15861/share:1 OTS parsing error: invalid version tag
DevTools failed to parse SourceMap: https://domain/core/vendor/purify.min.js.map
```
</details>   

#### Firefox Browser log
<details>
<summary>Browser log</summary>
```
Errore mapping di origine: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
URL risorsa: http://domain/core/vendor/core.js?v=96d016e173f0cd7874887e9bdf2dbf68-5
URL mapping di origine: purify.min.js.map
[Ulteriori informazioni]
Crypto stuff initialized
passman.min.js:27:26050
GETXHR
http://domain/index.php/apps/passman/api/v2/sharing/credential/A1EB0410-966D-4056-A9AA-3B92EAD15861/acl
[HTTP/1.1 200 OK 292ms]
Una richiesta XMLHttpRequest sincrona sul thread principale è deprecata a causa degli effetti negativi sull’esperienza utente. Per ulteriori informazioni consultare http://xhr.spec.whatwg.org/
core.js:4:14346
L’attributo “content” degli oggetti Window è deprecato. Al suo posto utilizzare “window.top”.
```
</details>

**Comment by animalillo** [comment]
Would be nice to know the following points:
1.Does the target user have created any vaults?
1.Have you previously shared and unshared said credential? There is a known bug on the sharing system when performing this action.

**Comment by Mte90** [comment]
* All the users have their vaults
* In the past I never shared a password, now I need to do it and I found that bug

**Comment by animalillo** [comment]
Did you select the users and assign permissions to them?
You need to add them to the list.

**Comment by Mte90** [comment]
Can you explain better? What kind of permission? What is the page?

**Comment by animalillo** [comment]
sure thing, i have just written an article regarding sharing usage just for you. Please take a look and tell us if you still have any trouble.

https://github.com/nextcloud/passman/wiki/Sharing

**Comment by Mte90** [comment]
Thank you, as screenshot in my installation after selecting the user doesn't appear the list with permission so maybe there is something that not happen after add the user in the field

**Comment by animalillo** [comment]
did you click the "+" button?

**Comment by Mte90** [comment]
ok now I got it!

**Comment by animalillo** [comment]
Glad I have been able to solve your issue! :D
