### ISSUE TITLE
Unable to get OTP working :(

### ISSUE THREAD

**Issue by vincegre** [nextcloud/passman#401]
### Steps to reproduce
1. Connect to my Nextcloud instance and select Passman app
2. Find the amazon record for my accound and edit it to add the OTP
3. Uploaded the OTP picture supplied by Amazon, accepted by system but it doesn't generate any code (Sample picture attached)
![index](https://user-images.githubusercontent.com/3164888/32839270-358c08b4-ca14-11e7-91a6-b5d92cf53b26.png)

4. Instead of uploading picture I copied/paste code given by Amazon but mot much better (sample code: KWCG QSZQ 2GPY PRUM FDSM KSJQ OBE3 ZUGP O55W VQHG EBB2 DZ4J KZFQ)

### Expected behaviour
It should generate the OTP codes corresponding to setup done previously

### Actual behaviour
It accepts the picture code or the string code but doesn't generate any OTP code to use for authentification

### Configuration
**Operating system**:  Ubuntu 16.04.2 

**Browser**: Firefox Quantum (57)

**Extensions that might cause interference**:   no other extension in browser

**Passman version**:    

**Operating system**: Ubuntu 16.04.2

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.0
      
**cloud server:** Nextcloud

**cloud version:** 11.0.4

**Comment by brantje** [comment]
The javascript fails on: `String of HEX type must be in byte increments` same as in #293, so this is a duplicate. Closing.
