### ISSUE TITLE
 passman update 2.15 download with github it lost passman database 2.14 to passman update 2.15 download with github it lost passman database 2.14 

### ISSUE THREAD

**Issue by peturbg** [nextcloud/passman#402]
HI guys i just see there is new verson 2.15 and i update from github and when i enter to see 2.15 it comment me there is no vault. No vaults found, why not create one? So how can recover the vault from version 2.14 for 2.15

thanks too for the great program.

**Comment by animalillo** [comment]
Did you check on your database if your data is gone? You should check for passman_ tables

If there is no data there, there isn't really much we can do. Except hoping that you made backups, as you should with every update of anything delicate.

Wish you best luck

**Comment by animalillo** [comment]
Did you check on your database if your data is gone? You should check for passman_ tables

If there is no data there, there isn't really much we can do. Except hoping that you made backups, as you should with every update of anything delicate.

Wish you best luck

**Comment by peturbg** [comment]
where is passman_table

**Comment by brantje** [comment]
Dude, it works fine, no need to name the issue like this

**Comment by brantje** [comment]
The table is called **dbprefix*passman_vaults` for vaults and `*dbprefix*passman_credentials` for credentials. There is NO drop table or what ever included in passman. So if the tables got dropped it's a problem in the upsteam (so nextcloud in this case).

**Comment by animalillo** [comment]
The updates are handled by the owncloud/nextcloud core, you should follow their update and procedures, not really much we can do about it.
Also, you didn't follow the issue template.

1. What version of passman where you using before the update?
1. What version of passman did you update to?
1. What (owncloud / nextcloud) and what version are you using?
1. What database system do you use? What version?
1. Operating system of your server and version?
1. Did you get any errors durning update?
1. Any relevant log lines?

We need all that info we request on the issue template you just ingnored. I might forget some relevant info we need.

**Comment by brantje** [comment]
Btw, 2.15 isn't even released yet. So you're basically trying beta software.

**Comment by peturbg** [comment]
brantje... i like how you lie yourself. Include you are try indirect to damage insult and etc. me. brantje do you know that i use beta software. brantje i will ask you simple. brantje how porcentage " % " you are sure i use beta software. brantje do you know my life to LIE what i use and what i don't use. brantje before you try attack you need to start respect the other person. I will not tell anything more. Regardles passman the fault is in passman becouse when i open passman it comment new version in github 2.15 you have 2.14 so who have the culpt. T

**Comment by peturbg** [comment]
brantje... i like how you lie yourself. Include you are try indirect to damage insult and etc. me. brantje do you know that i use beta software. brantje i will ask you simple. brantje how porcentage " % " you are sure i use beta software. brantje do you know my life to LIE what i use and what i don't use. brantje before you try attack you need to start respect the other person. I will not tell anything more. Regardles passman the fault is in passman becouse when i open passman it comment new version in github 2.15 you have 2.14 so who have the culpt. normal user open passman and it comment there is new version in github. So this is like you drink water but you don't know if the bottle is empty.

**Comment by brantje** [comment]
Well first of all, i'm not being rude. Second, i don't like being called a **liar**. 
I test passman throughly, and yes it has bugs, but where do you see 2.1.5 is released? No where!
Look at the relaases tab, where do you see **2.1.5**?
Master is always BETA, same with nextcloud, you don't install that too from master on a production.
And if you won't tell any info then i think this issue can be closed due lack of info.

**Comment by peturbg** [comment]
animallilo there is no **dbprefix*passman_vaults for vaults and *dbprefix*passman_credentials. So when you know that passman is getting problems in update why don't you make warning to appear when normal user update that he can lost all his 20 password or more passwords. This is serious matter. It is like you are married when you are not married.

**Comment by brantje** [comment]
Replace `**dbprefix` with the prefix you used during install. Please use common sense.

**Comment by animalillo** [comment]
You should replace dbprefix with the database prefix your have set while setting up your cloud instance, not passman.

The update process is fully handled by nextcloud core, no way to add a warning there.

And please, mind to answer the questions so we can properly help you track your issue down?

**Comment by peturbg** [comment]
brantje you respond yourself how you are in real life " Well first of all, i'm not being rude. Second, i don't like being called a liar. "
So brantje remember there is no general humankind, everybody is different. So if you use passman beta this don't mean everybody will you use beta software, brantje if you are liar, becouse you confirm yourself you are liar then this is your problem. And no thank you i don't want to see you in real life. brantje i desire you good life. brantje with you communication is over for today. brantje have a nice day.

**Comment by peturbg** [comment]
animallilo comment me step by step. This is seen and read by other peoples too. So animallilo where it should be replaced dbprefix with the database, where what steps. animallilo do you have nextcloud, if yes then maybe you know that you only go to download and install, so if i remember correctly there is no database change... Animalillo you confirm yourself that process is handled by nextcloud but then why in the process with update it delete the database maybe with more 20 password. Animalillo respond yourself what is in real life passman...

**Comment by animalillo** [comment]
He meant that you are using the beta version of passman, not ready for production use, so see have tested it but can't warrantee there is no issues and you should not use it with any critical data as anything can happen.

**Comment by peturbg** [comment]
animalillo mind to answer the questions so we can properly help you in your real life your issue down?

**Comment by peturbg** [comment]
animalillo habals espanyol, porque si leiste bien la beta la utiliza el otro hombre. lee y veras que version utilizo ademas. passman si utiliza nextcloud entonces habria que guardar la base para las actualizaciones.

**Comment by animalillo** [comment]
If you don't provide me with information on your setup and the exact errors and steps to reproduce them, we can't do anything more to help you.

We have provided you with all the information we can with the small amount of information you have provided to us.

So if you want to keep digging into the passman problem and try to recover your passwords please, provide us with the information we need to help you.

Otherwise, this issue will remain closed.

Thank you for your patience, apologies for the inconvenience and any misunderstanding in our conversations.

Wish you best

**Comment by nickvergessen** [comment]
@peturbg Please stick to your report.
Do not high-jack other issues to discuss your problem which was reported here.

Please also stick to english as a language.

And last but not least please keep in mind, that people do their work here voluntarily. Insulting is not really the best option to honor their work.
