### ISSUE TITLE
ATTENTION to all who wants to update to passman from 2.14 to 2.15. You are gonna lost your vault. this is second topic the first topic was illegaly closed by other person bratje brajie or something like that

### ISSUE THREAD

**Issue by peturbg** [nextcloud/passman#403]
Hi guys this is second topic, the first topic was closed by some user bratje or something like that. Take precaution when you update from passman 2.14 to passman 2.15 you are gonna lost all your passowords and maybe never will return, so make copy or don't update. Include this user bratje or moderator or admin bratje or something like that try insult me, damage and etc. when he use beta this don't mean everybody need to use beta software. The case was that nextcloud comment there is new version in github passman 2.15 and no warning that when someone update to 2.15 he will lost his vault. So now no return for passwords. The program passman is good in general but this is serious matter that a program like passman in update delete all your vault. Maybe there is peoples who have more than 40 password so do you imagine you to lost 40 passwords and no return. Thanks guys for the passman but you have to start repspect the other peoples. have a nice day and have nice weekend.

**Comment by brantje** [comment]
Hi there the 'some' brantje.
I'm the owner of passman, so so far for the 'some' brantje.
You have #402 as issue, and waiting for your answer, please next time use the issue template.

**Comment by animalillo** [comment]
Also a note, we tried and have not been able to replicate such behaviour when updating between 2.14 and 2.15, so we need additional info, please keep young be issues when there is already one topic about it, we will reopen it if we find an issue in passman code
