### ISSUE TITLE
Can't export passwords with any browser

### ISSUE THREAD

**Issue by In0cenT** [nextcloud/passman#405]
### Steps to reproduce
1. export credentials
2. wait for file to download
3. still waiting -> no answer

### Expected behaviour
Browser should download a file

### Actual behaviour
Nothing at all

### Configuration
**Operating system**:   
Running NextCloud in a Docker on unraid
**Browser**:      
Chrome and Edge
**Extensions that might cause interference**:   
No extension
**Passman version**:    

**Operating system**:

**Web server:**

**Database:**

**PHP version:**
      
**cloud server:** Nextcloud or ownCloud

**cloud version:** (see admin page or version.php)
  
   
#### Browser log
<details>
<summary>Browser log</summary>
```
JQMIGRATE: Migrate is installed, version 1.4.0
passman.min.js?v=23a942654c1c81209e19c2b84432f398-0:27 Crypto stuff initialized
initEngines @ passman.min.js?v=23a942654c1c81209e19c2b84432f398-0:27
(anonymous) @ passman.min.js?v=23a942654c1c81209e19c2b84432f398-0:27
core.js?v=23a942654c1c81209e19c2b84432f398-0:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ core.js?v=23a942654c1c81209e19c2b84432f398-0:4
ajax @ core.js?v=23a942654c1c81209e19c2b84432f398-0:4
load @ passman.min.js?v=23a942654c1c81209e19c2b84432f398-0:33
(anonymous) @ passman.min.js?v=23a942654c1c81209e19c2b84432f398-0:33
j @ core.js?v=23a942654c1c81209e19c2b84432f398-0:2
fireWith @ core.js?v=23a942654c1c81209e19c2b84432f398-0:2
ready @ core.js?v=23a942654c1c81209e19c2b84432f398-0:2
I @ core.js?v=23a942654c1c81209e19c2b84432f398-0:2
```
</details>   

Is this the browser logs you're asking for? I just opend up the dev console in chrome and copied everything from the console tab...

#### Cloud log
<details>
<summary>Cloud log</summary>
```
Error | PHP | Method OC_L10N_String::__toString() must return a string value at /config/www/nextcloud/lib/private/L10N/L10N.php#85 | 2017-11-20T10:56:13+0100
-- | -- | -- | --
Error | PHP | vsprintf(): Too few arguments at /config/www/nextcloud/lib/private/legacy/l10n/string.php#72 | 2017-11-20T10:56:13+0100
```
</details>

Thanks for your work!

**Comment by brantje** [comment]
Hi!
Thanks for reporting, we have similliar issues like yours: #264 or #371
