### ISSUE TITLE
Textarea for Freehand Notes

### ISSUE THREAD

**Issue by compumatter** [nextcloud/passman#406]
## Feature request

**User type**: Logged-in or public user
Public user (ie chrome, firefox extensions)
**User level**: Beginners, intermediate or advanced
Advanced
### Description

I am a former lastpass user.  Having migrated to passman (which I like and am grateful for) I do not find a feature I have relied upon with this and with clipperz in years past.  This is the presence of a freehand textarea to write in notes specific to this url. 
### Benefit / value

 I feel this is of value and especially for users importing data from lastpass and others who will simply loose this data upon import
### Risk / caveats

None that I am aware of
### Sponsorship

**Are you a developer willing to implement this feature?**: yes/no
No
**Can you sponsor the development of this feature or do you know someone who can?**: yes/no
I would contribute 50.00 towards its implementation
![lasptass](https://user-images.githubusercontent.com/121611/33145032-df6d1bd4-cf73-11e7-9038-f342bce22bb6.png)

**Comment by brantje** [comment]
Hi there!
Glad to have you join our community!
Such feature exist already, when adding / editing the credential, you have the notes field on the right.

![image](https://user-images.githubusercontent.com/2758767/33145126-93858dea-cfbf-11e7-94da-f78db2cbfbe8.png)

**Comment by compumatter** [comment]
Hello,

I have mistakenly added this request in the Passman main github.  It is actually a need for the Passman-webextension.

I see what you are talking about.

Thank you.  I will re-enter this request in the right forum.

Jay
