### ISSUE TITLE
Uploaded files on mobile devices

### ISSUE THREAD

**Issue by ShwoIIi** [nextcloud/passman#408]
When uploaded a grid or some other image for login on a website in passman,
it can not be opened or downloaded from a android device.
Tried it with different versions of android and devices.

On Firefox i click on the attached file and it starts to download.

On a mobile device the click does not start any action.

**Comment by brantje** [comment]
Yea, we will have the android app for that soon. Passman doesn't work great in a mobile browser (and that's why we will have mobile apps).
