### ISSUE TITLE
Feature Request - Prompt/Warn user Label field is required.

### ISSUE THREAD

**Issue by spwilson2** [nextcloud/passman#410]
## Feature request

**User type**: Logged-in or public user

Logged in

**User level**: Beginners, intermediate or advanced

Beginners

### Description

When creating a new password without filling in the Label field the save icon spins indefinitely without any error indication being given to the user. There should be a popup or fail notice displayed to the user indicating that the Label is required field. 

Implementation Hint: This would probably mean validating the Label field is non-null on the client side.

### Benefit / value

Unless the user realizes that he should look at the mysql logs they will never know that Label is a required field. This would help new users.

### Risk / caveats

Non

### Sponsorship
 
**Are you a developer willing to implement this feature?**: yes/no

no

**Can you sponsor the development of this feature or do you know someone who can?**: yes/no

no

**Comment by binsky08** [comment]
this is already implemented
