### ISSUE TITLE
Error translation in Chinese for 'master_password_remember' label

### ISSUE THREAD

**Issue by CrazyShipOne** [nextcloud/passman#414]
### Steps to reproduce
1.click the passman button on chrome when not logged in

### Expected behaviour
the label(for="master_password_remember") of the checkbox below password input should be '记住主密码'(means remember the main password)

### Actual behaviour
the label is '忘记主密码' which means forget the main password....

Since the problem is relatively simple, I guess there is no need to paste logs here. But if its necessary please notify me and I would like to do it. Thanks.

**Comment by brantje** [comment]
Translations are handled by [Transifex](https://www.transifex.com/nextcloud/nextcloud/passman/).
You can sign up with your Github account and join the Chinese translations team.
