### ISSUE TITLE
"Destruction request" message

### ISSUE THREAD

**Issue by arnauldb** [nextcloud/passman#416]
"I tried to delete my vault and there is a "Destruction request" send, but where is it send to i can't find it back anywhere to confirm the destruction so it is really deleted."

Please, could you tell me where it is sent ?

Thank you.

**Comment by animalillo** [comment]
It goes to the admin, into the passman settings menu

**Comment by arnauldb** [comment]
thank you @animalillo , I finally found it. I join a screenshot in case somebody else can't find where to look...
![selection_001_09_20 27 58](https://user-images.githubusercontent.com/13196747/33798829-2dd6d698-dd20-11e7-989a-6a4dd2905a06.jpg)

**Comment by splitt3r** [comment]
WOW! That browser looks really messy 😆

**Comment by brantje** [comment]
Closing, i think this is solved. @arnauldb if you're still having problems i'll reopen the issue.
