### ISSUE TITLE
PHP Error Method OC_L10N_String

### ISSUE THREAD

**Issue by Bables55** [nextcloud/passman#418]
### Steps to reproduce
1. Open Passman app on Nextcloud site. Not add-on. Nextcloud's app.

### Expected behaviour
Normal use

### Actual behaviour
In rare cases, an error "message flag could not be set" may be displayed. As a result, it switches to Passman's valut selection screen.
Even when it is not displayed, an error is displayed when viewing the log.

### Configuration
**Operating system**:   
CentOS 7.3

**Browser**:      
Firefox 57, Vivaldi 1.13.

**Passman version**:    
2.1.4
**Operating system**:
CentOS 7.3
**Web server:**
nginx 1.11.10
**Database:**
MariaDB 5.5.56
**PHP version:**
7.1.12
**cloud server:** Nextcloud or ownCloud
Nextcloud
**cloud version:** (see admin page or version.php)
12.0.4
   
#### Cloud log

<details>
<summary>Cloud log</summary>

```
Method OC_L10N_String::__toString() must return a string value at /MY-NEXTCLOUD/lib/private/L10N/L10N.php#85

vsprintf(): Too few arguments at /MY-NEXTCLOUD/lib/private/legacy/l10n/string.php#72

```
</details>

**Comment by brantje** [comment]
This issue has been reported multiple times. We are aware of it. #306 or #209
