### ISSUE TITLE
cannot creat a vault if aiRobofrom is installed

### ISSUE THREAD

**Issue by 3PO** [nextcloud/passman#424]
Hi,

i installed the password app in nextcloud.
When i click on the icon, i get a message, that i should creat a new vault.
So far, so good, but when i clich on the green button, nothing happens...

![2017-12-20_120642](https://user-images.githubusercontent.com/945108/34204608-9313ae5c-e57f-11e7-844e-0f58d0874819.png)

I foud out, this happens if "aiRobofrom" is installed. 
When i dissable the aiRobofrom addon, it works.

![2017-12-20_122511](https://user-images.githubusercontent.com/945108/34204953-e5aa72da-e580-11e7-9bd8-66825a60fcad.png)

I've tested it with Firefox, Chrome and Opera and the behavior is allways the same.

Maybe you can implant a check if aiRoboform is installed?

**Comment by brantje** [comment]
This is a problem with aiRobofrom, i suggest you take it to developers so they can fix the bug.

**Comment by brantje** [comment]
Oh btw, passman can fill forms for you. No need to have Roboform.
If you use custom fields with the id/name of the input you want to fill it works like roboform

**Comment by 3PO** [comment]
I know, that passman can fill forms, but only in FF or Chrome, Roboform work in all Browsers and in other Apps too. ;)

BTW:
Creating a vault is not the only problem, passman deosnt generally not work, if Roboform is activatet.

I know, it isnt a problem of passman, its only for information, if other useres have the same prblem. ;)

**Comment by brantje** [comment]
Roboform is interfering with the workings of passman, not much i can do, it's up to them to fix it.
But i doubt they will do that. 

"And all other browsers" -> Which browser(s) are you missing? Safari extension is planned, but requires a lot of work to be done.

**Comment by 3PO** [comment]
> [...]  Which browser(s) are you missing? ...

Opera, for example. :)

Maybe in future it is possible to extend the nextcloud client for Win10 to use passman also in other Apps, so than i can Roboform kick away.  ;)

**Comment by brantje** [comment]
I doubt they gonna include passman in the Windows 10 app.
Never got contacted by the Nextcloud Windows team for this.
Afaik, you can install the extension in Opera (if it supports webextensions).
Or you can [try](https://www.techsupportalert.com/content/how-install-chrome-extensions-opera.htm) this.

**Comment by 3PO** [comment]
>[...] Or you can try this. ...

"this" is working, THX

But i cannot login into nextcloud:

![2017-12-20_164328](https://user-images.githubusercontent.com/945108/34215451-a828c400-e5a5-11e7-8e7a-bc0397afe887.png)

BTW:

The button "Nächstes" should be "Weiter".

**Comment by brantje** [comment]
Translations are handles by Transifex. If you would like to change it you can join the nextcloud team.
Don't know if you can access the developer tools in Opera, if that's the case, could you open them and try again? Rrrors will be logged to the console.
