### ISSUE TITLE
Passwords fields in overlay forms not (always) recognized

### ISSUE THREAD

**Issue by jzielke84** [nextcloud/passman#427]
### Steps to reproduce
1. Save password for an overlay login (e.g Paypal.com or cerberusapp.com)
2. Access Site Again
3. Fields not automatically filled, when selecting account from passman search, fields get filled but no update or this url is asked either.

### Expected behaviour
Password fields should be recognized in overlay login forms

### Actual behaviour
They don't (duh!)

### Configuration
**Operating system**:   
Max OS X 10.10.5
**Browser**:      
 Chome 63.0.3239.108
**Extensions that might cause interference**:   
non because it doesn't work with or without any
**Passman version**:    
2.0.4 in chrome and 2.1.4 on server
**Operating system**:
Again? Max OS X 10.10.5 Or the server nextcloud runs on: Ubuntu 16.04
**Web server:**
Apache2
**Database:**
holy MariaDB
**PHP version:**
php 7.1 fpm
**cloud server:** Nextcloud or ownCloud
Nextcloud
**cloud version:** (see admin page or version.php)
12.0.4
   
#### Browser log
<details>
<summary>Browser log</summary>
Login field:

<paper-dialog id="dialog" entry-animation="fade-in-animation" exit-animation="fade-out-animation" class="card style-scope login-card x-scope paper-dialog-0" role="dialog" tabindex="-1" style="outline: none; z-index: 103;">
    
    
			<paper-dialog-scrollable id="scrollable" class="scroll style-scope login-card x-scope paper-dialog-scrollable-0 no-padding scrolled-to-bottom">
    

    <div id="scrollable" class="scrollable style-scope paper-dialog-scrollable" style="box-sizing: border-box; max-height: 776px; max-width: 355px;">
      

				<form id="loginForm" method="post" class="style-scope login-card">
					<paper-input autofocus="" always-float-label="" label="Nombre de usuario" type="text" id="username" name="username" class="style-scope login-card x-scope paper-input-0" tabindex="0" aria-disabled="false">
    

    <paper-input-container class="style-scope paper-input x-scope paper-input-container-0">
    

    
      <div class="floated-label-placeholder style-scope paper-input-container" aria-hidden="true">&nbsp;</div>
    <template is="dom-if" class="style-scope paper-input-container"></template>

    <div class="input-content label-is-floating style-scope paper-input-container">
      

      <div class="label-and-input-container style-scope paper-input-container" id="labelAndInputContainer" style="position: static;">
        <label aria-hidden="true" for="input" class="style-scope paper-input" id="paper-input-label-1">Nombre de usuario</label><input is="iron-input" id="input" class="style-scope paper-input" autocomplete="off" placeholder="" autocapitalize="none" autocorrect="off" aria-describedby="" aria-labelledby="paper-input-label-1" name="username" type="text" autofocus="" tabindex="0" style="background-image: url(&quot;chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/icons/icon.svg&quot;); background-repeat: no-repeat; background-position: right 3px center !important;"><template is="dom-if" class="style-scope paper-input"></template><template is="dom-if" class="style-scope paper-input"></template>
      </div>

      
    </div>

    <div class="underline style-scope paper-input-container">
      <div class="unfocused-line style-scope paper-input-container"></div>
      <div class="focused-line style-scope paper-input-container"></div>
    </div>

    <div class="add-on-content style-scope paper-input-container">
      
    </div>
  </paper-input-container>
  </paper-input>
					<paper-input always-float-label="" label="Contraseña" type="password" id="password" name="password" class="style-scope login-card x-scope paper-input-0" tabindex="0" aria-disabled="false">
    

    <paper-input-container class="style-scope paper-input x-scope paper-input-container-0">
    

    
      <div class="floated-label-placeholder style-scope paper-input-container" aria-hidden="true">&nbsp;</div>
    <template is="dom-if" class="style-scope paper-input-container"></template>

    <div class="input-content label-is-floating style-scope paper-input-container">
      

      <div class="label-and-input-container style-scope paper-input-container" id="labelAndInputContainer" style="position: static;">
        <label aria-hidden="true" for="input" class="style-scope paper-input" id="paper-input-label-2">Contraseña</label><input is="iron-input" id="input" class="style-scope paper-input" autocomplete="off" placeholder="" autocapitalize="none" autocorrect="off" aria-describedby="" aria-labelledby="paper-input-label-2" name="password" type="password" tabindex="0" style="background-image: url(&quot;chrome-extension://hlpjhlifkgmoibhollggngbbhbejecph/icons/icon.svg&quot;); background-repeat: no-repeat; background-position: right 3px center !important;"><template is="dom-if" class="style-scope paper-input"></template><template is="dom-if" class="style-scope paper-input"></template>
      </div>

      
    </div>

    <div class="underline style-scope paper-input-container">
      <div class="unfocused-line style-scope paper-input-container"></div>
      <div class="focused-line style-scope paper-input-container"></div>
    </div>

    <div class="add-on-content style-scope paper-input-container">
      
    </div>
  </paper-input-container>
  </paper-input>
				</form>
			
				<div class="error style-scope login-card">
					<div id="error" class="style-scope login-card" style="display: none;"> </div>
				</div>
				<div class="buttonsLayout style-scope login-card">
					<paper-button id="forgot" raised="" class="style-scope login-card x-scope paper-button-0" role="button" tabindex="0" animated="" aria-disabled="false" elevation="1" style="display: none;">¿Ha olvidado su contraseña?</paper-button>
			 		<paper-button id="buy" raised="" class="style-scope login-card x-scope paper-button-0" role="button" tabindex="0" animated="" aria-disabled="false" elevation="1" style="display: none;">Comprar licencia</paper-button>
			 		<paper-button id="login" raised="" class="style-scope login-card x-scope paper-button-0" role="button" tabindex="0" animated="" aria-disabled="false" elevation="1" style="display: block;">Iniciar sesión<div class="fitLayout style-scope login-card"><paper-spinner class="style-scope login-card x-scope paper-spinner-0" aria-hidden="true"><div id="spinnerContainer" class="  style-scope paper-spinner"><div class="spinner-layer layer-1 style-scope paper-spinner"><div class="circle-clipper left style-scope paper-spinner"></div><div class="circle-clipper right style-scope paper-spinner"></div></div><div class="spinner-layer layer-2 style-scope paper-spinner"><div class="circle-clipper left style-scope paper-spinner"></div><div class="circle-clipper right style-scope paper-spinner"></div></div><div class="spinner-layer layer-3 style-scope paper-spinner"><div class="circle-clipper left style-scope paper-spinner"></div><div class="circle-clipper right style-scope paper-spinner"></div></div><div class="spinner-layer layer-4 style-scope paper-spinner"><div class="circle-clipper left style-scope paper-spinner"></div><div class="circle-clipper right style-scope paper-spinner"></div></div></div></paper-spinner></div></paper-button>
				</div>
			
    </div>
  </paper-dialog-scrollable>
		
  </paper-dialog>
</details>   

#### Cloud log

<details>
<summary>Cloud log</summary>
Not needed because the cloud works fine. It's just the browser extension
</details>

**Comment by brantje** [comment]
Hi there,
Thanks for reporting.
Can you move this to https://github.com/nextcloud/passman-webextension ?

**Comment by jzielke84** [comment]
I can't but the project owners can.

**Comment by brantje** [comment]
I can't move issue. Just close this one and open a new one at that repo.

**Comment by jzielke84** [comment]
Ok shall i copy this one over?

**Comment by jzielke84** [comment]
[Moved to passman-webextension](https://github.com/nextcloud/passman-webextension/issues/226)

Please close this one
