### ISSUE TITLE
Share passwordlists between groups

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/passman#428]
The '[teampass](https://github.com/nilsteampassnet/TeamPass)' app is designed to let you share passwords between teams/groups. It would be nice to be able to do this in passman 🥇 

It is also written in PHP, perhaps there's room for collaboration...

Via @waazdakka who can give more details 😄

**Comment by brantje** [comment]
Hi Jos,
Unfortunately this is not possible, for more info see [here](https://github.com/nextcloud/passman/issues/396#issuecomment-342636560).

**Comment by jospoortvliet** [comment]
too bad but I understand... doesn't work with E2E, yea, good point.
