### ISSUE TITLE
header information error

### ISSUE THREAD

**Issue by mind22** [nextcloud/passman#438]
## Bug report

Passman app continuously generates error in log file.

### Steps to reproduce
1. No steps here just installed app.

### Configuration
**Passman version**:    2.1.4

**Operating system**:  Ubuntu 16.04 LTS

**Web server:**. Nginx 1.12.2

**Database:** MariaDB

**PHP version:**. 7.1
      
**cloud server:** Nextcloud 

**cloud version:** 13RC3
  
 
#### Cloud log

<details>
<summary>Cloud log</summary>

Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/apps/passman/personal.php:1) at /var/www/nextcloud/lib/private/AppFramework/Http/Output.php#69

</details>

No others errors appear in log file.

**Comment by OS3DrNick** [comment]
What is the error?

**Comment by mind22** [comment]
I did include the error message in section cloud log (Cloud log). The passman app is as i can say normally working. But it continuously shows this in the log file when the app is activated.

**Comment by OS3DrNick** [comment]
Sorry. Was too quick with response :)

**Comment by mesamoo** [comment]
Same error on 
nextcloud 13.0.0
Apache 2.4.29
php 7.2.1

**Comment by NikTh** [comment]
I'm not a PHP Guru, but modifying `personal.php` seems fixing this error.

**Before**
```
<!-- Placeholder file -->
```
![personal php_before](https://user-images.githubusercontent.com/5518249/36458194-44559114-16b6-11e8-86a5-cbe9fdce1170.jpg)

**After**
```
<?php
?>
```
![personal php_after](https://user-images.githubusercontent.com/5518249/36458208-50d0425e-16b6-11e8-8f4e-ff06d60ebfdf.jpg)

**Comment by madmath03** [comment]
I do not know for sure how the `personal.php`  file is used, maybe to store information about the personal settings like email and notifications?

@NikTh with your fix, after removing the troublesome, did you encounter any issues using the app? If not, maybe you could send a PR?

**Comment by NikTh** [comment]
@madmath03 
I don't know if 1 day of testing is enough. I'm using Passman from yesterday, personal.php is updated, also Chrome Extension and Firefox Addon. No issues. So far so Good.

PR submitted.

**Comment by NikTh** [comment]
Better is without closing the tags, as @animalillo pointed out. 
Just 
`<?php` 
is enough.

**Comment by mind22** [comment]
E.g. comparing with nextcloud/apps/pushnotifications personal.php. It has just the opening <?php like NikTh says.
