### ISSUE TITLE
Question: can Passman capture pre-filled forms' data?

### ISSUE THREAD

**Issue by aymercury** [nextcloud/passman#439]
Can Passman capture pre-filled forms' data? 

I use that "Save all entered data" feature in Lastpass regularly. Now I am looking for a password manager to migrate to, tried Passman and did not see that feature. 

Is there a way to do this in Passman? Can it detect all available fields and capture entered data? Or can it detect fields, then I would enter data in Passman, save there and populate the form? 

Thanks!

**Comment by violoncelloch** [comment]
Are you looking for something like this?
https://github.com/nextcloud/passman-webextension/wiki/Fill-any-input-with-custom-fields

**Comment by aymercury** [comment]
Not sure if this is the same.

Let say I want to create a new user account on www.example3.com. They have a long form to fill. 
1. I use my profile in Passman to fill name/address fields.
2. I manually fill out the rest of form fields. (security questions like fav. color, mother's maiden name etc - **all random values**, not real maiden name. Some other fields like car model on a car forum, for example).
3. I then ask Passman to **detect all form fields** as custom fields, capture all entered data and save it.  

Is it possible to get all this data saved in Passman?  Maybe, if I change the order of steps, the direction of data flow?  Will this work:
1. I ask Passman to detect all form fields, it creates many custom fields.
2. I fill them out in Passman (either from pre-saved profile or manually), save it.
3. I use Passman to fill all form fields on the web site.

**Comment by brantje** [comment]
I think this issue fits better in the webextension repo, because, i think you're talking about that one.
Link: https://github.com/nextcloud/passman-webextension/issues
@aymercury do you want me to move it or do you open a new one yourself?
