### ISSUE TITLE
Firefox extension does not work

### ISSUE THREAD

**Issue by wneiluj** [nextcloud/passman#445]
Hello,

Good initiative, unfortunately Firefox extension does not work at all for me.
EXCEPT when I create a new account on a website using password generator.
All other existing website stored in the vault are not found by the extension.

### Steps to reproduce
1. unlock passman extension with the vault's password
2. open a webpage with a login form (account's credentials are stored inside the vault)
3. 

### Expected behaviour
passman should find the credentials for this webpage, as they are stored inside the vault

### Actual behaviour
authentication fields are not filled, passman extension says 'no information found for this website'
the issue occurs for all websites for which I have a user account

### Configuration
**Operating system**:   Win 7 Pro 64 bits

**Browser**:  Firefox 58.0.2

**Extensions that might cause interference**:   ?
I use : HTTPS everywhere, Privacy badger, Enhancer for youtube, Qwant
problem occurs even if I deactivate all extensions

**Passman version**:    2.0.4 (extension)

**Operating system**: Nextcloud webserver OS? if yes, my service provider says: linux centos 7

**Web server:**
https://ncloud.zaclys.com/

**Database:** mysql

**PHP version:** ? I use a hosted service, do not have this info
      
**cloud server:** Nextcloud

**cloud version:** (see admin page or version.php) ?
  should be the most recent
   
#### Browser log
<details>
<summary>Found 0 logins for this site
inject.js:315:21</summary>

</details>   

#### Cloud log
??
I use a hosted service, do not have this info

**Comment by aa23** [comment]
Double-Check this setting: `Passman Extension Icon > Settings > Show Advanced Options > 'Ignore path for site matching'`

It'll match sites better if it's **enabled**. I can't remember how it's set by default.
I've been using the extension with Firefox before and after Quantum and I haven't really had issues with it.

**Comment by wneiluj** [comment]
Thank you for your help. In fact this setting was already enabled. I have changed other settings with not success.

I do not understand why it does not work. Same issue with another computer. Could it have something to do with nextclould's server configuration?

**Comment by wneiluj** [comment]
The most surprising thing is that, again, the extension works fine with a website for which the extension was used to create a new account but only within the same session! if I lock the extension and re-authenticate myself, that website is no longer found!

**Comment by aa23** [comment]
Is this enabled or disabled for you? I have it disabled and I'm 95% sure it's disabled-by-default. `Ignore subdomain for site matching`
Just making sure since some sites use an assortment of subdomains. I'm clearly grasping at straws :P .

Also, when you do unlock your account on the extension, and click the 'hamburger' at the top left, it lists the total number of credentials you have in your vault, right? I had one problem once where I would unlock it, but it'd say there were 0 sites in my vault (I self-host and had to make a change to Nextcloud).

Have you tried deleting your 'Account' in the extension, then re-adding it? Obviously not a good solution, but maybe something is screwed up locally.

You may be able to rule out an issue with your hosting provider if you test the Chrome extension as well.

If none of that helps, you can enable `Debug Mode` in the extension, hit `F12`, click `console`, and go to a login page and see or report back what the extension says.
For example, this is what it tells me when it autofills the password for Amazon.com:
```
(form ignored (https://www.amazon.com/ap/signin) -- no password fields.)
findForm.js:182:17
(form ignored (https://www.amazon.com/ap/get) -- no password fields.)
findForm.js:182:17
(form (https://www.amazon.com/ap/signin) ignored -- no username field found)
findForm.js:182:17
(form ignored (https://www.amazon.com/ap/signin) -- no password fields.)
findForm.js:182:17
(form ignored (https://www.amazon.com/ap/get) -- no password fields.)
findForm.js:182:17
Found 1 logins for this site
inject.js:315:21
(form (https://www.amazon.com/ap/signin) ignored -- no username field found)
findForm.js:182:17
(form ignored (https://www.amazon.com/ap/signin) -- no password fields.)
findForm.js:182:17
(form ignored (https://www.amazon.com/ap/get) -- no password fields.)
findForm.js:182:17
```

**Comment by wneiluj** [comment]
OK, thank you again.

Answers:

> Is this enabled or disabled for you?

it's enabled

> Also, when you do unlock your account on the extension, and click the 'hamburger' at the top left, it lists the total number of credentials you have in your vault, right? 

no, the list is empty, which means that when I authenticate myself on any website, the extension considers it as a news entry to be added.

> Have you tried deleting your 'Account' in the extension, then re-adding it? Obviously not a good solution, but maybe something is screwed up locally.
this is a solution indeed! but only temporary...

Example of logs :
(form ignored (https://secure.lemonde.fr/sfuser/register) -- no password fields.)
findForm.js:182:17
(form ignored (https://secure.lemonde.fr/sfuser/password/lost) -- no password fields.)
findForm.js:182:17
Found 0 logins for this site
inject.js:315:21

I will also make tests with Chrome, that's a good point

**Comment by wneiluj** [comment]
Correction: "click the 'hamburger' at the top left, it lists the total number of credentials you have in your vault" yes, it does shows the total number, even if no matching is found

and for some reason, now that I have re-added my account in the extension, all websites are found EXCEPT the 'new' one that I had added in the previous session!

**Comment by aa23** [comment]
> and for some reason, now that I have re-added my account in the extension, all websites are found EXCEPT the 'new' one that I had added in the previous session!

Hey, that's good news right? I hope it continues to work even after you lock it and unlock it.
If it does continue working correctly, that must mean it wasn't able to synchronize any new accounts you had added from the extension to your vault in Nextcloud.

**Comment by wneiluj** [comment]
you're right. For now, it still works fine even after lock and unlock. Hope it lasts! thanks

**Comment by brantje** [comment]
Hi there,
We are aware of this issue in the webextension repo (https://github.com/nextcloud/passman-webextension)
As we have a separate repo for it, i'm closing this one to prevent clutter.
