### ISSUE TITLE
Https required... but its actually working with HTTPS

### ISSUE THREAD

**Issue by Gutz-Pilz** [nextcloud/passman#446]
hello there,

i'd love to use nextcloud-passwords
when i try to access it say's "Https required"

i'm using nextcloud-apache along with jwilder/letsencrypt docker-compose file.
(if needed i can provide)

![bildschirmfoto 2018-02-24 um 17 10 20](https://user-images.githubusercontent.com/3322071/36632331-c799e24c-1985-11e8-8780-5113bd7e5040.png)

**Comment by SkyBehind** [comment]
Same, but I think this is the passwords app, not passman. I could be wrong, but I think they're two different apps

**Comment by brantje** [comment]
That is the passwords app, not passman. Closing due wrong repo.
