### ISSUE TITLE
Error Message: Cannot modify header information in nextcloud.log

### ISSUE THREAD

**Issue by egeu5** [nextcloud/passman#449]
### Steps to reproduce
1. Install NC 13
2. Install Passmann

### Expected behaviour
-

### Actual behaviour
A error message "Cannot modify header information" is appearing every time if a user is refreshing the passwords on the Firefox-App. Furthermore it is also appering if the app automatically refreshing the passwords.

### Configuration
**Operating system**:   Arch Linux

**Browser**:      58.0.2

**Extensions that might cause interference**:   uBlock Origin, Ghostery

**Passman version**:    Passman Extension 2.0.4, Nextcloud App 2.1.4

**Operating system**: Arch Linux

**Web server:** Apache

**Database:** Mariadb

**PHP version:** 7.2.2
      
**cloud server:** Nextcloud

**cloud version:** 13.0.0
  
#### Cloud log
<details>
<summary>Cloud log</summary>

```
"Cannot modify header information - headers already sent by (output started at /usr/share/webapps/nextcloud/apps/passman/personal.php:1) at /usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Output.php#69"
```
</details>

**Comment by aa23** [comment]
Not that will help you any, but I have a very similar setup, except I'm running NC v12. I'm not able to reproduce the error.

**Comment by egeu5** [comment]
On NC 12 it was working pritty well and did not have the error :-)

**Comment by gradinaruvasile** [comment]
Replace the contents of 

/var/www/nextcloud/apps/passman/personal.php
with this:

`<?php
/* Placeholder file */
`

This fixed the issue for me.

**Comment by egeu5** [comment]
If I did this, Nextcloud crashes with an "Internal-Server Error" when logging in into the web interface if I switched to Settings-Tab.
 ``
ParseError: syntax error, unexpected '<', expecting end of file

    /usr/share/webapps/nextcloud/lib/private/Settings/Manager.php - line 497: OC_App getForms('personal')
    /usr/share/webapps/nextcloud/settings/Controller/CommonSettingsTrait.php - line 89: OC\Settings\Manager->getPersonalSections()
    /usr/share/webapps/nextcloud/settings/Controller/CommonSettingsTrait.php - line 42: OC\Settings\Controller\PersonalSettingsController->formatPersonalSections('personal', 'personal-info')
    /usr/share/webapps/nextcloud/settings/Controller/CommonSettingsTrait.php - line 120: OC\Settings\Controller\PersonalSettingsController->getNavigationParameters('personal', 'personal-info')
    /usr/share/webapps/nextcloud/settings/Controller/PersonalSettingsController.php - line 61: OC\Settings\Controller\PersonalSettingsController->getIndexResponse('personal', 'personal-info')
    [internal function] OC\Settings\Controller\PersonalSettingsController->index('personal-info')
    /usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 161: call_user_func_array(Array, Array)
    /usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 91: OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Settings\Controller\PersonalSettingsController), 'index')
    /usr/share/webapps/nextcloud/lib/private/AppFramework/App.php - line 115: OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Settings\Controller\PersonalSettingsController), 'index')
    /usr/share/webapps/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OC\\Settings\\Con...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /usr/share/webapps/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /usr/share/webapps/nextcloud/lib/base.php - line 998: OC\Route\Router->match('/settings/user')
    /usr/share/webapps/nextcloud/index.php - line 37: OC handleRequest()
    {main}
``

**Comment by gradinaruvasile** [comment]
It was supposed to have a newline...
```
<?php
/* Placeholder file */
 ```

**Comment by worldworm** [comment]
Can report the same bug.

@gradinaruvasile your fix helped. Thanks!


---

Browser: 58.0.2
Extensions that might cause interference: uBlock Origin
Passman version: Passman Extension 2.0.4
Operating system: Ubuntu 17.10
Web server: Apache
Database: MYSQL
PHP version: 7.2.2
cloud server: Nextcloud
cloud version: 13.0.0

**Comment by egeu5** [comment]
This seems to be working for me to :-)
@worldworm has updated the personal.php file with this input so I will close.
Thank you all for you're quick response and this awesome plugin!

**Comment by madmath03** [comment]
Is there any plan in the near future to make a new release including this fix ?

I found out that this errors not only generates a lot of logs but also impacts other apps to load properly... I love passman and really do not want to disable it.
