### ISSUE TITLE
Change triple dot ellipsis

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/passman#450]
https://github.com/nextcloud/passman/blob/780003407d502a012db9eeab6aacd7b2ba86c353/templates/public_share.php#L80

Reported at Transifex. See https://www.transifex.com/nextcloud/nextcloud/translate/#de/$/117120274?issue=yes

**Comment by AK04** [comment]
What should I change it to?

**Comment by rakekniven** [comment]
Change the three single dots to ellipsis character.
See https://en.wikipedia.org/wiki/Ellipsis

**Comment by brantje** [comment]
Fixed
