### ISSUE TITLE
bug: passman involuntarily exposes passwords in WebUI

### ISSUE THREAD

**Issue by knixx** [nextcloud/passman#452]
![image](https://user-images.githubusercontent.com/14290269/37455298-08babbdc-283d-11e8-94aa-1cc6bd722d02.png)
It takes the latest password and displays it.

**Comment by brantje** [comment]
Hi!
You can change the type to password to hide it.
Click on `Text` a dropdown will appear, then select password.

**Comment by knixx** [comment]
NO! Absolutely no! - This is a security related bug that need to be fixed. Period.

**Comment by brantje** [comment]
Your situation:
![image](https://user-images.githubusercontent.com/2758767/37455613-bf87dcc8-283d-11e8-9899-598ac9e1ec9c.png)
This will save it as 'text type' but still encrypted client side.

![image](https://user-images.githubusercontent.com/2758767/37455653-dac46074-283d-11e8-870e-06f5b5be268e.png)
This will save the value as type `password` so passman knows it's a password and therefore it needs to thread it as one. 

Passman needs to know what type it is, because i personally use text fields more.

**Comment by brantje** [comment]
Closing, as this is not a bug. Just a little misunderstanding.

**Comment by knixx** [comment]
You need to read first. **It exposes the vault's password!!!!!!**

**Comment by knixx** [comment]
You need to read first. It exposes the vault's password!!!!!!

**Comment by knixx** [comment]
You need to read first. It exposes the vault's password!!!!!!

**Comment by brantje** [comment]
So where are the steps to reproduce? The issue is invalid anyway's you didn't honor the issue template.
We use that template with a reason.

**Comment by brantje** [comment]
Until you fill in that template and post it here, or create an new issue with it. This issue stays closes.

**Comment by knixx** [comment]
One again, Sir, you have a mayjor security issue in your app. And your app is all about security! Please listen and check your software.

**Comment by brantje** [comment]
Once again without steps to reproduce we can't do anything

**Comment by knixx** [comment]
1. Create vault with a new password
2. Create an item in the vault
3. Logout, close the vault
4. Login again, click on "user field"
5. You will find the vault's password, like my screenshot shows

**Comment by brantje** [comment]
What branch are you on? What Browser are you using?

All questions i now have to ask because you refuse to fill in the template.

**Comment by knixx** [comment]
Firefox, Chrome always latest (Linux, Mac, Win), stable nextcloud 13 on Ubuntu 16.04, all patched and current, etc... But all irrelevant - It is a security bug in YOUR app.

**Comment by brantje** [comment]
We are working on this in our free time. We love our own app and security is a big aspect of it offcourse.
But creating an issue with just a screenshot, with no further information doesn't help to reproduce the problem.

I've tried it on the demo, but don't get too see "user field". 
Could you make a gif that displays it? That would help us alot!
Thanks in advance.

**Comment by animalillo** [comment]
Just a tiny question, do you have the vault password saved into your browser's password manager? Maybe that's the issue, as the browser may be filling the field with your password automatically.

**Comment by knixx** [comment]
Damn, yes the browser's password manager. But then again... Why does the password ends up in a form field of the app anyway? The field should have another name than the password field at the login page of the app.

**Comment by animalillo** [comment]
because your browser detects the field is suited to hold a password, so it autofills your precious password.

**Comment by animalillo** [comment]
we once tried to work around this very same problem while developing the app and found no way to fix this little issue, we decided to not invest any more time on this.

Firefox and Chrome ignore the autofill="disabled" property and we didn't come up with a good solution for this problem.

If you find some, please share it or make a pretty pull request and we will gladly implement or merge it.
