### ISSUE TITLE
Any plans for a Microsoft Edge extension?

### ISSUE THREAD

**Issue by imthenachoman** [nextcloud/passman#459]
I know the iOS app is on the to-do list. Any plans for a Microsoft Edge extension?

**Comment by brantje** [comment]
Supporting Chrome and firefox is already a lot of work. I doubt that Microsoft can keep it self to the Webextension standards, but if they to it would be possible. If the extension need 'hacks' then its a no-go.

**Comment by brantje** [comment]
Also can this issue fits better here: https://github.com/nextcloud/passman-webextension/issues

**Comment by imthenachoman** [comment]
I completely understand. I figured I'd check.

But I'm being forced to move back to Chrome for other reasons so all is well.

Thank you!
