### ISSUE TITLE
flash of red bar and untranslated strings

### ISSUE THREAD

**Issue by SimJoSt** [nextcloud/passman#464]
### Steps to reproduce
1. Install the Passman app into Nextcloud
2. Open the Passman app

### Expected behaviour
The app loads normally.

### Actual behaviour
While loading (especially with an empty cache) a red bar appears at the top.
Also, some variables/untranslated strings appear throughout the page, including `{{ 'http.warning' | translate }}`.
All of this disappears when the page is fully loaded.

### Configuration
**Operating system**:   Windows 10 x64

**Browser**:      Chrome

**Extensions that might cause interference**:   

**Passman version**:    2.1.4

**Operating system**:

**Web server:**

**Database:**

**PHP version:**
      
**cloud server:** Nextcloud

**cloud version:** 13.0.1
  
   
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>   

#### Cloud log

<details>
<summary>Cloud log</summary>

```
Insert your cloud log here
```
</details>

## Feature request

**User type**: Logged-in or public user

**User level**: Beginners, intermediate or advanced

### Sponsorship

 
**Are you a developer willing to implement this feature?**: yes/no

**Can you sponsor the development of this feature or do you know someone who can?**: yes/no

**Comment by newhinton** [comment]
This is fixed with 2.2.0, this bar is now normally hidden
