### ISSUE TITLE
Feature Request: Folders and Duplicate Credentials

### ISSUE THREAD

**Issue by bstin** [nextcloud/passman#465]
## Feature request

**User type**: Logged-in or public user

**User level**: Beginners, intermediate or advanced

### Description
Two Request:

1.  Folders

Please add "folders" to organize credentials in vaults. Using this with a team with dozens of credentials, its a long list in each vault. Would be easier if we could organize credentials into logical groups. 

2.  Copy / Duplicate

Also beneficial would be the ability to copy / duplicate an existing credential into a new one. The point of this is when you are doing something like deploying 50 of the same machines and each is basically identical with minor differences in username/password/IP address/etc. 

### Benefit / value

These enhancements would make your product much more suitable for organizations and groups where managing a large number of credentials is necessary. 

### Sponsorship

**Are you a developer willing to implement this feature?**: No

**Can you sponsor the development of this feature or do you know someone who can?**: Yes - I made a small donation recently to this project as a way to help continue development: 

Pay Pal Confirmation Number: XXXXXXXX960667040

**Comment by newhinton** [comment]
See  #492. Please open up a new Request for the duplicate/copy function

**Comment by newhinton** [comment]
Scratch that, i open a new request ;)
