### ISSUE TITLE
better not to share with groups?

### ISSUE THREAD

**Issue by animalillo** [nextcloud/passman#47]
I think sharing with groups is too complicated and problematic, since we keep everything client side as main passman philosophy. The main issue comes when a user is added or removed from a group, mostly on the adding users to group process, specially if the given user has never used passman before because it wouldn't have vaults with sharing keys which would be a mess.
Too sleepy to express myself correctly, hope the point is clear.

**Comment by phsc** [comment]
For me, it would be great to have the feature to share passwords with groups. But it is not a showstopper, if you decide, not to implement it.

Really appreciate your hard work on passman (quite impressive commit history the last days/weeks)! 👍

**Comment by animalillo** [comment]
We will think about it, but there are many situations that should be taken into account to make this feature something useful and that isn't leading to confusion or reports of bugs that aren't bugs.

The most troublesome situation is new people comming into the group that weren't there once the share was made. Since all the cryptographic workload is handled on the client side, the server has no way of letting the user access a shared credential.

For now, we will be implementing only user sharing, maybe a feature to load all users on a group to the share list, maybe, @brantje what do you think? Would this be good enough for you, @phsc ?

**Comment by brantje** [comment]
Imo, sharing with groups is even more complex then sharing with users. 
Sharing has been on the wishlist of passman from the beginning, so sharing with users (and a public share link if wished) is already a great progress.
See sharing with users / links, as a public test, if it's much used, we can look to adding group sharing.

**Comment by phsc** [comment]
This is ok for me. It is no showblocker. Even without this feature, passman is a great app!
