### ISSUE TITLE
Cannot modify header information - headers already sent by (output started at /var/www/html/nextcloud/apps/passman/personal.php:1) at /var/www/html/nextcloud/lib/private/AppFramework/Http/Output.php#69

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/passman#474]
Steps to reproduce

none. Nextcloud error log will log this error permanentely since upgrade to Nextcloud 13.0.2 from Nextcloud 12.0.6

Expected behaviour

No errors related to passman

Actual behaviour

Nextcloud error log will log this error permanentely since upgrade to Nextcloud 13.0.2 from Nextcloud 12.0.6

Server configuration detail

Operating system: Linux 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64

Webserver: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.1.14 (apache2handler)

Database: mysql 5.5.56

PHP version: 7.1.14
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, apcu, bcmath, bz2, calendar, ctype, curl, dba, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, ldap, exif, mcrypt, mysqli, PDO, pdo_mysql, pdo_sqlite, Phar, posix, redis, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, wddx, xmlreader, xmlwriter, xsl, memcached, zip, Zend OPcache

Nextcloud version: 13.0.2 - 13.0.2.1

Updated from an older Nextcloud/ownCloud or fresh install:
Updated from Nextcloud 12.0.6

Where did you install Nextcloud from: Automatic WEB-Upgrade by Nextcloud

Enabled:

activity: 2.6.1
admin_notifications: 1.0.1
announcementcenter: 3.2.1
apporder: 0.4.1
bookmarks: 0.11.0
bruteforcesettings: 1.0.3
calendar: 1.6.1
circles: 0.13.6
comments: 1.3.0
contacts: 2.1.3
dav: 1.4.6
deck: 0.3.1
federatedfilesharing: 1.3.1
federation: 1.3.0
files: 1.8.0
files_external: 1.4.1
files_pdfviewer: 1.2.1
files_rightclick: 0.8.4
files_sharing: 1.5.0
files_texteditor: 2.5.1
files_trashbin: 1.3.0
files_versions: 1.6.0
files_videoplayer: 1.2.0
firstrunwizard: 2.2.1
gallery: 18.0.0
impersonate: 1.0.4
issuetemplate: 0.3.0
logreader: 2.0.0
lookup_server_connector: 1.1.0
mindmaps: 0.1.0
mood: 0.3.3
music: 0.5.6
nextcloud_announcements: 1.2.0
notes: 2.3.2
notifications: 2.1.2
oauth2: 1.1.0
ownbackup: 17.5.0
passman: 2.1.4
password_policy: 1.3.0
polls: 0.8.1
provisioning_api: 1.3.0
quicknotes: 0.1.3
quota_warning: 1.2.0
rainloop: 5.0.6
ransomware_protection: 1.1.0
serverinfo: 1.3.0
sharebymail: 1.3.0
sharepoint: 1.1.0
socialsharing_diaspora: 1.0.2
socialsharing_email: 1.0.3
socialsharing_facebook: 1.0.2
socialsharing_googleplus: 1.0.2
socialsharing_twitter: 1.0.2
spreed: 3.2.0
survey_client: 1.1.0
systemtags: 1.3.0
tasks: 0.9.6
theming: 1.4.1
twofactor_backupcodes: 1.2.3
twofactor_totp: 1.4.1
updatenotification: 1.3.0
workflowengine: 1.3.0
Disabled:
admin_audit
appvncsafe
audioplayer
encryption
external
files_antivirus
lsd
ojsxc
richdocuments
spreedme
user_external
user_ldap
weather
{
"memcache.local": "\OC\Memcache\APCu",
"filelocking.enabled": true,
"redis": {
"host": "REMOVED SENSITIVE VALUE",
"port": 0,
"dbindex": 0,
"timeout": 1.5
},
"instanceid": "REMOVED SENSITIVE VALUE",
"passwordsalt": "REMOVED SENSITIVE VALUE",
"secret": "REMOVED SENSITIVE VALUE",
"trusted_domains": [
"localhost",
"xxxxx
"xxxxxx",
"xxxxxx"
],
"datadirectory": "REMOVED SENSITIVE VALUE",
"overwrite.cli.url": "https://xxxxxx",
"dbtype": "mysql",
"version": "13.0.2.1",
"dbname": "REMOVED SENSITIVE VALUE",
"dbhost": "REMOVED SENSITIVE VALUE",
"dbport": "",
"dbtableprefix": "oc_",
"mysql.utf8mb4": true,
"dbuser": "REMOVED SENSITIVE VALUE",
"dbpassword": "REMOVED SENSITIVE VALUE",
"installed": true,
"maintenance": false,
"theme": "",
"loglevel": 1,
"updater.release.channel": "production",
"auth.bruteforce.protection.enabled": true,
"check_for_working_htaccess": true,
"data-fingerprint": "xxxxxxxx",
"mail_from_address": "REMOVED SENSITIVE VALUE",
"mail_smtpmode": "smtp",
"mail_smtpauthtype": "LOGIN",
"mail_domain": "REMOVED SENSITIVE VALUE",
"mail_smtpsecure": "tls",
"mail_smtpauth": 1,
"mail_smtpname": "REMOVED SENSITIVE VALUE",
"mail_smtppassword": "REMOVED SENSITIVE VALUE",
"mail_smtphost": "REMOVED SENSITIVE VALUE",
"mail_smtpport": "xxxx",
"session_lifetime": xxxx,
"session_keepalive": false,
"logtimezone": "xxxx",
"logfile": "/media/nextcloud.log",
"log_rotate_size": 104857600,
"knowledgebaseenabled": false,
"updater.secret": "REMOVED SENSITIVE VALUE"
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

<details><summary>LDAP configuration (delete this part if not used)</summary>

With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM oc_appconfig WHERE appid = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Dragon/52.15.25.665 Chrome/52.0.2743.82 Safari/537.36

**Operating system:** 

Windows 10

**Comment by aa23** [comment]
See #449 .
I just installed Nextcloud 13, had the same error as you, and created the file mentioned in that issue. I no longer get this error in the logs.

**Comment by Githopp192** [comment]
Thx a lot aa23! This fixed it for me,2.

<?php
/* Placeholder file */

in "personal.php"

Greetings & Best Regards
Mike

**Comment by NESC1US** [comment]
i have the same problem, I don't think this should have been closed, as the reason for this error message is a useless html comment on line 1 of the nextcloud/apps/passman/personal.php

suggested solution:
perhaps change the html comment to php comment by prefixing it wth #?

**Comment by quenenni** [comment]
I'm in the process to update all our Nc12 -> Nc13 and noticed the same error in my logs.

I quite agree with @NESC1US 

The problem comes from the comment line in the file personal.php.

I removed the line and no more errors.
I tried also @NESC1US idea and added a # before the line and it worked too.

**Comment by NESC1US** [comment]
I realised, shortly after posting my previozs comment here, that in order to resolve this issue, both line deletion nor commenting the line out would not really work, php block encapsulation is needed in order for the file not output anything prior the headers desemination and by doing so, blocking them, replace content of personal.php with something like the bellow:
<?php
// here, its fixed for good
?>

**Comment by quenenni** [comment]
@NESC1US I think you forgot to write the last sentence (after "below:".)

Removing the line fixes the lod msgs, but I don't know if it breaks the passman.
My first test seems to show that passman is still working, but not using it myself, I don't know if that can break existing vaults that are upgraded to v13.

I think too that this thread should be re-opened.

**Comment by NESC1US** [comment]
when this was done a new issue started to appear in the logs, I believe that it was always there, but never executed due to the original issue:

Level | App | Message | Time
-- | -- | -- | --
Error | PHP | Method OC\L10N\L10NString::__toString() must return a string value at /bla/bla/bla/nextcloud/lib/private/L10N/L10N.php#88 | 2018-06-07T13:51:41+0200
Error | PHP | vsprintf(): Too few arguments at /bla/bla/bla/nextcloud/lib/private/L10N/L10NString.php#79 | 2018-06-07T13:51:41+0200

**Comment by quenenni** [comment]
Ok.. Thanks for the infos.

Well, today, my tests showed something different :(

I put back the original personal.php file and now (with apache and nginx), the "modify headers" error only appears when navigating through the settings pages, nowhere else  (I tested all the pages all several times).
Is it due to the fact that's a new php session compared to yesterday where it was the same session as before the upgrade?

And when I go to the passman app page, I have the same 2 errors as you. 
So it seems these errors (__tostring & vsprintf) aren't related to the first one.

I still have to upgrade all the Nc on 1 server, I'll check if I can see the same pattern.

**Comment by quenenni** [comment]
Very strange, but indeed, this error only appears when navigating the settings pages now.
The only difference from the server where I discover the problem was an Apache server Vs here a Nginx server.

But still, the error is still present when navigating the settings pages.
And if I change the content of personal.php file to #449 (adding <?php ?>), I have an internal server error when going to the setting pages (not elsewhere):
```
{"reqId":"zP8x5IN31koF1jF366Wf","level":3,"time":"2018-06-08T14:56:32+02:00","remoteAddr":"aaa.aaa.aaa.aaa","user":"xxxx","app":"index","method":"GET","url":"\/settings\/user","message":"Exception: {\"Exception\":\"ParseError\",\"Message\":\"syntax error, unexpected '<', expecting end of file\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/lib\\\/private\\\/Settings\\\/Manager.php(497): OC_App::getForms('personal')\\n#1 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(93): OC\\\\Settings\\\\Manager->getPersonalSections()\\n#2 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(46): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->formatPersonalSections('personal', 'personal-info')\\n#3 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(125): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->getNavigationParameters('personal', 'personal-info')\\n#4 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/settings\\\/Controller\\\/PersonalSettingsController.php(57): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->getIndexResponse('personal', 'personal-info')\\n#5 [internal function]: OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->index('personal-info')\\n#6 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#7 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\PersonalSettingsController), 'index')\\n#8 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\PersonalSettingsController), 'index')\\n#9 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Settings\\\\\\\\Con...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#12 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/lib\\\/base.php(999): OC\\\\Route\\\\Router->match('\\\/settings\\\/user')\\n#13 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/index.php(37): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/home\\\/nextcloud\\\/instances\\\/hale\\\/apps\\\/passman\\\/personal.php\",\"Line\":2}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:52.0) Gecko\/20100101 Firefox\/52.0","version":"13.0.2.1"}
{"reqId":"RsIzxMtWqmQjFAJx1LAC","level":3,"time":"2018-06-08T14:56:33+02:00","remoteAddr":"aaa.aaa.aaa.aaa","user":"xxxx","app":"index","method":"GET","url":"\/settings\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"The requested uri(\\\/settings\\\/ocs\\\/v2.php\\\/apps\\\/notifications\\\/api\\\/v2\\\/notifications) cannot be processed by the script '\\\/apps\\\/notifications\\\/')\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/lib\\\/base.php(951): OC\\\\AppFramework\\\\Http\\\\Request->getRawPathInfo()\\n#1 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/index.php(37): OC::handleRequest()\\n#2 {main}\",\"File\":\"\\\/home\\\/nextcloud\\\/instances\\\/hale\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Request.php\",\"Line\":733}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:52.0) Gecko\/20100101 Firefox\/52.0","version":"13.0.2.1"}
{"reqId":"RsIzxMtWqmQjFAJx1LAC","level":3,"time":"2018-06-08T14:56:33+02:00","remoteAddr":"aaa.aaa.aaa.aaa","user":"xxxx","app":"no app in context","method":"GET","url":"\/settings\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"theming.Theming.getLogo\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/lib\\\/private\\\/Route\\\/Router.php(337): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('theming.Theming...', Array, 1)\\n#1 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/lib\\\/private\\\/Route\\\/CachingRouter.php(60): OC\\\\Route\\\\Router->generate('theming.Theming...', Array, false)\\n#2 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/lib\\\/private\\\/URLGenerator.php(80): OC\\\\Route\\\\CachingRouter->generate('theming.Theming...', Array)\\n#3 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/apps\\\/theming\\\/lib\\\/ThemingDefaults.php(190): OC\\\\URLGenerator->linkToRoute('theming.Theming...')\\n#4 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/lib\\\/public\\\/Defaults.php(187): OCA\\\\Theming\\\\ThemingDefaults->getLogo(true)\\n#5 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/core\\\/templates\\\/layout.guest.php(34): OCP\\\\Defaults->getLogo()\\n#6 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/lib\\\/private\\\/Template\\\/Base.php(176): include('\\\/home\\\/nextcloud...')\\n#7 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/lib\\\/private\\\/Template\\\/Base.php(151): OC\\\\Template\\\\Base->load('\\\/home\\\/nextcloud...', NULL)\\n#8 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/lib\\\/private\\\/legacy\\\/template.php(204): OC\\\\Template\\\\Base->fetchPage(NULL)\\n#9 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/lib\\\/private\\\/legacy\\\/template.php(229): OC_Template->fetchPage()\\n#10 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/lib\\\/private\\\/Template\\\/Base.php(132): OC_Template->fetchPage()\\n#11 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/lib\\\/private\\\/legacy\\\/template.php(351): OC\\\\Template\\\\Base->printPage()\\n#12 \\\/home\\\/nextcloud\\\/instances\\\/hale\\\/index.php(65): OC_Template::printExceptionErrorPage(Object(Exception))\\n#13 {main}\",\"File\":\"\\\/home\\\/nextcloud\\\/instances\\\/hale\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":130}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:52.0) Gecko\/20100101 Firefox\/52.0","version":"13.0.2.1"}
```

**Comment by quenenni** [comment]
OMFSelf...

I just realized that #449 not only added the tag <?php ?>, but also changed the comment line 
```
from
<!-- Placeholder file -->
to
/* Placeholder file */
```
And because I didn't change that part, I had the internal server error. Silly me.

Now, no more error.
Sorry about the noise.
