### ISSUE TITLE
Multiple Password in Toolbar, No Selection in Login/Password Field

### ISSUE THREAD

**Issue by wjwieland** [nextcloud/passman#477]
### Steps to reproduce
1. Similar entries in DB. For example: https://me.myserver.org/nextcloud/login.php and https://me.meserver.org/blog/
2.  Open either link
3.  The passman icon in the toolbar will display entries for both sites, but there will be now icons in the username or password fields from which to choose a password.  
4.  One must log in manually.

### Expected behaviour
A. Preferable - DB should look at more than just the domain name so that if there are two logins on the same site with different paths the correct password should be entered.

B. Regardless of whether or not more than one password is available or not, the login and password fields should contain the icon and a list of the potential entries.

### Actual behaviour
Please see steps to reproduce.

### Configuration
**Operating system**:   
Linux - Ubuntu 17.10.1 (server)
Any - Client
**Browser**:      
Chromium, Google Chrome
**Extensions that might cause interference**:   
Unknown
**Passman version**:    
2.1.4
**Operating system**:
Linux - Ubuntu 17.10.1
**Web server:**
Apache2
**Database:**
MySQL
**PHP version:**
7.1.15      
**cloud server:** Nextcloud or ownCloud
Nextcloud
**cloud version:** (see admin page or version.php)
  13.02
   
#### Browser log

<summary>No Errors or Warnings</summary>

#### Cloud log
```

```

<details>
<summary>Cloud log</summary>

```
wjw@wjw-server:/opt/data/wjw_nextcloud$ tail -f nextcloud.log
{"reqId":"OAzJ6nblGOi8kYQeRbz3","level":3,"time":"2018-05-12T21:58:59+00:00","remoteAddr":"68.169.241.72","user":"wjw","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/passman\/api\/v2\/language?lang=en","message":"vsprintf(): Too few arguments at \/var\/www\/nextcloud\/lib\/private\/L10N\/L10NString.php#79","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.139 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"OAzJ6nblGOi8kYQeRbz3","level":3,"time":"2018-05-12T21:58:59+00:00","remoteAddr":"68.169.241.72","user":"wjw","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/apps\/passman\/api\/v2\/language?lang=en","message":"Method OC\\L10N\\L10NString::__toString() must return a string value at \/var\/www\/nextcloud\/lib\/private\/L10N\/L10N.php#88","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.139 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"3e3WwuZF50184bX6a4uP","level":3,"time":"2018-05-12T22:36:51+00:00","remoteAddr":"68.169.241.72","user":"wjw","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/settings\/user","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/nextcloud\/apps\/passman\/personal.php:1) at \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Output.php#69","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.139 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"3e3WwuZF50184bX6a4uP","level":3,"time":"2018-05-12T22:36:51+00:00","remoteAddr":"68.169.241.72","user":"wjw","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/settings\/user","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/nextcloud\/apps\/passman\/personal.php:1) at \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Output.php#69","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.139 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"3e3WwuZF50184bX6a4uP","level":3,"time":"2018-05-12T22:36:51+00:00","remoteAddr":"68.169.241.72","user":"wjw","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/settings\/user","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/nextcloud\/apps\/passman\/personal.php:1) at \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Output.php#69","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.139 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"3e3WwuZF50184bX6a4uP","level":3,"time":"2018-05-12T22:36:51+00:00","remoteAddr":"68.169.241.72","user":"wjw","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/settings\/user","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/nextcloud\/apps\/passman\/personal.php:1) at \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Output.php#69","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.139 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"dCPgdNc9iGj6tAbgpGCv","level":3,"time":"2018-05-12T22:37:00+00:00","remoteAddr":"68.169.241.72","user":"wjw","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/settings\/admin","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/nextcloud\/apps\/passman\/personal.php:1) at \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Output.php#69","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.139 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"dCPgdNc9iGj6tAbgpGCv","level":3,"time":"2018-05-12T22:37:00+00:00","remoteAddr":"68.169.241.72","user":"wjw","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/settings\/admin","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/nextcloud\/apps\/passman\/personal.php:1) at \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Output.php#69","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.139 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"dCPgdNc9iGj6tAbgpGCv","level":3,"time":"2018-05-12T22:37:00+00:00","remoteAddr":"68.169.241.72","user":"wjw","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/settings\/admin","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/nextcloud\/apps\/passman\/personal.php:1) at \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Output.php#69","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.139 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"dCPgdNc9iGj6tAbgpGCv","level":3,"time":"2018-05-12T22:37:00+00:00","remoteAddr":"68.169.241.72","user":"wjw","app":"PHP","method":"GET","url":"\/nextcloud\/index.php\/settings\/admin","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/nextcloud\/apps\/passman\/personal.php:1) at \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Output.php#69","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/66.0.3359.139 Safari\/537.36","version":"13.0.2.1"
```
![capture](https://user-images.githubusercontent.com/5116738/39962219-e8512ea4-560d-11e8-99ab-c9a08830d123.JPG)

</details>

**Comment by violoncelloch** [comment]
I think you're describing the webextension? So move the issue to the corresponding repo (or create a new one there)...

There are settings in the extension for wether it should only compare the domain or the subdomain or even the path (under advanced settings)

The missing passman icons are an other issue... could you activate the debug mode (in advanced settings of the extension) and show us, what your browser console shows when you open the login pages where it is not working for you

**Comment by wjwieland** [comment]
My mistake.  I apologize. I did not realize the web extension was a separate project from the passman app.
I will attempt to migrate the applicable portion of this to that project.
That said, I do not see the settings in the extension that you mentioned. (version 2.1.1)

Regarding the missing icons, here is what I did. I hope it is what you were asking for, informative and helpful. Please let me know if not:

1. Turned off 'Disable javascript debugger' in Nextcloud->Settings->Additional Setting->Passman
2. Loaded a blank page in a new tab on chromium
3. Loaded inspect page on the blank page
4. loaded https://wjwieland.dvrdns.org/blog/wp-login.php
4a. loaded https://wjwieland.dvrdns.org/nextcloud/
5. saved the console log from the first, as there were no real differences that I could see.
6. attached it here

Thank you

The screen shot from my original report is still applicable.  The icons for the web extension do not show in the case where there are two possible choices.
[wjwieland.dvrdns.org-1526236212978.log](https://github.com/nextcloud/passman/files/1998778/wjwieland.dvrdns.org-1526236212978.log)

**Comment by violoncelloch** [comment]
thank you for moving the issue to nextcloud/passman-webextension#256
will continue discussion there
