### ISSUE TITLE
Can't upload a file

### ISSUE THREAD

**Issue by kokoparkletal** [nextcloud/passman#478]
## Bug report
I'm trying to upload a file to any password to mess arround with issue #264, the file upload but when I click save never end.
EDIT: After a few hours, randomly one credential save the file (and issue #264 fix not working with that file)
Same error trying to delete the file.
EDIT2: The credential that I was using to test just disapear after reenter to passman.

### Steps to reproduce
1. Go to de vault.
2. Edit a password.
3. Add file.

### Expected behaviour
Save file 

### Actual behaviour
Infinite time to save

### Configuration
**Operating system**:   
Windows 10
**Browser**:      
FireFox 60.0.1
Chrome 66.0.3359.181
**Extensions that might cause interference**:   
ublock(?)
**Passman version**:    
2.1.5
**Operating system**:
Debian 8
**Web server:**
Apache+nginx proxy
**Database:**
mysql  Ver 14.14 Distrib 5.5.60, for debian-linux-gnu (x86_64) using readline 6.3
**PHP version:**
PHP 5.6.33-0+deb8u1 (cli) (built: Jan  5 2018 15:46:26)
**cloud server:** Nextcloud or ownCloud
Nextcloud 12.0.5
**cloud version:**
Nextcloud 12.0.5
   
#### Browser log
<details>
<summary>Browser log</summary>
<input type=​"password" ng-model=​"storedCredential.password_repeat" class=​"ng-pristine ng-untouched ng-valid ng-not-empty">​
angular.min.js?v=22bd762a800570e247ad8b76d8b8b7d9-3:103 PATCH https://SERVER/nextcloud/index.php/apps/passman/api/v2/credentials/3B4D64F8-BF84-4FC7-BC00-8F66882C2FF0 500 (Internal Server Error)
</details>

**Comment by ckanibal** [comment]
I experienced the same problem when I tried to upload a file to a new credential entry, until I noticed that you have a supply a valid label in the first tab.

Can you check the log file of your Nextcloud installation? It might show you what is wrong.

**Comment by binsky08** [comment]
seems to work with the current version
