### ISSUE TITLE
Personal settings usage ?

### ISSUE THREAD

**Issue by Oliv4945** [nextcloud/passman#481]
Hi,

Following [this issue](https://github.com/nextcloud/server/issues/9763#issuecomment-395121122) I am wondering the aim of registering a personal settings page.
As the [personal.php](https://github.com/nextcloud/passman/blob/master/personal.php) page is empty, I tried to disable personal page registration in [appinfo/app.php](https://github.com/nextcloud/passman/blob/6767322a22bae9549b439fac40bbdbd2a2df8fee/appinfo/app.php#L24) and it corrects my error : why this empty page exists without proper content ?

Furthermore it created issues linked to #443

**Comment by ashgoodman** [comment]
Any update on whether this will be fixed?

It seems to be just an issue with the empty settings page. Would having some text on that page without ny actual settings resolve this?

If so, perhaps a basic user guide could live in settings?

**Comment by mainmachine** [comment]
I just ran into this issue today after upgrading to NC 16. This has been an issue for awhile now, how do we get this fixed?

**Comment by binsky08** [comment]
fixed with https://github.com/nextcloud/passman/pull/681/commits/6a103d8c8c6b8669e2e12597ffcb9a28d4491def
