### ISSUE TITLE
Push notification cannot be dismissed if password was deleted

### ISSUE THREAD

**Issue by AND51** [nextcloud/passman#488]
### Steps to reproduce
1. Set an expiry date on one of your passwords.
2. Wait till expire date arrives. Press F5 and/or log out and in.
3. Nextcloud will inform you with the bell icon and a red dot that you've got a push notification.
4. Click the text which will lead you to the password.
5. After revising, I decided to delete my password.
6. Wait couple of hours / days and log out and in, maybe even from different computers.
7. Push notification comes again.
8. Clicking "Ignore" or "X" doesn't help.

### Expected behaviour

Once a password is deleted, there must not be a notification for it any more.

### Actual behaviour

- The push notification comes again and again. I haven't figured out yet under which circumstances it comes. It comes every then and now.
- Clicking "X" does only temporaryly dismiss it.
- Clicking "Ignore" does not permananently dismiss it.

### Configuration
**Operating system**:   Ubuntu 16.04.3

**Browser**:      Vivaldi 1.15

**Extensions that might cause interference**:   Passman-Extension from Chrome Store successdully installed and working

**Passman version**:    2.1.4

**Web server:** Apache 2.4.18 (Ubuntu)

**Database:** MariaDB

**PHP version:** 7.0
      
**cloud server:** Nextcloud 

**cloud version:** 13.0.4
  
   
#### Browser log

![image](https://user-images.githubusercontent.com/26226303/43034618-fcbc6f76-8cdf-11e8-8144-a9b17d4c8e1e.png)

![image](https://user-images.githubusercontent.com/26226303/43034621-0652c526-8ce0-11e8-939d-83ea9ad9a0b5.png)

#### Cloud log

<details>
root@red:/srv/www/vhosts/censored/data# grep W1MBTX8AAQEAAEdeOigAAAAn nextcloud.log
{"reqId":"W1MBTX8AAQEAAEdeOigAAAAn","level":3,"time":"2018-07-21T11:47:57+02:00","remoteAddr":"2003:censored","user":"Andre","app":"PHP","method":"DELETE","url":"\/index.php\/apps\/passman\/api\/internal\/notifications\/read\/369","message":"Missing argument 2 for OCA\\Passman\\Db\\CredentialMapper::updateCredential(), called in \/srv\/www\/vhosts\/censored\/htdocs\/apps\/passman\/lib\/Service\/CredentialService.php on line 81 and defined at \/srv\/www\/vhosts\/censored\/htdocs\/apps\/passman\/lib\/Db\/CredentialMapper.php#154","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.183 Safari\/537.36 Vivaldi\/1.96.1147.52","version":"13.0.4.0"}
{"reqId":"W1MBTX8AAQEAAEdeOigAAAAn","level":3,"time":"2018-07-21T11:47:57+02:00","remoteAddr":"2003:censored","user":"Andre","app":"index","method":"DELETE","url":"\/index.php\/apps\/passman\/api\/internal\/notifications\/read\/369","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Cannot use object of type OCA\\\\Passman\\\\Db\\\\Credential as array\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/vhosts\\\/censored\\\/htdocs\\\/apps\\\/passman\\\/lib\\\/Service\\\/CredentialService.php(81): OCA\\\\Passman\\\\Db\\\\CredentialMapper->updateCredential(Object(OCA\\\\Passman\\\\Db\\\\Credential))\\n#1 \\\/srv\\\/www\\\/vhosts\\\/censored\\\/htdocs\\\/apps\\\/passman\\\/controller\\\/internalcontroller.php(69): OCA\\\\Passman\\\\Service\\\\CredentialService->upd(Object(OCA\\\\Passman\\\\Db\\\\Credential))\\n#2 [internal function]: OCA\\\\Passman\\\\Controller\\\\InternalController->read('369')\\n#3 \\\/srv\\\/www\\\/vhosts\\\/censored\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#4 \\\/srv\\\/www\\\/vhosts\\\/censored\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Passman\\\\Controller\\\\InternalController), 'read')\\n#5 \\\/srv\\\/www\\\/vhosts\\\/censored\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Passman\\\\Controller\\\\InternalController), 'read')\\n#6 \\\/srv\\\/www\\\/vhosts\\\/censored\\\/htdocs\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Passman\\\\\\\\Con...', 'read', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/srv\\\/www\\\/vhosts\\\/censored\\\/htdocs\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#9 \\\/srv\\\/www\\\/vhosts\\\/censored\\\/htdocs\\\/lib\\\/base.php(999): OC\\\\Route\\\\Router->match('\\\/apps\\\/passman\\\/a...')\\n#10 \\\/srv\\\/www\\\/vhosts\\\/censored\\\/htdocs\\\/index.php(42): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/srv\\\/www\\\/vhosts\\\/censored\\\/htdocs\\\/apps\\\/passman\\\/lib\\\/Db\\\/CredentialMapper.php\",\"Line\":155}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/65.0.3325.183 Safari\/537.36 Vivaldi\/1.96.1147.52","version":"13.0.4.0"}
</details>

**Comment by bessian** [comment]
I am having the same issue on NC 19.0.6.2. 
Is there any progress ?
