### ISSUE TITLE
curl a CSV or JSON export

### ISSUE THREAD

**Issue by JBoisseau** [nextcloud/passman#495]
This is more a question than a feature request : I'd like to regularly backup vaults. = download an CSV/JSON export with a command line.
The only export method looks to be the gui method, which has a known bug on some browser.

Is there an api I could query ? based on private/public key ?

**Comment by animalillo** [comment]
Well, there actually is an API, the web extension and the Android app make use of it. Even the browser app makes use of itt (standard passman app).

The thing is, the api will give you the data encrypted after the server side enctyption has been undone. But you will still need to decrypt it with the vault key.

This opens you two possibilities, one is keep an encrypted backup, the other is, giving your tool the vault key, keep a plaintext backup.

**Comment by animalillo** [comment]
There is no export api tho

**Comment by JBoisseau** [comment]
Ok thanks.
I managed with the api ans curl.
Thanks for the prompt answer
