### ISSUE TITLE
Demo platform isn't working

### ISSUE THREAD

**Issue by yorick1989** [nextcloud/passman#496]
## Issue report
This issue isn't really code related, but hopefully someone could help me to solve it.

### Steps to reproduce
1. Opened https://demo.passman.cc/
2. Pressed 'create container'.
3. Not working (404) =(

### Expected behaviour
I was hoping for a working demo @ https://demo.passman.cc/ .

### Actual behaviour
After the container should have been created, it redirected me to a 'https://demo.passman.cc:<port>' page; which gave me a 404 error as response.

Hopefully someone can help me with solving this issue.

Thanks!

Grtz,

Yorick

**Comment by joshhazelhurst123** [comment]
I am having the same issue. I am running Windows 8.1 64 bit OS. Toshiba satellite L50D-B
Running firefox quantum 64 bit

**Comment by cClaude** [comment]
@yorick1989 Could you close this issue, to remove some noise. Thk.
