### ISSUE TITLE
Share for xx views

### ISSUE THREAD

**Issue by brantje** [nextcloud/passman#5]
When user shares a password with a user / group / link.
He should be able to set the amount of views before the shared password 'expires'.
This means:
- When shared with a user, the credential is not longer visible
- When shared with a group, the credential is not longer visible
- When shared with a link, the credential is not longer available.

**Comment by animalillo** [comment]
i'm saying here the same that i said on the #7, client side performance issues if we want to keep the system secure, and again, it might be nice for shared links

**Comment by brantje** [comment]
Fixed in: dbbe383bf9786c6f05fe2c247cde4e5e37be3ac2
