### ISSUE TITLE
Undefined index: icon at /var/www/nc/apps/passman/lib/Service/EncryptService.php

### ISSUE THREAD

**Issue by joergmschulz** [nextcloud/passman#500]
### Steps to reproduce
1. install passman from Github master
2. try to create new entry
3. entry will not be created. Instead, nc log says 'Undefined index: icon at /var/www/nc/apps/passman/lib/Service/EncryptService.php#336'

### Expected behaviour
Tell us what should happen
new entry should be created

### Actual behaviour
msg displayed that entry has been created
instead, op cit msg in NC log

### Configuration
      
**cloud server:**  nc13.06

this error also pops up when I 
- remove all oc_pass* tables before installing.
- upgrade from previous version of passman with existing entries (can add entries in store version)

**Comment by MikaYuoadas** [comment]
I get the same error, but not on all url.

I get it only on https://www.spidervet.com/ and https://fr.yahoo.com.

The entry can be created, but the favicon fail to save and display a blank error image and then the log are spammed with "Exception: Base href is not an absolute URL" everytime I display the vault page. :(

**Comment by Razican** [comment]
I get this error consistently, my logs are full of it. Are there any news?

**Comment by joergmschulz** [comment]
this should be obsolete now --- can't currently test because I stopped using passman. If the issue persists, feel free to reopen!
