### ISSUE TITLE
Server version 13 or lower is required.

### ISSUE THREAD

**Issue by Tomasu** [nextcloud/passman#514]
## Bug report

Unable to enable Passman extension in nextcloud14

### Steps to reproduce
1. Update to nextcloud 14
2. ??
3. get "Server version 13 or lower is required." error on apps page (proffit?)

### Expected behaviour
Tell us what should happen

Extension should just work.

### Actual behaviour
Tell us what happens instead

Passwords are inaccesible.

### Configuration
**Operating system**:   

**Browser**:      

**Extensions that might cause interference**:   

**Passman version**:    

**Operating system**:

**Web server:**

**Database:**

**PHP version:**
      
**cloud server:** Nextcloud or ownCloud

**cloud version:** (see admin page or version.php)
  
   
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>   

#### Cloud log

<details>
<summary>Cloud log</summary>

```
Insert your cloud log here
```
</details>

## Feature request

**User type**: Logged-in or public user

**User level**: Beginners, intermediate or advanced

### Sponsorship

 
**Are you a developer willing to implement this feature?**: yes/no

**Can you sponsor the development of this feature or do you know someone who can?**: yes/no

**Comment by egeu5** [comment]
#491

**Comment by newhinton** [comment]
see egeu5's comment, closed
