### ISSUE TITLE
No vaults found (not documented to fix)

### ISSUE THREAD

**Issue by AquaL1te** [nextcloud/passman#538]
### Steps to reproduce
1. Install Passman
2. Create keystore with KeepassX
3. Open Passman in Nextcloud; no vaults found

### Expected behaviour
A file browser to open your Keepass database. Or at least some documentation about this, does it expect a well-known directory somewhere with the keystores? This is not documented as far as I can find on the following pages below. Please provide these instructions since "Import from various password managers" is listed as a feature.

1. https://apps.nextcloud.com/apps/passman
2. https://github.com/nextcloud/passman#readme

### Actual behaviour
Can only create a new vault.

**Comment by animalillo** [comment]
First of all, sorry for the late response.

The import feature works after you create a vault.
First you need to create the vault.
After you have created the vault you can import credentials from certain external password managers and sometimes it requires additional steps from the external password manager.

The import feature is inside the vault settings.

But the main point is that you don't import vaults, you import things inside vaults, so this is not a bug i'm afraid.
