### ISSUE TITLE
Server version 14 or lower is required

### ISSUE THREAD

**Issue by dwrana** [nextcloud/passman#546]
Thanks for reporting issues back to us!

## Bug report

passman is not working any more after update to nextcloud 15, "Server version 14 or lower is required."

### Steps to reproduce
1. always

### Expected behaviour
Should work with current version like other apps

**Comment by Marco-Jacobs** [comment]
I installed the addon on Nextcloud 15.0.0 a few hours ago and it works.
Maybe a problem with the update to 15.

**Comment by vwbusguy** [comment]
What is your passman version?  Passman is working here on NextCloud 15.0.1 with Passman 2.2.1.  Most likely, you just need to update your Passman app.

**Comment by vwbusguy** [comment]
Version 2.2.1 supports versions 14 and 15: https://github.com/nextcloud/passman/blob/2.2.1/appinfo/info.xml#L45

**Comment by vwbusguy** [comment]
Actually, Nextcloud does show which apps are compatible or not before the upgrade.  Either way, that wouldn't be something that the passman app would handle - that has to do with NextCloud's app policy.

**Comment by dwrana** [comment]
It did show that it is not compatible. I did the Nextcloud upgrade at January 1th. I will observe the way it works at the upgrade to Nextcloud 16. Thanks for help!
