### ISSUE TITLE
Undefined index: icon

### ISSUE THREAD

**Issue by copiis** [nextcloud/passman#548]
`Undefined index: icon at  /apps/passman/lib/Service/EncryptService.php#336`

**Comment by animalillo** [comment]
Can you please check if this still happens with passman 2.3.1? If so, could you provide any more information as to how to reproduce this issue?

**Comment by copiis** [comment]
No problem with 2.3.1an Nextcloud 16.0.1

**Comment by battosai30** [comment]
Hi, 

Fresh Nextcloud snap (tried with stable v15) + Passman v2.3.1 and I ge the same error : 

> Undefined index: icon at /var/snap/nextcloud/13453/nextcloud/extra-apps/passman/lib/Service/EncryptService.php#336"

I updated NextCloud to v16/candidate : import is still stuck but I get nothing in logs :s

**Comment by thsnielsen** [comment]
on 18.0.8 with passman 2.3.5 (working)
i still get
Undefined index: icon at /var/www/nextcloud/apps/passman/lib/Service/EncryptService.php#336
