### ISSUE TITLE
Firefox extension: no password check

### ISSUE THREAD

**Issue by Cybernemo** [nextcloud/passman#549]
### Steps to reproduce
1. Install Passman extension to firefox
2. Set Nextcloud instance, user and what you want as password
3. Choose vault
4. Enter password
5. Use Passman

### Expected behaviour
After step 2, the extension should not be able to access the Nextcloud instance as the password is not correct

### Actual behaviour
The extension has access to the Nextcloud instance

### Configuration
Self-hosted Nextcloud on Docker with Traefik reverse proxy.

**Browser**:      
Firefox Quantum

**Extensions that might cause interference**:   
None

**Passman version**:    

**Operating system**:
Ubuntu 18.10, 64bits

**Database:**
MariaDB
  
**cloud server:** 
Nextcloud 15.0.0

**Comment by animalillo** [comment]
This issue belongs to the webextension repo: https://github.com/nextcloud/passman-webextension

Please report it there if this is still happening.
