### ISSUE TITLE
Vault still accessible after logout in browser

### ISSUE THREAD

**Issue by langfingaz** [nextcloud/passman#550]
## Bug report

Logout of vault in Nextcloud app not working completely. User can still access the vault as long as long as he doesn't close the browser-tab.

### Steps to reproduce
1. In your webbrowser log into vault in Nextcloud passman app.
2. Logout [of your vault]
3. Go back in your browser-tab and you are still logged in!

### Expected behaviour
You should not be able to go back and still have access to the vault.

### Client Configuration
**Operating system**:  Windows 10

**Browser**: Firefox desktop

**Passman version**:  2.2.1

### Server Configuration

**Operating system**: Debian

**Web server:** Apache2

**Database:** MariaDB

**PHP version:** 7.2
      
**cloud server:** Nextcloud 15.0.2

**cloud version:** (see admin page or version.php)

**Comment by skewty** [comment]
Not even a comment by a developer!?  This is shocking to me.  I am thinking of looking elsewhere for a solution.  This leads me to believe security is not of great importance to this development team.

**Comment by adsworth** [comment]
I can't duplicate that problem here. If I have a vault open and I logout of Nextcloud and then go back in my browser tab I get the login screen.

I'm using Nextcloud 15.0.2 with Passman  2.2.1 and I tried with Firefox and Chromium in GNOME.

**Comment by langfingaz** [comment]
Thanks for the reply and sorry for my ambiguous issue description. The problem only occurs if you log out of your passman vault.
Most Nextcloud users probably stay logged in into their Nextcloud accounts all the time, so this doesn't help with the issue.

**Comment by adsworth** [comment]
By logout do mean clicking on the home icon or how do you log out?
I get your behaviour when I click on the home icon.

**Comment by langfingaz** [comment]
I used to log out via "Settings > Logout" (on the bottom left of the web interface) and left my browser tab pinned so that I can access the vault easily. I just reproduced this issue on a different device in Arch Linux with the current Firefox version.

[short video demo](https://cloud.privacy1st.de/s/xW7BLYoDLQFDQeR)

**Comment by Matthew-Hine** [comment]
Interesting to see the short video demo. Understandable that some people have stated there concerns over this.

**Comment by newhinton** [comment]
I will try to solve this issue in the next release. We already clear the angular-variables, which store the vault, but it seems the browser keeps references for the history. We now force a page reload on logout, which clears those references and your vault should be gone for good

Thanks for reporting and sorry for the delay!

**Comment by langfingaz** [comment]
You're welcome. Thanks for the update!
