### ISSUE TITLE
Passwort sharing not working and destroys password data

### ISSUE THREAD

**Issue by wolkenfutter-de** [nextcloud/passman#553]
## Bug report

Behaviour before Update to Passman 2.2.1: Password sharing with 1 user was working. Adding another user to the same Password was not working. New password entry needed to be created and shared with both users at the same time to make it work.

Behaviour after Passman 2.2.1: Password sharing with 1 user works only sometimes. Adding another user does not work. Password sharing routine does not quit and password data get destroyed, see https://own.cloudfood.org/index.php/s/Dpw9wjYqmdKP5MZ

### Steps to reproduce
1. Create password entry
2. Share with 1 user
3. Share same password with another user

### Expected behaviour
Working password sharing, adding and removing users without having to create a new password entry

### Actual behaviour
Password sharing routine does not quit and sometimes leaves the password data encrypted (?) and useless.

### Configuration
**Operating system**:   MacOS

**Browser**:      Safari

**Extensions that might cause interference**:   

**Passman version**:    2.2.1

**Operating system**:

**Web server:**

**Database:** MySQL

**PHP version:** 7.2
      
**cloud server:** Nextcloud

**cloud version:** 14.0.4
  

#### Cloud log

<details>
<summary>Cloud log</summary>

see https://own.cloudfood.org/index.php/s/Eb2DnG5mDopB2qq

</details>

**Comment by andrelec1** [comment]
same here

**Comment by misterbridge** [comment]
Same, password is shared and working for the other user, but becomes corrupted in the original vault.

**Comment by animalillo** [comment]
Can you please check if this is still going on with passman 2.3.1? 
If so we will try to priorize this for one of the next releases.
Thank you.

**Comment by andrelec1** [comment]
https://github.com/nextcloud/passman/issues/558 related ...

Issue still present on Passman 2.3.1 ( NextCloud 15.0.5 )

**Comment by almightykiwi** [comment]
Note that this can easily be reproduced in the [demo](https://demo.passman.cc/) (hence a clean install, with Nextcloud 17.0.0 alpha and Passman 2.3.1).

**Comment by mainmachine** [comment]
I just got bit by this today. Not fun and potentially damaging to anyone who's relying on the stability of their password manager. >:(

NC 15.0.10

Passman 2.3.2

**Comment by sundanceowner** [comment]
I also have this issue.  When the password is shared the other user can see it. once any password is unshared, it seems all passwords will not share properly afterwards, at least for that same vault.  Users get the request, but cannot receive any passwords.  If passwords are accepted, you are unable to use the unshare button, but you can use the trashcan button by the user to remove them but they still cannot re-receive this or any other shared password from the same vault.

**Comment by binsky08** [comment]
Couldn't reproduce the issue in Passman 2.4.0. https://github.com/nextcloud/passman/issues/606#issuecomment-1100028551

Please reopen the issue if the bug reproducibly occurs with a >= 2.4.0 installation.
