### ISSUE TITLE
There were problems with the code integrity check.

### ISSUE THREAD

**Issue by daleosm** [nextcloud/passman#554]
### Steps to reproduce
1. On login
2.
3.

### Expected behaviour
Tell us what should happen
Nothing

### Actual behaviour
Tell us what happens instead
Error message

### Configuration
**Operating system**:   
Ubuntu 18.04 SNAP

**Browser**:      

**Extensions that might cause interference**:   

**Passman version**:    
 2.2.1

**Operating system**:

**Web server:**

**Database:**

**PHP version:**
      
**cloud server:** Nextcloud or ownCloud
Nextcloud

**cloud version:** (see admin page or version.php)
Nextcloud 14.0.6
   
#### Cloud log

<details>
<summary>Cloud log</summary>
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- passman
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.

Raw output
==========
Array
(
    [passman] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate is not valid.
                )

        )

)

</details>

**Comment by IwishIcanFLighT** [comment]
Duplicated of #524

**Comment by animalillo** [comment]
It should be fixed now
