### ISSUE TITLE
ignore changes option is never saved

### ISSUE THREAD

**Issue by skewty** [nextcloud/passman#557]
![screenshot from 2019-02-10 09-23-24](https://user-images.githubusercontent.com/9087223/52536951-d99cb600-2d15-11e9-9e70-81dcf0b571cf.png)

It doesn't matter how many times I click on [Ignore site], it still pops up the next time.

Also, I don't see anywhere where that ignore boolean is saved into the vault when I try to edit the entry.

**Comment by skewty** [comment]
![screenshot from 2019-02-10 09-29-06](https://user-images.githubusercontent.com/9087223/52537014-72cbcc80-2d16-11e9-93f9-249ff32eddb0.png)

Also, it doesn't seem to know what website I am on again.  Look..  it is still talking about CoastCapital while I was filing this bug report.

**Comment by skewty** [comment]
Probably related to #550 and #556

**Comment by newhinton** [comment]
this is a bug in the browser extension, not the main app, can you report it there?

**Comment by skewty** [comment]
I see it reported there as # 260.   My bad.  Thanks.  Please close this.
