### ISSUE TITLE
Certificate "4120" has been revoked

### ISSUE THREAD

**Issue by earth08** [nextcloud/passman#560]
After upgrading to  15.0.5 i recieved code-integrity error
after disabling and removing passman,
i cant install passman, 
it gives me this error
Certificate "4120" has been revoked

**Comment by juergen852** [comment]
Same problem here after NC-Update.
Cannot update to passman 2.2.1

**Comment by vwbusguy** [comment]
Seems like it could be related to https://github.com/nextcloud/passman/issues/524

**Comment by Mipronimo** [comment]
Same here ☝️

**Comment by mickey86** [comment]
Same here!

**Comment by svaitsis** [comment]
+ Same here!

**Comment by dl5rcw** [comment]
same here. running 15.0.5, trying passman 2.2.1
Certificate "4120" has been revoked

**Comment by Mipronimo** [comment]
See https://github.com/nextcloud/passman/issues/524#issuecomment-469286167 for the manual installation.

**Comment by svaitsis** [comment]
+ Same here!

**Comment by svaitsis** [comment]
Thanks - worked for me!

**Comment by earth08** [comment]
I also got it to work by manually installing it by command line.
Hope this guys soon solve the problem and provide us a new version.
Thanks guys

**Comment by thatscoteng** [comment]
Why is this issue closed?  Surely a manual install is a workaround, not an actual fix.
