### ISSUE TITLE
passman.cc down, can't download/update the app

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/passman#564]
Hi,

passman.cc is down so users can't download/install the app. Perhaps it might make sense to simply use github as source for the download? Not that github isn't ever down but it probably has a better uptime still ;-)

(I wanted to share passman over social media but couldn't grab a screenshot - those you could also include in the repo so they're nearly always up)

**Comment by brtptrs** [comment]
Still down

**Comment by brtptrs** [comment]
When trying to install Passman from the NC15 front-end it fails with this error:
"Certificate "4120" has been revoked"
Is this due to https://passman.cc/ not being available or is it something different.

**Comment by rkilchmn** [comment]
there is a workaround to download/install via shell

1. wget https://github.com/nextcloud/passman/archive/master.zip
2. unzip master
3. sudo mv passman-master <path to nextcloud dir>/nextcloud/apps/
4. sudo -u <webserver_user> php <path to nextcloud dir>/nextcloud/occ app:enable passman

**Comment by DecaTec** [comment]
Any news on this one?

**Comment by patrickj0607** [comment]
I would be very glad if this could be fixed soon.

Who's the responsible for the website passman.cc, @brantje? @animalillo? Is there some way I can help to get the website running again?

**Comment by ezaquarii** [comment]
@patrickj0607 I don't believe original authors are maintaining this project, I'm afraid. Their last activity is December 2018.

A fork maybe?

**Comment by Loriowar** [comment]
@rkilchmn upload of `master` branch is not a good idea. Preferable to use tags. For example `wget https://github.com/nextcloud/passman/archive/2.2.2.zip`. Otherwise you obtain broken UI due to problems with assets (css and js). For me this works as expected.

**Comment by newhinton** [comment]
The passman.cc site should be back up and running again, updates should be there as well.
