### ISSUE TITLE
Any idea when passman will work on Nextcloud 15?

### ISSUE THREAD

**Issue by SHARK-Hab** [nextcloud/passman#566]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system**:   

**Browser**:      

**Extensions that might cause interference**:   

**Passman version**:    

**Operating system**:

**Web server:**

**Database:**

**PHP version:**
      
**cloud server:** Nextcloud or ownCloud

**cloud version:** (see admin page or version.php)
  
   
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>   

#### Cloud log

<details>
<summary>Cloud log</summary>

```
Insert your cloud log here
```
</details>

## Feature request

**User type**: Logged-in or public user

**User level**: Beginners, intermediate or advanced

### Sponsorship

 
**Are you a developer willing to implement this feature?**: yes/no

**Can you sponsor the development of this feature or do you know someone who can?**: yes/no

**Comment by unix0r** [comment]
The Readme may say, passman is tested with Nextcloud 14, but that does not mean, its not working with nextcloud 15.

Do you have any problems running passman with nc15?
For me, passman 2.2.1 and nextcloud 15.0.6 is running fine.

**Comment by newhinton** [comment]
Passman is running on nextcloud 15 and 16, so im closing this
