### ISSUE TITLE
Credentials created through api shouldn't be encrypted during api call

### ISSUE THREAD

**Issue by marcio199226** [nextcloud/passman#567]
### Configuration
**Operating system**:   

**Browser**:      

**Extensions that might cause interference**:   

**Passman version**:    2.2.1

**Operating system**:

**Web server:**

**Database:**

**PHP version:** 7.x
      
**cloud server:** Nextcloud

**cloud version:** 15.0.4
  
### Description

When we will creating a new credentials through passman api (https://github.com/nextcloud/passman/blob/master/docs/api.md) all data must be encrypted before sending it to /apps/passman/api/v2/credentials endpoint.

The issue I found is that scjl is not available for php so I am not able to encrypt data before send it.
the only option i have for do it is creating credentials through nodejs or browser ....?
Or maybe I missing something? I don't understand why these credentials are not encrypted by back-end if most of nextcloud installation are with ssl.
Is there any workaround ?

**Comment by newhinton** [comment]
This is how it is supposed to be
The server should **never** see unencrypted credentials, regardless of the usage of ssl. So therefore, the client needs to encrypt them before passing them to the api. This is working as intended, and if you find a workaround, you found a serious security issue :)

sjcl is just a library, you should be able to find implementations of the crypto-functions for php. If i remember correctly, you need an aes-256 function to decrypt the vaults
