### ISSUE TITLE
Loading never ends when listing (decryption error when creating)

### ISSUE THREAD

**Issue by rNoz** [nextcloud/passman#568]
A few days ago passman started to fail when listing the credentials after logging in passwords. I don't remember doing anything weird. I have just to recall that I use both passman (nextcloud, in the web) and passman extension for firefox. I usually search using the extension, but I usually (although not always) use the web to update and create credentials. 

I tried using other browser (Chrome) and it doesn't work, but at least it shows 2 errors. In Firefox I get stuck in debugger statements (even disabling breakpoints and resuming).

It is important to mention:
1. Other users can list and use passman properly
2. Although passman doesn't work in the web, I can continue using the firefox extension (listing, searching and updating passwords)
3. I can press the button '+' and create a new credential, but it fails afterwards. More to be explained at the end of this issue.

### Steps to reproduce
1. Login, go to passwords
2. Open vault, write password, decrypt vault
3. Logged inside the vault, spinning (loading) never finishes

### Expected behaviour
Should list the credentials.

### Actual behaviour
It is stuck in the loading spinner.

### Configuration

**Operating system**:  Linux

**Browser**:  Firefox 66.0.1 (But also in Chrome)

**Passman version**:  2.2.1
     
**cloud server:** Nextcloud 14
   
#### Browser log
<details>
<summary>Browser log</summary>

In Firefox it does not show those 2 errors, but in Chrome (without any extension) shows these:
```
passman.min.js?v=e5acae2e-11:27 Crypto stuff initialized
initEngines @ passman.min.js?v=e5acae2e-11:27
core.js?v=e5acae2e-11:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ core.js?v=e5acae2e-11:4
/ncloud/index.php/apps/passman/admin/delete-requests:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
/ncloud/index.php/apps/passman/api/v2/sharing/vault/FC8D28FA-DBBC-4C82-B216-D4D30A58CE02/get:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```
</details>   

## Creating a new credential under this state

As it is said at the beginning, I can "create" new credentials although I cannot list them in the web.

If I press the button '+', the form is shown. After creating the new credential I get two flash messages: a) credential created b) decryption problem/error
#### Browser log
<details>
<summary>Browser log</summary>

From Chrome:
```
/ncloud/index.php/apps/passman/api/v2/sharing/vault/FC8D28FA-DBBC-4C82-B216-D4D30A58CE02/get:1 Failed to load resource: the server responded with a status of 404 (Not Found)
passman.min.js?v=e5acae2e-11:4 TypeError: Cannot read property 'credentials' of undefined
    at m.$scope.refreshListWithSaved (passman.min.js?v=e5acae2e-11:30)
    at m.$scope.saveCredential (passman.min.js?v=e5acae2e-11:30)
    at fn (eval at compile (passman.min.js?v=e5acae2e-11:6), <anonymous>:4:233)
    at b (passman.min.js?v=e5acae2e-11:4)
    at e (passman.min.js?v=e5acae2e-11:7)
    at m.$eval (passman.min.js?v=e5acae2e-11:5)
    at m.$apply (passman.min.js?v=e5acae2e-11:5)
    at HTMLButtonElement.<anonymous> (passman.min.js?v=e5acae2e-11:7)
    at HTMLButtonElement.dispatch (core.js?v=e5acae2e-11:3)
    at HTMLButtonElement.r.handle (core.js?v=e5acae2e-11:3)
(anonymous) @ passman.min.js?v=e5acae2e-11:4
passman.min.js?v=e5acae2e-11:30 TypeError: Cannot read property 'credentials' of undefined
    at m.$scope.updateExistingListWithCredential (passman.min.js?v=e5acae2e-11:30)
    at passman.min.js?v=e5acae2e-11:30
    at passman.min.js?v=e5acae2e-11:4
    at m.$eval (passman.min.js?v=e5acae2e-11:5)
    at m.$digest (passman.min.js?v=e5acae2e-11:5)
    at m.$apply (passman.min.js?v=e5acae2e-11:5)
    at l (passman.min.js?v=e5acae2e-11:4)
    at J (passman.min.js?v=e5acae2e-11:4)
    at XMLHttpRequest.t.onload (passman.min.js?v=e5acae2e-11:4)
/ncloud/index.php/apps/passman/api/v2/sharing/vault/FC8D28FA-DBBC-4C82-B216-D4D30A58CE02/get:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```
</details>

**Comment by animalillo** [comment]
Please, try upgrading to passman 2.3.1 and check if it still happens to you.
Also, the debugging thing is a security feature of passman that you can disable on your nextcloud configuration if you need to use the debugger.

**Comment by binsky08** [comment]
Seems to be already fixed.

Please reopen the issue if the bug reproducibly occurs with a >= 2.4.0 installation.
