### ISSUE TITLE
Support Nextcloud 16 [$5]

### ISSUE THREAD

**Issue by Bubu** [nextcloud/passman#569]
## Bug report

Passman can't be enabled in NC 16, even when forced. The log shows 2 errors for every try enabling the app.

**PHP version:** 7.3.3
      
**cloud server:** Nextcloud 16 beta2
  
  
#### Cloud log

formatted copy doesn't reliably work **sigh**, here's the raw paste:

Summary: 
`Error: Call to undefined method OC\Activity\Manager::registerExtension()`

```
{"reqId":"7vUJ3Sig57VYriqPPher","level":3,"time":"2019-04-03T16:29:51+00:00","remoteAddr":"77.13.28.197","user":"AdminBubu","app":"no app in context","method":"GET","url":"/apps/files","message":{"Exception":"Error","Message":"Call to undefined method OC\\Activity\\Manager::registerExtension()","Code":0,"Trace":[{"file":"/usr/share/webapps/nextcloud/lib/private/legacy/app.php","line":261,"function":"require_once"},{"file":"/usr/share/webapps/nextcloud/lib/private/legacy/app.php","line":154,"function":"requireAppFile","class":"OC_App","type":"::","args":[{"__class__":"OCA\\Passman\\AppInfo\\Application"}]},{"file":"/usr/share/webapps/nextcloud/lib/private/legacy/app.php","line":127,"function":"loadApp","class":"OC_App","type":"::","args":["passman"]},{"file":"/usr/share/webapps/nextcloud/lib/base.php","line":960,"function":"loadApps","class":"OC_App","type":"::","args":[]},{"file":"/usr/share/webapps/nextcloud/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/usr/share/webapps/nextcloud/apps/passman/appinfo/app.php","Line":41,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0","version":"16.0.0.4","id":"5ca4e31d83a93"}
```
```
[no app in context] Error: Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "passman.page.index" as such route does not exist. at <<closure>>

 0. /usr/share/webapps/nextcloud/lib/private/Route/Router.php line 337
    Symfony\Component\Routing\Generator\UrlGenerator->generate("passman.page.index", [], 1)
 1. /usr/share/webapps/nextcloud/lib/private/Route/CachingRouter.php line 60
    OC\Route\Router->generate("passman.page.index", [], false)
 2. /usr/share/webapps/nextcloud/lib/private/URLGenerator.php line 79
    OC\Route\CachingRouter->generate("passman.page.index", [])
 3. /usr/share/webapps/nextcloud/apps/passman/lib/AppInfo/Application.php line 145
    OC\URLGenerator->linkToRoute("passman.page.index")
 4. /usr/share/webapps/nextcloud/lib/private/NavigationManager.php line 115
    OCA\Passman\AppInfo\Application->OCA\Passman\AppInfo\{closure}("*** sensitive parameters replaced ***")
 5. /usr/share/webapps/nextcloud/lib/private/TemplateLayout.php line 81
    OC\NavigationManager->getAll()
 6. /usr/share/webapps/nextcloud/lib/private/legacy/template.php line 183
    OC\TemplateLayout->__construct("user", "files")
 7. /usr/share/webapps/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php line 160
    OC_Template->fetchPage({usedSpacePercen ... ]})
 8. /usr/share/webapps/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 119
    OCP\AppFramework\Http\TemplateResponse->render()
 9. /usr/share/webapps/nextcloud/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Files\Controller\ViewController {}, "index")
10. /usr/share/webapps/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("ViewController", "index", OC\AppFramework\ ... {}, {_route: "files.view.index"})
11. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "files.view.index"})
12. /usr/share/webapps/nextcloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "files.view.index"})
13. /usr/share/webapps/nextcloud/lib/base.php line 975
    OC\Route\Router->match("/apps/files")
14. /usr/share/webapps/nextcloud/index.php line 42
    OC::handleRequest()

GET /apps/files
```

**Comment by Bubu** [comment]
The culprit is https://github.com/nextcloud/passman/blame/master/appinfo/app.php#L41 and https://github.com/nextcloud/server/commit/abd305eff5904a10218d559f596c80c08e2b9c4e#diff-38bf4cf711437accbb8a873e75892f99

Just removing https://github.com/nextcloud/passman/blame/master/appinfo/app.php#L40-L46 let's me enable passman. Not exactly sure about the side effects, but as this seems to be related to the activity app this seems it's not core functionality.

**Comment by OsiMood** [comment]
Actually removing the app.php may not be the solution as the icon won't show up in the main navigation menu, a better solution is to remove this funtion
`$manager->registerExtension(function() {
	return new Activity(
		\OC::$server->getURLGenerator()
	);
});`
and it all should work, also you can edit the info.xml and update the max version to 16
Good luck

**Comment by Bubu** [comment]
@OsiMood I wasn't taking about removing app.php, only lines L40-L46

**Comment by OsiMood** [comment]
@Bubu Sorry, I miss understood.

**Comment by newhinton** [comment]
I will take a look at this for the next release

**Comment by Bubu** [comment]
We are now at v16-RC2

**Comment by Bubu** [comment]
NC16 has been released now.

**Comment by Luticus** [comment]
I'm not a nextcloud app dev or anything and I know basically nothing about the nextcloud api but it *looks* like you may be able to switch line 41 from registerExtension (which is deprecated and removed) to registerConsumer such that it looks like:
$manager->registerConsumer(function() {

Not sure if commenting out that function caused any issues but this *may* help avoid them, provided I guessed right about what replaces registerExtension.

**Comment by Luticus** [comment]
My preliminary testing shows that this seems to work fine on nc16.  @newhinton  is there a good place with current listings of all the nextcloud api calls and their descriptions?  I tried googling that stuff and couldn't find a good comprehensive list.  What else needs to happen for the release to occur?  Anything you guys need help testing?  If I can contribute, I will.

**Comment by Luticus** [comment]
I guessed wrong it seems, I added a note above about it.  Basically when that function is changed, it breaks 2fa and maybe other things as well.  May even break normal logins too, but since I don't log in this way I haven't tested it.  I suspect that it only impacts 2fa.

**Comment by Bubu** [comment]
I submitted my solution(?) as a proper MR now: https://github.com/nextcloud/passman/pull/575
