### ISSUE TITLE
Password in Custom fields cleartext in credential preview

### ISSUE THREAD

**Issue by StoyanDimitrov** [nextcloud/passman#570]
### Steps to reproduce
1. Enter a vault
2. Create new credential
3. Open Custom fields tab
3. In Field label input enter "secret"
4. In Field value input enter "password"
5. From the dropdown next to the value field select "password"
6. Click Save button
7. From the credentials list click on the newly created one

### Expected behaviour
In the right hand side of the screen observe the value of the custom field named "secret" masked  and toggle visibility button being available.

### Actual behaviour
In the right hand side of the screen observe the value of the custom field named "secret" in clear text and no toggle visibility button available.

### Configuration
**Operating system**: Win10

**Browser**:  Mozilla Firefox 68.0a1

**Extensions that might cause interference**:   

**Passman version**:    2.2.2

**Operating system**:

**Web server:** 

**Database:** MySQL

**PHP version:** 7.3
      
**cloud server:** Nextcloud
**cloud version:** 15.0.7

**Comment by animalillo** [comment]
I have tested it on 2.3.1 and seems to be working fine
Feel free to reopen if it still happens to you and try to get us some extra details if so

**Comment by StoyanDimitrov** [comment]
Yes, it still happens on 2.3.1:

![Screenshot_2019-05-21 Passwords - Nextcloud](https://user-images.githubusercontent.com/10962709/58073302-b776c780-7b91-11e9-9e08-4be09b49a652.png)

Can you direct me where to go for the details you need?
