### ISSUE TITLE
Custom fields type password not editable content

### ISSUE THREAD

**Issue by StoyanDimitrov** [nextcloud/passman#571]
### Steps to reproduce
1. Enter a vault
2. Create new credential
3. Open Custom fields tab
4. In Field label input enter "secret"
5. In Field value input enter "password"
6. From the dropdown next to the value field select "password"
7. Click Save button
8. Edit the newly created credential
9. Open the Custom fields tab
10. Click on the value of the custom field labeled "secret"

### Expected behaviour
The contents of the field is available in plain text for edit or buttons are in place to toggle masked/plain text state.

### Actual behaviour
The contents of the field shows ******** and there are no buttons to toggle between plain text and masked value.

### Configuration
**Operating system**: Win10

**Browser**:  Mozilla Firefox 68.0a1

**Extensions that might cause interference**:   

**Passman version**:    2.2.2

**Operating system**:

**Web server:** 

**Database:** MySQL

**PHP version:** 7.3
      
**cloud server:** Nextcloud
**cloud version:** 15.0.7

**Comment by animalillo** [comment]
Is this still happening on 2.3.1?
Please, note you have to click on the password value (masked as ****) so that you can edit it.

**Comment by StoyanDimitrov** [comment]
As it seems it is fixed. Thank you.
