### ISSUE TITLE
Could not Download and Install

### ISSUE THREAD

**Issue by yj0930** [nextcloud/passman#572]
Certificate "4120" has been revoked

**Comment by lzivadinovic** [comment]
Try manual method.
- Fetch .zip/.tar.gz archive and place it in nextcloud_root/apps/passman then enable it via `php occ app:enable passman`

**Comment by yj0930** [comment]
$ curl https://releases.passman.cc/passman_2.2.1.tar.gz -O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4762    0  4762    0     0    153      0 --:--:--  0:00:30 --:--:--  1334

**Comment by MoBe80** [comment]
Ok, this is a Solution for self hosted instances but not for Nextcloud hosted instances. Please fix this soon.

**Comment by snagglewest** [comment]
Unfortunately [passman.cc](https://passman.cc/) has been down the last few days so [https://releases.passman.cc/passman_2.2.1.tar.gz ](https://releases.passman.cc/passman_2.2.1.tar.gz) returns an error...  I fear it might be the last nail in the coffin which is a real shame.  It's the best password  manger I've found.

**Comment by boonkerz** [comment]
yea what should we do

**Comment by anxic** [comment]
You can download the release on Github : https://github.com/nextcloud/passman/releases

curl https://github.com/nextcloud/passman/archive/2.2.1.tar.gz

**Comment by yj0930** [comment]
I'd like to download binary executable, not source code.

**Comment by boonkerz** [comment]
question has passman an future or should i switch to https://apps.nextcloud.com/apps/passwords

**Comment by yj0930** [comment]
@anxic Thanks for your first download link.
@lzivadinovic Thanks for your hint, I can unzip the source code to apps folder, then rename for redundent version number, then enable it.
