### ISSUE TITLE
2.3.0 duplicating URL protocol

### ISSUE THREAD

**Issue by snagglewest** [nextcloud/passman#588]
### Steps to reproduce
1. upgrade to 2.3.0
2. open passman in nextcloud
3.click on a entry and use the link to open a site

### Expected behaviour
The site should open

### Actual behavior
The site opens but the URL protocol is doubled
ie  opens as - https://https://github.com

### Configuration
**Operating system**:   ubuntu 16.04
**Browser**:  Chrome
**Extensions that might cause interference**:   
**Passman version**:    2.3.0
**Operating system**: linux/windows
**Web server:** apache2
**Database:** mysql Version: 10.0.38
**PHP version:** 7.2.18
**cloud version:** Nextcloud 15.0.7
  

Fist let me express my appreciation for updating Passman!  It's really appreaciated!  The upgrade seemed to go without a hitch but... I've run into the issue above.  The quick fix I've found is to just open the record and resave it which eliminates the double protocol in the URL.  Not a show stopper, but inconvenient.  Wish I could provide more, but I'm only a novice, The code is way out side my skill set and might as well be written in mandarin Chinese!

**Comment by snagglewest** [comment]
I spoke too soon. opening the repsord and saving it and then going back into the record seems to work immediately but if you wait a while and try it again it does the double protocol thing again.  there's something strange going on with the save button too.  When clicked it starts the normal spinning wheel of dots, but it never stops and never goes back to the main screen.  Not sure what it's actually doing.  Seems to be sorta saving, but it's not sticking permanently.  Strange...

**Comment by OS3DrNick** [comment]
I can confirm your issue. 

Seems to happen on all credentials, 
it does not happen all the time, and it happens a little wierd:
https://google.fr will become: https://https//google.fr 
where the first one is the notation used in the saved credential.

On the saving part, opening F12/developer console reveals an 500 internal error to me. 
and the save button keeps on spinning.
![500-servererror-credential-update](https://user-images.githubusercontent.com/1030133/58909939-99be6c00-8714-11e9-93a3-6c1b100922d5.PNG)
And also with that, it doesn't happen all the time, it happens sometimes..

Passman Webextention, version 2.3.1
Nextcloud Version, 14.0.12
Raspbian Stretch
php7.0.33 
(Build from git / npm / grunt)

**Comment by OS3DrNick** [comment]
Sorry, made a too quick pull request. 
Seems to fix it in my instance, the regex matching was wrong,
in discussion chosen for this solution.
