### ISSUE TITLE
Passman can't find vault(s) anymore - 2.3.1

### ISSUE THREAD

**Issue by bsherwoodofdaptiv** [nextcloud/passman#594]
### Steps to reproduce
1. Log into NextCloud
2. Open Passman App
3. No vaults listed anymore - only "Create a New Vault"

### Expected behaviour
Vaults should be listed.

### Actual behaviour
No vaults are listed. Vaults have existed for more than a year.

### Configuration
**Operating system**:   
Linux 
**Browser**:      
Any (Firefox 67 - Chrome 74 - Edge 42)

**Extensions that might cause interference**:   
unknown 
**Passman version**:    
2.3.1
**Operating system**:
Windows
**Web server:**
Apache
**Database:**
MYSQL
**PHP version:**
      
**cloud server:** Nextcloud or ownCloud
Nextcloud
**cloud version:** (see admin page or version.php)
  15.0.8
   

</details>

**Comment by Stijn98s** [comment]
a server restart fixed it for me

**Comment by bsherwoodofdaptiv** [comment]
Excellent point. Since I am using a hosted server, the thought of just rebooting it had not occurred.

Needing access to my passwords, I took a harsher action and rolled back my server to the last snapshot I had made. I don't think I had lost too much in doing so.

The problem remains a concern, but since my rollback and your reboot resolved it for our issues, we don't have a reproducible issue. Since "Did you try turning it off and then turning it on again?" seems to be the logical workaround for now, I guess we have a way forward.

My system is incredibly low traffic, as I am its primary user. At best I can only suspect the issue is triggered by:
1. Run time (bleeding of memory) since last update
2. Use of android client to pull latest password file sets up system in odd state (?)
3. Some other software update activitity set machine into odd state that trips issue.

Will have to wait to see if it reoccurs. Issue can be marked as 'not easily reproduced' and closed

**Comment by kruffin** [comment]
I had the same issue when upgrading Passman to 2.3.1; a server restart fixed it for me as well. Scary, but at least all of the data is still there. My guess is the new version isn't attempting to look for existing vaults once the upgrade finishes.
I was using Passman just before the upgrade on the web UI and right after just refreshed the UI and the vaults were gone.

**Comment by newhinton** [comment]
Also browser caching could be a problem, so that the client tries to use the "old" frontent with the "new" backend, which does not work.

But since it has resolved itself, im closing this ;)
