### ISSUE TITLE
Files not passing integrity check

### ISSUE THREAD

**Issue by kirkgroome** [nextcloud/passman#596]
When I get the list of invalid files it returns the text below
Technical information
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.
Results

    passman
        EXCEPTION
            OC\IntegrityCheck\Exceptions\InvalidSignatureException
            Certificate is not valid.

Raw output

Array
(
[passman] => Array
(
[EXCEPTION] => Array
(
[class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
[message] => Certificate is not valid.
)

    )

)

I have uninstalled passman and reinstalled it. How can I fix this problem
Nextcloud version 16.0.1

Thanks
Kirk

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system**:   

**Browser**:      

**Extensions that might cause interference**:   

**Passman version**:    

**Operating system**:

**Web server:**

**Database:**

**PHP version:**
      
**cloud server:** Nextcloud or ownCloud

**cloud version:** (see admin page or version.php)
  
   
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>   

#### Cloud log

<details>
<summary>Cloud log</summary>

```
Insert your cloud log here
```
</details>

## Feature request

**User type**: Logged-in or public user

**User level**: Beginners, intermediate or advanced

### Sponsorship

 
**Are you a developer willing to implement this feature?**: yes/no

**Can you sponsor the development of this feature or do you know someone who can?**: yes/no

**Comment by newhinton** [comment]
Are you using passman 2.3.1?

**Comment by kirkgroome** [comment]
The version I’m using is 2.3.1. I think I started to get this when I upgraded to nextcloud 14.

**Comment by Luticus** [comment]
That's pretty odd, I'm on 2.3.1 and I'm not seeing that issue.  I was before I upgraded but everything has been fine since.  I'm on NC 16 though, so maybe it's specific to older versions of NC?

**Comment by kirkgroome** [comment]
I'm on NC 16.1

**Comment by Luticus** [comment]
Oh ok, you said you'd upgraded to 14 in your prior post, I assumed you were still on that.  Maybe try removing the app completely and reinstall it.  Maybe you've got some old files mixed in?

**Comment by kirkgroome** [comment]
I have tried to uninstall the app and reinstalled it and still have the problem. The problem stated when I did the upgrade to NC14. The problem has stayed with me as I have done many upgrades after that.

**Comment by Luticus** [comment]
When you say you did an uninstall did you just go to the apps thing in nextcloud and remove it there?  I recommend you ssh to you actual server and make sure that the app is being completely removed from /var/www/nextcloud/apps, which is most likely where it'll be.  If it is not, use rm -rf passman from inside that directory.  Then go back to your apps section in nextcloud and install it.  Just don't drop the database and you should be ok.  If that doesn't fix it then it may be someone odd with your nextcloud installation.  If you have a spare server or vm and time to test, try deploying a test nextcloud, installing passman and see if you have the same problem.

**Comment by kirkgroome** [comment]
I just tried removing it by removing the directory and reinstalling it with the same result
Then in doing some research I found issue 524 on the nextcloud site where his was a but. Ithey say to uninstall then do a rescan then reinstall. I did that and all is good.
Thanks for your help

**Comment by newhinton** [comment]
@kirkgroome @Luticus Is this still valid? if not i will close this issue in a few days

**Comment by Luticus** [comment]
It's not for me, and from what @kirkgroome  said in the last post:

> Then in doing some research I found issue 524 on the nextcloud site where his was a but. Ithey say to uninstall then do a rescan then reinstall. I did that and all is good.

I suspect it's good on that end too.  I think it's safe to assume it can be closed.
