### ISSUE TITLE
Share for until a specific date / time 

### ISSUE THREAD

**Issue by brantje** [nextcloud/passman#6]
When user shares a password with a user / group / link.
He should be able to set the date before the shared password 'expires'.
This means:
- When shared with a user, the credential is not longer visible
- When shared with a group, the credential is not longer visible
- When shared with a link, the credential is not longer available.

**Comment by animalillo** [comment]
there is a client performance issue with this feature, i find it a must for the shared links, but i'm not so sure about adding it for standard user and groups as it would requiere changing the shared cypher key once one of the users or groups "times out" and updating all the other users with the new random key

**Comment by brantje** [comment]
Fixed om 5c9aac94955a3b1559146427baaa923118494d4d
