### ISSUE TITLE
Can't import  (csv/json)

### ISSUE THREAD

**Issue by rottenIO** [nextcloud/passman#603]
Steps to reproduce
1. export 16 credentials to JSON 
2. switch account to a clean one
3. import credentials using json filter
4. passman hangs in importing 15/16 credentials

a. Import CSV file
b. select fields
c. start import
d. process stops importing @ n-1 credentials

Expected behaviour
Imported credentials

Actual behaviour
nothing gets imported

**Comment by letopisec3** [comment]
I join the teacher above, does not work.
![изображение](https://user-images.githubusercontent.com/36674563/59892526-0fe3f380-93e2-11e9-95ee-85e348609ddf.png)

**Comment by Oliv4945** [comment]
Hi, it has been solved in #589, you can manually apply the fix or way for next release :)
