### ISSUE TITLE
Not import from csv

### ISSUE THREAD

**Issue by ricain59** [nextcloud/passman#605]
## Bug report
I've recently install nextcloud 16.0.1 + passman 2.3.1 from store nextcloud and unable import any file csv. I've try lastpass.csv and other csv without success.

### Steps to reproduce
1.choose lastpass csv or generic import.
2.choose the file and click on import
3.anything show.

### Expected behaviour
Expected show anything

### Configuration
**Operating system**:   debian 9 (OMV 4.1.22)

**Browser**:      chrome

**Extensions that might cause interference**:   

**Passman version**:    2.3.1
 
**cloud server:** Nextcloud 

**cloud version:16.0.1
  
  I'm newbie and try import.

**Comment by Oliv4945** [comment]
Hi, it has been solved in #589, you can manually apply the fix or way for next release :)

**Comment by ricain59** [comment]
Thank you for reply and help.
How apply the fix? With git command or possible download and update the file?
