### ISSUE TITLE
Credentials wont show after successfull import

### ISSUE THREAD

**Issue by OS3DrNick** [nextcloud/passman#607]
### Steps to reproduce
1. Create new Vault
2. Go to Settings , Import credentials, Pick passman JSON or generic CSV
3. Import your payload

### Expected behaviour
I would have expected that the credentials are visible when going back to the new vault.

### Actual behaviour
No credentials show, clicking any button or option wont make them appear.
The only thing that seems to work, is logging out of the vault and re-enter it again. 

### Configuration
**Operating system**:   Win10
**Browser**:      Chrome
**Extensions that might cause interference**:   Passman / ABP
**Passman version**:    2.3.2

**Operating system**: Raspbian
**Web server:** Apache2
**Database:** MySQL
**PHP version:** 7.x
**cloud server:** Nextcloud
**cloud version:** 14.0.12

**Comment by OS3DrNick** [comment]
Maybe related, maybe not:

When removing tags from a credential, the tags (unique for those) remains visible in the tag search bar.
This disapears after logging back into vault again.

**Comment by newhinton** [comment]
Do they show up when you log in back to your vault?

Is this still valid with 2.3.2?
