### ISSUE TITLE
Can't export vault with files

### ISSUE THREAD

**Issue by newhinton** [nextcloud/passman#609]
The exporter is stuck when files are in a vault, likely due to a missing router

**Comment by ymybe** [comment]
Running Passman 2.3.4, NC17,  (PHP7.3.11-fpm, Apache 2.4.41, MariaDB 10.4.9)-in docker-compose

i can confirm that this issue still persists.

as soon as i removed(destroyed) even deleted files, i could go on with my export.

**Comment by binsky08** [comment]
Is this still an issue?
I haven't had any problems exporting credentials that contain files yet
