### ISSUE TITLE
Adjust notifier to Nextcloud 17

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/passman#610]
Hello App developer,

for Nextcloud 17 the notifications API received some changes:
https://github.com/nextcloud/server/pull/15040

Notable are especially:
* Strict types are checked on the method signature instead of throwing `\InvalidArgumentException` inside
* A new action type `WEB` has been added, which makes the clients open the website instead of sending a request in the background
* Notifier registration has been adjusted to state of the art

For the last point your App needs a patch similar to this Pull Request in the Talk app.
Please see the comments on this GitHub review for detailed steps and explanations:
https://github.com/nextcloud/spreed/pull/2003#pullrequestreview-262492829

Also if your app supports multiple Nextcloud versions, you need to split on this release.
The old way of registering does not work in Nextcloud 17 and the new way does not work in olders.
So you need to make a new release which is exclusive for >=17 and the old one should be for <=16.

Thanks for your understanding and happy hacking

**Comment by paulcalabro** [comment]
Just looked at my logs and it's being flooded with this error, which appears to be related to this issue:

```
[no app in context] Error: InvalidArgumentException: Notifier Passwords (id: passman) is not considered because it is using the old way to register. at <<closure>>

0. /var/www/html/custom_apps/passman/appinfo/app.php line 38
   OC\Notification\Manager->registerNotifier(Closure {}, Closure {})
1. /var/www/html/lib/private/legacy/app.php line 260
   undefinedundefinedrequire_once("/var/www/html/c ... p")
2. /var/www/html/lib/private/legacy/app.php line 154
   OC_App::requireAppFile(OCA\Passman\AppInfo\Application {})
3. /var/www/html/lib/private/legacy/app.php line 127
   OC_App::loadApp("passman")
4. /var/www/html/ocs/v1.php line 56
   OC_App::loadApps()
5. /var/www/html/ocs/v2.php line 24
   undefinedundefinedrequire_once("/var/www/html/ocs/v1.php")

GET /ocs/v2.php/apps/notifications/api/v2/notifications
from 8.39.233.85 by paulcalabro at 2019-09-27T07:27:23+00:00
```

**Comment by cClaude** [comment]
@nickvergessen since https://github.com/nextcloud/passman/pull/621 is merged, could you please close this issues to remove some noise. Thk.
