### ISSUE TITLE
Warn when user fails to add label

### ISSUE THREAD

**Issue by morgankevinj** [nextcloud/passman#615]
#  Bug report

### Steps to reproduce
1. Fill out the form password to add a new password without creating a label 
2. Click save
#
### Expected behaviour
User should be warned that a new entry can not be created without a label

### Actual behaviour
Save operation fails silently

### Configuration
**Operating system**:   Ubuntu 18.04

**Browser**:      

**Extensions that might cause interference**:   

**Passman version**:    

**Operating system**: Ubuntu 18.04

**Web server:**

**Database:** SQLlite

**PHP version:** 7
      
**cloud server:** Nextcloud 

**cloud version:** (see admin page or version.php)
  
   
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>   

#### Cloud log

<details>
<summary>Cloud log</summary>

```
Insert your cloud log here
```
</details>

**Comment by binsky08** [comment]
duplicate issue #657
