### ISSUE TITLE
Custom Fields Not Imported

### ISSUE THREAD

**Issue by 42CF11059F2F** [nextcloud/passman#619]
**Nextcloud Version:** 16.0.5
**PHP Version:** 7.3
**Passwords Version:** 2.3.2
**Server OS and Version:** Debian 10

When importing a Passman JSON file, the import does not import, or skips, any custom field present in the JSON file. This is particularly problematic, as they tend to contain other passwords, e.g. app passwords or NC 2FA app keys.

**Steps to reproduce**
1. have a passman credential with custom fields and export it as JSON
2. import JSON into passwords

**Actual result**
Credentials loose all of their custom fields

**Expected result**
Custom fields should be migrated to passman's own extra fields.

**Comment by a1pilot** [comment]
@jospoortvliet Any response? A bit disappointing it was edited in minutes to add the "bounty" advert but no response given.

**Comment by jospoortvliet** [comment]
@a1pilot that works automatically, I didn't do that ;-)
It'll be up to the Passman developers to respond, if they can/want to do something about this.
