### ISSUE TITLE
App won't enable after the latest update 2.3.3

### ISSUE THREAD

**Issue by JazMTaz** [nextcloud/passman#625]
The Passman app won't enable after the latest 2.3.3 update. Nextcloud version stable Version: 16.0.5.1 and PHP Version: 7.3.10 and MariaDB mysql Version: 10.0.38

Error | no app in context | Error: Call to undefined method OC\Notification\Manager::registerNotifierService()/var/www/nextcloud/lib/private/legacy/app.php - line 260:require_once()/var/www/nextcloud/lib/private/legacy/app.php - line 154:OC_App::requireAppFile(OCA\Passman\ ... {})/var/www/nextcloud/lib/private/legacy/app.php - line 127:OC_App::loadApp("passman")/var/www/nextcloud/lib/base.php - line 960:OC_App::loadApps()/var/www/nextcloud/index.php - line 42:OC::handleRequest()
-- | -- | --

**Comment by jaycedk** [comment]
Im seeing the same error.

**Comment by anojht** [comment]
Yep the app is broken on Nextcloud 16.0.5 with version 2.3.3.

**Comment by samuelb** [comment]
The issue https://github.com/nextcloud/passman/issues/610 mentioned that the change introduced with https://github.com/nextcloud/passman/pull/621 would break version compatibility and min required version of Nextcloud needs to be adjusted, which didn't happened obviously.

I suggest to remove the release 2.3.3 again (i'm not sure what's the right process here) and re-release it with Nextcloud min-version 17 under a new version number.

**Comment by GYJohn** [comment]
I got the same issue.
Would appriciate a quick update/downgrade of the app.

**Comment by newhinton** [comment]
We are aware of that and will fix it shortly with 2.3.4 that targets only nc 16. Then we will work on a more permanent solution. Sorry for the inconvenience!

**Comment by anshibanov** [comment]
I got the same issue. Please fix as soon as possible. Thx

**Comment by wheeler01** [comment]
Same here. Awaiting fix.

**Comment by anojht** [comment]
I found that downgrading to 2.3.2 works for me temporarily.

Steps:
Backup passman directory in the apps folder of you nextcloud installation.
`wget https://github.com/nextcloud/passman/archive/2.3.2.zip`
unzip the contents into your passman directory
I restarted nextcloud, enabled the app and was up and running.

**Comment by animalillo** [comment]
i have just released a hotfix, it reverts compatibility with NC17, the change made it incompatible with NC16 it seems.

For now we have just reverted that code so it's no longer compatible with NC17. We will work on a way to make it compatible with NC17 but not breaking instances on NC16 with an update. Maybe we drop compatibility with NC16 though. We will see anyway.

Hope this restores the passmans of eveyone!

**Comment by Matthew-Hine** [comment]
@animalillo thanks for pushing out a hotfix so quickly, can confirm updating to V2.3.4 restores functionality

**Comment by JazMTaz** [comment]
Confirmed working for me also after updating to 2.3.4

**Comment by GYJohn** [comment]
Working fine now. Thank you!
