### ISSUE TITLE
After upgrade to 2.3.4 down

### ISSUE THREAD

**Issue by Ajilis** [nextcloud/passman#627]
Nextcloud 16.0.5 / PHP 7.3
Firefox 69.0.3
Extension 2.1.1

Webapp 2.3.2 OK
Webapp 2.3.3 KO  [0] Invalid reply from server
Webapp 2.3.4 KO [0] Invalid reply from server

**Comment by animalillo** [comment]
What is failing? Please, we need more details to debug this issue.
Do you have logs?
The problem is on the web or on the extension?
Give us something more, please, thanks!

**Comment by Ajilis** [comment]
For me its on the webapp all other things havent been changed.
When i restored the VM server with same nextcloud (16.0.5) with the old jully app (2.3.2)  its works.

The issue is : when i try to logon on the firefox extension when i put continue the extension respond : Invalid reply from server and i cant even view and  select any vaults

**Comment by animalillo** [comment]
Any server logs?

Can you check if you can access the vault via the web app instead of via the firefox extension?

**Comment by Ajilis** [comment]
Sorry for disturb;  the app wasnt activated after upgrade ;)
Thanx for review.

**Comment by animalillo** [comment]
NP! hope it all works nicely!
Today i had the busiest day of the year i think hahaha. I should be sleeping already, so i will do that now.

Have a good day!
