### ISSUE TITLE
New Version 2.3.4 for Nextcloud 17

### ISSUE THREAD

**Issue by BijuuKrunos** [nextcloud/passman#628]
Heyho just updated to Nextcloud 17. Now i got a new update for passman. After i updated my log is full of this:
InvalidArgumentException: Notifier Passwörter (id: passman) is not considered because it is using the old way to register.

    /var/www/nextcloud/apps/passman/appinfo/app.php - line 38:

    OC\Notification\Manager->registerNotifier(Closure {}, Closure {})

    /var/www/nextcloud/lib/private/legacy/app.php - line 260:

    require_once("/var/www/ne ... p")

    /var/www/nextcloud/lib/private/legacy/app.php - line 154:

    OC_App::requireAppFile(OCA\Passman\ ... {})

    /var/www/nextcloud/lib/private/legacy/app.php - line 127:

    OC_App::loadApp("passman")

    /var/www/nextcloud/lib/base.php - line 985:

    OC_App::loadApps()

    /var/www/nextcloud/index.php - line 42:

    OC::handleRequest()

Now i see that the new version is not for Nextcloud 17. but why it tells me to update then? pls update your app to Nextcloud 17 again.

**Comment by Matthew-Hine** [comment]
Hey, this is related to #625 - give it a read to catch up with what's going on

**Comment by newhinton** [comment]
We needed a quick fix because nextcloud 16 broke. You can wait for 2.3.5 (Which will be out at the end of the week)

You could try to remove the application, and reinstall it from the appstore, that should downgrade you to 2.3.3.

Backup your database beforehand, so that in the case of errors you have your data secure!

**Comment by BijuuKrunos** [comment]
its working. Just 20 Errors per second xD. But don't worry my system has over 2tb left. so i will wait. 
thx for the fast answer.

**Comment by newhinton** [comment]
Ah okay :D
can you edit files on the server? you could edit the offending file, that would stop the spamming

**Comment by BijuuKrunos** [comment]
Yeah of course i can. What should I edit?

**Comment by newhinton** [comment]
https://github.com/nextcloud/passman/commit/52b97e781e5c9420d5dc5a1da73929fdce0513af

in appinfo/app.php

lines 26 to 38 register the notification service
if you comment those lines out, the spamming should stop

this will remove notifications, but they are broken anyway, so nothing lost until 2.3.5 ;)

**Comment by BijuuKrunos** [comment]
puhh thx. yep it works.

**Comment by darkernoise** [comment]
newhinton, you rock!  Your suggestion works perfectly.  NC 17 now works with passman.  Well, minus notifications, but no big deal really.

**Comment by Bubu** [comment]
Any update on this?

**Comment by darkernoise** [comment]
Bubu,

There are some more incompatibilities with NC17 and 2.3.4, even with the notifications removed.  Mostly, the formatting is off, making passman kind of hard to use, but possible.  I am running it in production only out of desperation.  Hopefully 2.3.5 will be released soon.

**Comment by newhinton** [comment]
@Bubu We will prepare an update as soon as possible for nc17

@darkernoise Can you give me examples on where formatting is off? I'd like to solve those too. (Im not yet on nc17)

**Comment by darkernoise** [comment]
@newhinton: Yes, I think NC17 changes quite a lot about formatting.  Her are a few major areas:

- Add new or Edit. Panel is uformatted, with no column/cell spacing

[https://imgur.com/gkerYSk](url)

- Toggle Visibility (to view a password), does nothing, but close the current selected item
- If you select an item, the right side buffer is way too large, forcing the left side into the menu list, making neither readable

[https://imgur.com/vfsRw65](url)

- Mobile formatting is completely off

**Comment by newhinton** [comment]
Thanks for posting pictures, however this seems to be a build-error, not an actual error in passman.
(which does not mean it should not be fixed, however, it should be automatically fixed with 2.3.5)

**Comment by Bubu** [comment]
Nextcloud 18 is currently in beta.

**Comment by emper0r** [comment]
upgrading to last version of passman this issue is solved.

**Comment by cClaude** [comment]
@BijuuKrunos I think this issue could be close now. Thank to close it if not more relevant to remove some noise. Now we have NextCloud 20 in stable channel.
