### ISSUE TITLE
Passman don't detect I'm behind a proxy

### ISSUE THREAD

**Issue by JOduMonT** [nextcloud/passman#630]
Hi;

I'm using this [docker-compose](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy-self-signed-ssl/mariadb/fpm/docker-compose.yml) which works perfectly.

The only issue is Passman consider nextcloud running on a non HTTPS server, which technicaly is true when you look at [nginx config](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy-self-signed-ssl/mariadb/fpm/web/nginx.conf)

My 1st question is: the issue is on Nextcloud core or on Passman side because it did'nt dectect I'm behing a proxy ?

My 2nd question is: Why Passman don't consider the fact I'm behind a proxy ?
_Yes!, I understand, even on the server someone could sneaky pete my http but really..._

Thank you

ref: https://github.com/nextcloud/docker/issues/906

**Comment by Oliv4945** [comment]
Hi Jonathan,

I think in that configuration I used `'overwriteprotocol' => 'https'` in config.php, but it was really long time ago so my memory can trick me
