### ISSUE TITLE
Add quick copy to clipboard in browser extension

### ISSUE THREAD

**Issue by matlag** [nextcloud/passman#636]
To make it possible for us to help you please fill out below information carefully.

If you like to make a feature request, please remove the issue template.
If you want to fill in a issue, remove the feature request template.

## Feature request

**User type**: Logged-in

**User level**: Intermediate

### Description
Some browsers do not work with the auto-fill feature. So we need to click on the extension button to list the site matching credentials login, then edit, then copy the password and paste.
This is a bit heavy. In particular on Firefox for Android, on small screens, the "edit" button is not visible in portrait, only when you rotate the phone in landscape mode.

The request is to have a "copy password to clipboard" button right next to the matching credential login in the browsers extensions.

### Benefit / value

This is just to save some time and make the login process quicker when auto-fill does not work.

### Risk / caveats

Accidentally copying the password can lead to an accidental paste as well. Though one could say all copy can lead to accidental paste. I would say seen from my humble window, the risk seems low.

### Sponsorship
 
**Are you a developer willing to implement this feature?**: yes/no

No to the first, so no to the last...

**Can you sponsor the development of this feature or do you know someone who can?**: yes/no

Let's be honest and admit I've never contributed financially to this project.
Let's also say that I'm organizing myself to donate to opensource projects I use and rely on, this one is on the list, but I won't withhold anything based on this feature implementation.

**Comment by Oliv4945** [comment]
Hi, it has been done and merged few month ago but we need to wait for @animalillo  to publish a new version
