### ISSUE TITLE
NC additional settings are showing "1"

### ISSUE THREAD

**Issue by GYJohn** [nextcloud/passman#640]
## Bug report
NC additional settings are showing "1"

### Steps to reproduce
1. Install passman on NC 16 or 17
2. Open "additional settings" in NC settings menu

### Expected behaviour
You should see the NC additional settings

### Actual behaviour
You see "1"

### Configuration
**Operating system**:   
Debian 10

**Browser**:      
Chromium

**Extensions that might cause interference**:   
Passman

**Passman version**:    
2.3.5

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
PHP 7.3
      
**cloud server:** Nextcloud 

**cloud version:** 17
  
   
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>   

#### Cloud log

<details>
<summary>Cloud log</summary>

```
Insert your cloud log here
```
</details>

## Feature request

**User type**: Logged-in or public user

**User level**: Beginners, intermediate or advanced

### Sponsorship

 
**Are you a developer willing to implement this feature?**: yes/no

**Can you sponsor the development of this feature or do you know someone who can?**: yes/no

**Comment by shyaminayesh** [comment]
I can confirm this under NC 17 with Passman v2.3.4

**Comment by GYJohn** [comment]
Still in passman: 2.3.5 :(
