### ISSUE TITLE
Make it compatible with nextcloud dark mode [$10]

### ISSUE THREAD

**Issue by shyaminayesh** [nextcloud/passman#643]
### Steps to reproduce
1. Install NC 17
2. Install Passman v2.3.4
3. Activate NextCloud Dark theme from ( Settings > Accessibility )

### Expected behaviour
Passman with dark theme support.

### Actual behaviour
![image](https://user-images.githubusercontent.com/2026926/71250164-fa299980-2344-11ea-9676-630709194a61.png)

### Configuration
**Operating system**:  Debian 9
**Browser**: Chromium 79.0
**Extensions that might cause interference**: Passman
**Passman version**: 2.3.4
**Web server**: Nginx
**Database**: MariaDB
**PHP version**: 7.3
**cloud server**: Nextcloud
**cloud version**: 17.0.1

**Comment by synthead** [comment]
This commit looks like a great starting point: https://github.com/nextcloud/activity/commit/0473fd324535ed402ac1c92e46d7fbbe66db8332.

Instead of explicit colors like:

```
 	border: 1px solid #ddd;
```

...we'll probably want to use variables to set the colors, like this:

```
 	border: 1px solid var(--color-border-dark);
```

**Comment by Luckyvb** [comment]
beta version.
[passman.min.zip](https://github.com/nextcloud/passman/files/5351337/passman.min.zip)
Now i try to make pull request

**Comment by Luckyvb** [comment]
https://github.com/Luckyvb/passman/commit/b0c9ec879c5c053bd0cc797878abf1983b0c9917

**Comment by skervista** [comment]
Hi, I was working on this too. Do you need some help?

**Comment by Luckyvb** [comment]
my changes look good. but need right changes to make pool request and maybe refactoring.
![изображение](https://user-images.githubusercontent.com/5268904/95725484-641e8100-0c80-11eb-8fe4-06fff2de9851.png)

**Comment by binsky08** [comment]
you could also try https://apps.nextcloud.com/apps/breezedark it colours my passman perfectly :)
