### ISSUE TITLE
[Feature Request] Backup

### ISSUE THREAD

**Issue by STiAT** [nextcloud/passman#644]
I'd like to request a functionality to actually backup my passwords in a format which can be opened by other password managers, or in another nextcloud installation (kdbx or some encrypted passman file I could re-import if my provider killed it).

I do trust my hosting provider, but my trust just goes as far as I can spit.

**Comment by Dragon988** [comment]
What is the problem with CSV?

**Comment by newhinton** [comment]
Please see #633, this here is a duplicate.
