### ISSUE TITLE
[question] Passman for Owncloud 10.3.2?

### ISSUE THREAD

**Issue by Rasco94** [nextcloud/passman#647]
### Steps to reproduce
1.PassMan run
2.Upgrade Owncloud 10.3.2
3.Disable PassMan because not version on market for new owncloud

### Expected behaviour
Tell us what should happen

### Actual behaviour
hello everyone, I have a question in question, I used a lot of passman on owncloud and I was fine but when I had to update owncloud, I also had to disable passman because there was still no version for owncloud 10.3.2. Do you know when it will come out?
Thanks so much.

P.S. I am new to the group and I don't know if I have done the correct steps to write my question. sorry in advance

### Configuration
**Operating system**:   
ubuntu server 18.04
**Browser**:      
chrome
**Extensions that might cause interference**:   

**Passman version**:    
2.1.4 on market
**Operating system**:
linux ubuntu 18.04
**Web server:**
aphace2
**Database:**
mysql
**PHP version:**
      
**cloud server:** Nextcloud or ownCloud
owncloud
**cloud version:** (see admin page or version.php)
  10.3.2
   
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>   

#### Cloud log

<details>
<summary>Cloud log</summary>

```
Insert your cloud log here
```
</details>

## Feature request

**User type**: Logged-in or public user

**User level**: Beginners, intermediate or advanced

### Sponsorship

 
**Are you a developer willing to implement this feature?**: yes/no

**Can you sponsor the development of this feature or do you know someone who can?**: yes/no

**Comment by javyer** [comment]
I have same issue with latest Owncloud 10.3.2 , it's disabled but can't be enabled after upgrade.
Here are some dirty work around : 
- **change**  apps/passman/appinfo/info.xml to
     ` <owncloud min-version="10.0" max-version="1`**1**`.0" />`
- **remove** apps/passman/appinfo/signature.json, this will avoid ugly notification on integrity checks.

Passman project is not very healthy :-(

**Comment by binsky08** [comment]
sry, there is no longer app support for Owncloud because the code base of Nextcloud and Owncloud is getting further and further apart.
If you want to continue receiving updates for Passman you should migrate to Nextcloud
