### ISSUE TITLE
Vault password incorrect after migration

### ISSUE THREAD

**Issue by oleterno** [nextcloud/passman#648]
## Bug report
I have just migrated my nextcloud server from one machine to another. After the migration I cannot log into any vaults with the password I used on the older machine. The newer machine has a different nextcloud server version and the only directory copied from the older machine is the data directory. The passman app seems to work, and the vaults created previously are there, but they cannot be logged into with the passwords set on the older machine. 
### Steps to reproduce
1. Run nextcloud 17.0.3.1 with passman 2.3.5
2. Enter maintenance mode, export database and data folder. 
3. Install nextcloud 18.0.1.3 on new machine and import database and data folder.

### Expected behaviour
Passman should work as previously, and users should be able to use the existing vault passwords.

### Actual behaviour
When attempting to decrypt/access a vault, it says that the vault password is incorrect. 

### Configuration
**Operating system**:   
Ubuntu server 18.04.4 LTS
**Browser**:      
Chrome
**Passman version**:    
2.3.5
**Web server:**
Apache/2.4.29
**Database:**
MySQL 5.7.29-0ubuntu0.18.04.1
**PHP version:**
PHP 7.3.15-2+ubuntu18.04.1+deb.sury.org+2
**cloud server:** 
Nextcloud
**cloud version:**
18.0.1.3

**Comment by oleterno** [comment]
I started the older nextcloud server and exported the credentials from there and imported them in new vaults on the new nextcloud server. I now have my credentials back. I'm not sure if I should close this issue or not.

**Comment by animalillo** [comment]
did you back up your old server's config file? there's a secret used by passman's server side encryption

**Comment by oleterno** [comment]
Thank you, that was the problem. I copied over the `'passwordsalt'` and `'secret'` from the config.php on the old nextcloud server to the new nextcloud server, and now I can access my vaults.
