### ISSUE TITLE
Works with PostgreSQL

### ISSUE THREAD

**Issue by microniko** [nextcloud/passman#655]
Hi,

I would like just to tell you that Passman is working with PostgreSQL :
PHP : 7.3.14
PostgreSQL 11.7 (Debian 11.7-0+deb10u1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

(README.md says is Untested ;-)

**Comment by animalillo** [comment]
Thank you for remembering this to us. We had official support for postgres since ages ago hahaha
