### ISSUE TITLE
Can't add password to passman if label is not set

### ISSUE THREAD

**Issue by jsalatiel** [nextcloud/passman#657]
### Steps to reproduce
1. Try to add a password without settings label
2. Click save

### Expected behaviour
Password should be saved or a error message should be given to the user

### Actual behaviour
Saving button keeps spinning and exception thrown on logs.

### Configuration
**Operating system**:    Linux

**Browser**:      Firefox

**Passman version**:     2.3.5

**Operating system**: Nextcloud Docker container

**Web server:** Nextcloud Docker container

**Database:** Postgres

**PHP version:** Nextcloud Docker container
      
**cloud server:** Nextcloud 

**cloud version:** 18.0.6
  
 

#### Cloud log

<details>
<summary>Cloud log</summary>

```

{
  "reqId": "YPzQviK3WGK5kiP3BSf6",
  "level": 3,
  "time": "2020-06-22T12:21:27+00:00",
  "remoteAddr": "10.175.143.42",
  "user": "obfuscated",
  "app": "index",
  "method": "POST",
  "url": "/index.php/apps/passman/api/v2/credentials",
  "message": {
    "Exception": "Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException",
    "Message": "An exception occurred while executing 'INSERT INTO \"oc_passman_credentials\"(\"guid\",\"vault_id\",\"user_id\",\"description\",\"created\",\"changed\",\"tags\",\"email\",\"username\",\"password\",\"url\",\"expire_time\",\"delete_time\",\"files\",\"custom_fields\",\"otp\",\"hidden\",\"compromised\") VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)' with params 
...
:\n\nSQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"label\" violates not-null constraint\nDETAIL:  Failing row contains ...

```
</details>

I also note that there's a broken icon on:
![image](https://user-images.githubusercontent.com/5522389/85288350-f7cb0800-b46b-11ea-9563-3d92370f0e30.png)

**Comment by zandercodes** [comment]
You cannot save if you leave the label empty.
This is also stated in the SQL message.

**Comment by jsalatiel** [comment]
I know that. What I mean is that it should show some error popup to the user instead of keep spinning forever like it is saving but it is saving reeeeeaaaalllyyyy slow. The user has no access to the logs and sql messages to see what's hapenning.
