### ISSUE TITLE
Ignore

### ISSUE THREAD

**Issue by john-clark** [nextcloud/passman#658]
### Steps to reproduce
1. log into site with firefox
2. prompted to save credentials
3. Click ignore

### Expected behaviour
Should not prompt again

### Actual behaviour
prompts to save every time you revisit site

### Configuration
**Operating system**:   windows 10

**Browser**:   firefox

**Extensions that might cause interference**:   ublock origin

**Passman version**:    client 2.1.1

**Web server:** nginx

**Database:** mariadb

**PHP version:** 7.3.19
      
**cloud server:** Nextcloud

**cloud version:** 18.,0.7
  
   
#### Browser log
<details>
none
</details>   

#### Cloud log
<details>
none
</details>

## Feature request

**User type**: Logged-in

**User level**: Beginners

### Description
function improvement

### Benefit / value
users

### Risk / caveats
none

### Sponsorship
none
 
**Are you a developer willing to implement this feature?**: no

**Can you sponsor the development of this feature or do you know someone who can?**: no

**Comment by binsky08** [comment]
if this is still an issue, please open a new issue in the right repository: https://github.com/nextcloud/passman-webextension
