### ISSUE TITLE
Passman not working on owncloud

### ISSUE THREAD

**Issue by gpapaiko** [nextcloud/passman#660]
Hi,

I just downloaded the latest version of passman 2.30 and installed on owncloud 10.5.0.

I get 3 errors,  two minor and one major.

1/ the version in our info.xml has min version of 14 for owncloud, this will notwork as the current version is 10.5  this need to be updated to 10, hence we this is done manually the signature.json file becomes invalid.

2/ when version changed to 10, it then tells me that there is anew version 2.3.5, if I download that version owncloud crashes completely.

3/ (major)  this app completely fails owncloud integrity checks 
See attached file
[passman-error.txt](https://github.com/nextcloud/passman/files/5080259/passman-error.txt)

**Comment by vwbusguy** [comment]
I noticed that when I did the bump for the Nextcloud version.  Would setting the owncloud min and max version to 10 fix it?
