### ISSUE TITLE
[Solved] Incompatible with Nextcloud 20.0.1

### ISSUE THREAD

**Issue by xorbetto** [nextcloud/passman#665]
### Steps to reproduce
1. Install/Upgrade to Nextcloud 20

### Expected behaviour
Passman should work

### Actual behaviour
Page is blank and errors comes out on js console:

### Configuration
**Operating system**:   Arch linux

**Browser**:      Chrome

**Extensions that might cause interference**:   None

**Passman version**:    2.3.6

**Operating system**:

**Web server:** Apache2

**Database:** sqlite

**PHP version:** 7.4
      
**cloud server:** Nextcloud 

**cloud version:** (see admin page or version.php)
  
   
#### Browser log
<details>
<summary>Browser log</summary>
```
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=passmanApp&p1=Error%3A%20%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.5.8%2F%24injector%2Fnomod%3Fp0%3DpassmanApp%0A%20%20%20%20at%20http%3A%2F%2F172.16.16.2%2Fnextcloud%2Fapps%2Fpassman%2Fjs%2Fpassman.min.js%3Fv%3D20de4995-12%3A890%3A20%0A%20%20%20%20at%20http%3A%2F%2F172.16.16.2%2Fnextcloud%2Fapps%2Fpassman%2Fjs%2Fpassman.min.js%3Fv%3D20de4995-12%3A1364%3A35%0A%20%20%20%20at%20b%20(http%3A%2F%2F172.16.16.2%2Fnextcloud%2Fapps%2Fpassman%2Fjs%2Fpassman.min.js%3Fv%3D20de4995-12%3A1343%3A36)%0A%20%20%20%20at%20http%3A%2F%2F172.16.16.2%2Fnextcloud%2Fapps%2Fpassman%2Fjs%2Fpassman.min.js%3Fv%3D20de4995-12%3A1351%3A67%0A%20%20%20%20at%20http%3A%2F%2F172.16.16.2%2Fnextcloud%2Fapps%2Fpassman%2Fjs%2Fpassman.min.js%3Fv%3D20de4995-12%3A1809%3A37%0A%20%20%20%20at%20q%20(http%3A%2F%2F172.16.16.2%2Fnextcloud%2Fapps%2Fpassman%2Fjs%2Fpassman.min.js%3Fv%3D20de4995-12%3A908%3A69)%0A%20%20%20%20at%20g%20(http%3A%2F%2F172.16.16.2%2Fnextcloud%2Fapps%2Fpassman%2Fjs%2Fpassman.min.js%3Fv%3D20de4995-12%3A1797%3A20)%0A%20%20%20%20at%20cb%20(http%3A%2F%2F172.16.16.2%2Fnextcloud%2Fapps%2Fpassman%2Fjs%2Fpassman.min.js%3Fv%3D20de4995-12%3A1900%3A17)%0A%20%20%20%20at%20c%20(http%3A%2F%2F172.16.16.2%2Fnextcloud%2Fapps%2Fpassman%2Fjs%2Fpassman.min.js%3Fv%3D20de4995-12%3A1265%3A43)%0A%20%20%20%20at%20Bc%20(http%3A%2F%2F172.16.16.2%2Fnextcloud%2Fapps%2Fpassman%2Fjs%2Fpassman.min.js%3Fv%3D20de4995-12%3A1273%3A121)
    at passman.min.js?v=20de4995-12:890
    at passman.min.js?v=20de4995-12:1811
    at q (passman.min.js?v=20de4995-12:908)
    at g (passman.min.js?v=20de4995-12:1797)
    at cb (passman.min.js?v=20de4995-12:1900)
    at c (passman.min.js?v=20de4995-12:1265)
    at Bc (passman.min.js?v=20de4995-12:1273)
    at fe (passman.min.js?v=20de4995-12:1249)
    at HTMLDocument.<anonymous> (passman.min.js?v=20de4995-12:8209)
    at l (main.js?v=20de4995-12:1)
```
</details>   

#### Cloud log

<details>
<summary>Cloud log</summary>
None relevant
</details>

**Comment by vwbusguy** [comment]
By enabling untested apps, it works.  I haven't found any regressions yet.  It probably just needs the version bumped again.  The web view works, as well as the Firefox plugin.

**Comment by TheFoxStudio** [comment]
@vwbusguy can you tell me where to find this "enable untested apps"?
I have been looking through the settings but seem to miss it. Would be much appreciated

**Comment by xorbetto** [comment]
**@vwbusguy** you're rigth! version bumping solved the issue.

**Comment by TheFoxStudio** [comment]
I'd love if you guys share how to do this version bump.

**Comment by filipesaraiva** [comment]
@TheFoxStudio https://github.com/nextcloud/passman/issues/665#issuecomment-718245798:
> I'd love if you guys share how to do this version bump.

https://github.com/nextcloud/passman/blob/master/appinfo/info.xml#L45
