### ISSUE TITLE
Site is blank with Nextcloud 20.0.2

### ISSUE THREAD

**Issue by MhhhxX** [nextcloud/passman#671]
### Steps to reproduce
1. open passman

### Expected behaviour
Vaults should appear

### Actual behaviour
Site stays blank
![image](https://user-images.githubusercontent.com/23461170/100117580-4181a980-2e75-11eb-9ec3-29c997d9c1d7.png)

### Configuration
**Operating system**:   Arch Linux

**Browser**:      Firefox 83

**Extensions that might cause interference**:   

**Passman version**:    2.3.6

**Operating system**: Arch Linux

**Web server:** Nginx

**Database:** Mariadb

**PHP version:** 7.4
      
**cloud server:** Nextcloud

**cloud version:** (see admin page or version.php) 20.0.2
  
   
#### Browser log
<details>
<summary>Browser log</summary>
```



a) Browserlog
Failed to instantiate module passmanApp due to:
[$injector:nomod] http://errors.angularjs.org/1.5.8/$injector/nomod?p0=pass...
N/<@https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3:596
ke/</</<@https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3:10067
b@https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3:9609
ke/</<@https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3:9852
g/<@https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3:17535
q@https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3:1043
g@https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3:17384
cb@https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3:19426
c@https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3:7821
Bc@https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3:8124
fe@https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3:7426
@https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:7:31015
l@https://example.de/core/js/dist/main.js?v=63049fc1-0:1:27980
add@https://example.de/core/js/dist/main.js?v=63049fc1-0:1:28276
o/m.fn.ready@https://example.de/core/js/dist/main.js?v=63049fc1-0:1:30346
@https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:7:30996
@https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:7:31034

Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=pass…assman%2Fjs%2Fpassman.min.js%3Fv%3D63049fc1-0%3A7%3A31034%0A
    N https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3
    g https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3
    q https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3
    g https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3
    cb https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3
    c https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3
    Bc https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3
    fe https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3
    <anonymous> https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:7
    l https://example.de/core/js/dist/main.js?v=63049fc1-0:1
    add https://example.de/core/js/dist/main.js?v=63049fc1-0:1
    ready https://example.de/core/js/dist/main.js?v=63049fc1-0:1
    <anonymous> https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:7
    <anonymous> https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:7
passman.min.js:3:596
    N https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3
    g https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3
    q https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3
    g https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3
    cb https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3
    c https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3
    Bc https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3
    fe https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:3
    <anonymous> https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:7
    l https://example.de/core/js/dist/main.js?v=63049fc1-0:1
    add https://example.de/core/js/dist/main.js?v=63049fc1-0:1
    ready https://example.de/core/js/dist/main.js?v=63049fc1-0:1
    <anonymous> https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:7
    <anonymous> https://example.de/apps/passman/js/passman.min.js?v=63049fc1-0:7


</details>


#### Cloud log
<!--
The log has the name owncloud.log or nextcloud.log and is found in the data folder


<details>
<summary>Cloud log</summary>

```
Insert your cloud log here
```
</details>-->

**Comment by mproboeuf** [comment]
@MhhhxX : did you solve the issue ? I'm getting the same issue (same passman / php / nexcloud versions)

**Comment by MhhhxX** [comment]
@mproboeuf 
Sometimes the page loads for me and sometimes not :/

**Comment by blitzdesigner** [comment]
same here, but with PHP 7.3 on Ubuntu.
Empy page, so far did not load ever...

**Comment by kajoik** [comment]
I am using the docker image nextcloud:20.0.3. I also get the blank page initially, but if I click on the menu item once again, passman opens.

**Comment by TheFoxStudio** [comment]
Just out of curiousity. Is the dev still maintaining this project? The Nextcloud Version 20 issue exists since Version 20.0.1. Now we are at 20.0.4 and it has still not been fixed. Anyone know a good alternative that is working and updated?

In terms of the actual issue, as far as I know all that needs to be done is a version bump to make it compatible. But the dev is not doing it.

**Comment by wilya7** [comment]
> Just out of curiousity. Is the dev still maintaining this project? The Nextcloud Version 20 issue exists since Version 20.0.1. Now we are at 20.0.4 and it has still not been fixed. Anyone know a good alternative that is working and updated?
> 
> In terms of the actual issue, as far as I know all that needs to be done is a version bump to make it compatible. But the dev is not doing it.

My understanding is that the developers are not updating passman since the last couple of years. So far they bump the version, but it takes them quite a long time to do so. 

I Installed Nextcloud 20.0.4 and I can confirm no issue with passman. The dark theme is not working, but that was already a known problem. For the rest, everything works as before, as far as I can tell.

**Comment by rthouvenin** [comment]
I do face the issue with Nextcloud 20.0.4, after an upgrade from 19 and forcing activation of passman

**Comment by svalat** [comment]
I just upgrade to Nextcloud 20 and god issues with Chrome (blank page as described) but passman looks to work with Firefox.

**Comment by paulcalabro** [comment]
I've noticed, at least with FF, that if I bypass the cache the page loads as expected. When I don't, however, the page appears blank.

**Comment by mproboeuf** [comment]
Just updated to Nextcloud 21.0.1. No more issue with passman 2.3.7.
