### ISSUE TITLE
Support for NextCloud 20

### ISSUE THREAD

**Issue by muckinger** [nextcloud/passman#673]
After Updating Nextcloud to Version 20.0.4 i get the Message, the Passmann is no compatible with it:

_This app cannot be installed because the following dependencies are not fulfilled:
Server version 19 or lower is required._

And i just have the Option to "enabled untested App"...

Are there any Plans to make Passmann again compatible with the current NextCloud Version?
![nextcloud-20-passman](https://user-images.githubusercontent.com/389825/102341879-c6557400-3f98-11eb-9f8a-c3f4873434f3.png)

**Comment by trendless** [comment]
This. It also shows Passman as missing an update for compatibility with NC 20.0.4 in Admin/Overview, down in the update/upgrade section:

![Screenshot 2020-12-16 164803](https://user-images.githubusercontent.com/1134495/102423853-c8322e00-3fbe-11eb-8d07-e10b748dee5b.png)

**Comment by cClaude** [comment]
An issue is open related to NextCloud 20: https://github.com/nextcloud/passman/issues/671

**Comment by thsnielsen** [comment]
Passman not being V20 compatible is all that is holding me back on v19 ..

**Comment by lyn1337** [comment]
Are there plans at all to make this work on NC 20? Or will a migration to the passwords app be in order?

**Comment by thsnielsen** [comment]
Anybody has exberience with opening the passman app and tweaking the supported nextcloud version to 20?

**Comment by trendless** [comment]
> Are there plans at all to make this work on NC 20? Or will a migration to the passwords app be in order?

Passman can export a json which imports well into Passwords, no fancy auto migration required 😊

**Comment by thsnielsen** [comment]
sad sad : 
Nextcloud 19.0.8

A new version is available: Nextcloud 20.0.7
1 app has no update for this version available
Apps missing updates

    Passman ↗

**Comment by Rafiot** [comment]
Someone should probably archive this repo and add a link to the migration guide provided by passwords: https://git.mdns.eu/nextcloud/passwords/wikis/Users/Import/Import-from-Passman

**Comment by rthouvenin** [comment]
I upgraded to Nextcloud regardless, and force-activated passman which made me face #671. I got out of it this way:

 - Backed up my data
 - de-activate passman
 - delete passman
 - install and activate passman

The DB had not been touched during uninstall, no it works normally.
I hope this helps!
