### ISSUE TITLE
Migrate to Passwords app on Nextcloud 20

### ISSUE THREAD

**Issue by Rafiot** [nextcloud/passman#675]
**Disclamer**: I'm not a nextcloud/passman/password developer

This app seems to be deprecated in favor of [passwords](https://apps.nextcloud.com/apps/passwords), and there is a [migration guide](https://git.mdns.eu/nextcloud/passwords/wikis/Users/Import/Import-from-Passman).

**Comment by nefh** [comment]
It's sad to see this, since I've used Passman for many years. NC Passwords are still missing many features, even basic, like autofill in browsers, but Passman with each Nextcloud update is more obsolete. Now, in NC20 the web configuration is not working, only extensions can still connect to the vaults.

**Comment by wilya7** [comment]
> It's sad to see this, since I've used Passman for many years. NC Passwords are still missing many features, even basic, like autofill in browsers, but Passman with each Nextcloud update is more obsolete. Now, in NC20 the web configuration is not working, only extensions can still connect to the vaults.

In my two nextcloud home servers, I had no problems passing to NC 20. The passman menu is correctly shown when I open my account.

**Comment by Luticus** [comment]
my web configuration works fine in NC 20, my main issue is that the export credentials doesn't seem to work so I can't migrate easily! When I click the button it says it's "decrypting passwords" but just sits there. Does anyone know of a way around this?

**Comment by wilya7** [comment]
> my main issue is that the export credentials doesn't seem to work so I can't migrate easily! When I click the button it says it's "decrypting passwords" but just sits there. Does anyone know of a way around this?

I works just fine for me, both CVS and JSON. Just wondering if it can be a browser problem?

**Comment by Luticus** [comment]
I've tested on Nextcloud 21 and it's fine there too. Search still appears broken and exporting passwords still fails for me, but other than that everything seems ok.

**Comment by animalillo** [comment]
With the new release there's full support for nc22, so i think i will be closing this issue

https://github.com/nextcloud/passman/releases/tag/2.3.7

**Comment by Luticus** [comment]
@animalillo Thank you so much for continuing to maintain this app!!! It is so much better than the nc passwords app in my opinion. Seeing the new version today made my whole week. You guys are epic!

**Comment by animalillo** [comment]
Thank @binsky08 for their neat MRs! It's doing a great job migrating the app to the latest nextcloud core enhacements!

**Comment by nefh** [comment]
It's a great surprise. It's really good to see Passman updated. Many thanks!

**Comment by Luticus** [comment]
@animalillo @binsky08 As far as I'm concerned anyone who contributes to this project is a freaking hero. Thanks for all you guys do.
