### ISSUE TITLE
Will this be work with Owncloud 10.x (10.6)

### ISSUE THREAD

**Issue by gpapaiko** [nextcloud/passman#676]
Hi are there any plans to make this work with owncloud 10.x version at all.
The current version I have working with owncloud is 2.1.4.
I have tried this version but  it gives too many error:
An unhandled exception has been thrown:
Error: Call to undefined method OC\Notification\Manager::registerNotifierService() in /var/www/owncloud/insapps/passman/appinfo/app.php:29
Stack trace:
#0 /var/www/owncloud/lib/private/legacy/app.php(253): require_once()
#1 /var/www/owncloud/lib/private/legacy/app.php(192): OC_App::requireAppFile()
#2 /var/www/owncloud/lib/private/legacy/app.php(1021): OC_App::loadApp()
#3 /var/www/owncloud/lib/private/legacy/app.php(987): OC_App::executeRepairSteps()
#4 /var/www/owncloud/lib/private/Updater.php(345): OC_App::updateApp()
#5 /var/www/owncloud/lib/private/Updater.php(271): OC\Updater->doAppUpgrade()
#6 /var/www/owncloud/lib/private/Updater.php(112): OC\Updater->doUpgrade()
#7 /var/www/owncloud/core/Command/Upgrade.php(266): OC\Updater->upgrade()
#8 /var/www/owncloud/lib/composer/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
#9 /var/www/owncloud/lib/composer/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#10 /var/www/owncloud/lib/composer/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#11 /var/www/owncloud/lib/composer/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#12 /var/www/owncloud/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run()
#13 /var/www/owncloud/console.php(116): OC\Console\Application->run()
#14 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#15 {main}

Thanks.

**Comment by wilya7** [comment]
As far as I can tell, passman is abandoned.

**Comment by gpapaiko** [comment]
Thanks for the update.

**Comment by animalillo** [comment]
We have dropped owncloud support because the differences between the two cores are getting on very separate paths.
