### ISSUE TITLE
Log Stuffed 

### ISSUE THREAD

**Issue by minalexcorporation** [nextcloud/passman#683]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system**:   

**Browser**:      

**Extensions that might cause interference**:   

**Passman version**:    

**Operating system**:

**Web server:**

**Database:**

**PHP version:**
      
**cloud server:** Nextcloud or ownCloud

**cloud version:** (see admin page or version.php)
  
   
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>   

#### Cloud log

<details>
<summary>Cloud log</summary>

```
Insert your cloud log here
```
</details>

## Feature request

**User type**: Logged-in or public user

**User level**: Beginners, intermediate or advanced

### Sponsorship

 
**Are you a developer willing to implement this feature?**: yes/no

**Can you sponsor the development of this feature or do you know someone who can?**: yes/no

**Comment by binsky08** [comment]
could you please post a log message?

**Comment by minalexcorporation** [comment]
Sorry that posted unintentionally  thanks to some annoying keyboard shortcut that occurred when my hands freaked out on me for a second. Here's a copy/paste of the one I was working on below.
------------------------------------------------------------------
 
## Bug report

### Steps to reproduce
1.Install Passman
2.Not sure if necessary, but I created a vault played around, then removed it.
3.Look at the logs

### Expected behaviour
Sorry not sure what Passman's logs should look like.

### Actual behaviour
The log posts one to five (or more) times a second:
/appinfo/app.php is not loaded when \OCP\AppFramework\Bootstrap\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.

### Configuration
**Operating system**:   Linux - Proxmox Container, originally spawned from TurnKey Linux "appliance". Manually updated NextCloud to version 21. Per the settings screen in NextCloud: Linux 5.4.78-2-pve x86_64

**Browser**:  Brave

**Extensions that might cause interference**:   
None, but for fun: LastPass installed, HTTPS Everywhere installed. The following two extensions are DISABLED for the local NextCloud instance: Privacy Badger, UBlockOrigin

**Passman version**:    2.3.7

**Operating system**: (assuming client here) Linux - POP-OS

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.3.27
      
**cloud server:** Nextcloud

**cloud version:** (see admin page or version.php)
  
   
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

Can't say - only way to get the tab to respond, even to F12, is to click the Exit Page on the Unresponsive pop-up. That appears to be clearing everything out of the console and dumping the page.

</details>   


#### Cloud log
<!--
The log has the name owncloud.log or nextcloud.log and is found in the data folder
-->

<details>
<summary>Cloud log</summary>

```
{"reqId":"ttNdiXAkGcgzvi2XtWgX","level":3,"time":"2021-03-22T21:02:37+00:00","remoteAddr":"[local-network-ip]","user":"[user-name]","app":"passman","method":"GET","url":"/ocs/v2.php/apps/notifications/api/v2/notifications","message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36","version":"21.0.0.18"}
```
</details>

**Comment by binsky08** [comment]
Oh yes, thats an already known issue. During the publishing process the appinfo/app.php was not deleted.
It is just a warning that does not change the functionality of Passman.
I think it could be deleted manually, but you can also wait a few days for the next release.

**Comment by minalexcorporation** [comment]
Awesome, thanks for the response! Sorry if it was noted somewhere - I searched looking to see if someone mentioned it, but I suffer from sporadic idiocy syndrome; I may have missed a post about it :\
