### ISSUE TITLE
/appinfo/app.php is not loaded

### ISSUE THREAD

**Issue by Linuxfabrik** [nextcloud/passman#685]
### Steps to reproduce
1. Install NC 20
2. Install Passman
3. Use it

### Expected behaviour
nextcloud.log doesn't complain about nothing.

### Actual behaviour
nextcloud.log is full with those messages: 

```
    "level":3,
    "app":"passman",
    "method":"GET",
    "url":"/ocs/v2.php/core/navigation/apps?absolute=true&format=json",
    "message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class."
    "version":"20.0.8.1"
```

### Configuration
**Operating system**:   CentOS 7

**Browser**:  Doesn't matter

**Passman version**:  2.3.7

**Web server:** Apache httpd 2.4.6

**Database:** MariaDB 10.2.37

**PHP version:** PHP 7.4.16
      
**cloud server:** Nextcloud

**cloud version:** Nextcloud 20.0.8
  
   

#### Cloud log
<details>
<summary>Cloud log</summary>

```
    "level":3,
    "app":"passman",
    "method":"GET",
    "url":"/ocs/v2.php/core/navigation/apps?absolute=true&format=json",
    "message":"/appinfo/app.php is not loaded when \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class is used. Migrate everything from app.php to the Application class."
    "version":"20.0.8.1"
```
</details>

**Comment by binsky08** [comment]
see https://github.com/nextcloud/passman/issues/683#issuecomment-804400928

**Comment by Linuxfabrik** [comment]
Perfect, thank you :-)
