### ISSUE TITLE
Spamming logfile with Error level messages on Nextcloud 21

### ISSUE THREAD

**Issue by jaro3** [nextcloud/passman#691]
Arch Linux nextcloud 21.0.1-1

Error	passman	/appinfo/app.php is not loaded when \OCP\AppFramework\Bootstrap\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.

every second or less running in the logfile, cannot disable the Error level messages ;-;

**Comment by binsky08** [comment]
see https://github.com/nextcloud/passman/issues/683#issuecomment-804400928

**Comment by jaro3** [comment]
Okay
did 'loglevel' => 4,   for the time being
