### ISSUE TITLE
Error: /appinfo/app.php is not loaded when \OCP\AppFramework\Bootstrap\IBootstrap on the application class is used.

### ISSUE THREAD

**Issue by B0wman** [nextcloud/passman#692]
### Steps to reproduce
1.Upgrade Nextcloud 20.0.8 to 20.0.9
2.
3.

### Expected behaviour
That passman does not issue error messages

### Actual behaviour
Passman 2.3.7 fill the registry with error messages at a pace of 3 each second
### Configuration
**Operating system**:   
Windows 7 64 bits
**Browser**:      
Firefox 88.0 64 bits for Windows
**Extensions that might cause interference**:   

**Passman version**:    
2.3.7
**Operating system**:
Debian 10 Stable
**Web server:**
Apache2
**Database:**
PostgreSQL 11.11 (Debian 11.11-0+deb10u1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
**PHP version:**
7.3.27      
**cloud server:** Nextcloud or ownCloud
Nextcloud
**cloud version:** (see admin page or version.php)
  20.0.9
   
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>   

#### Cloud log

<details>
<summary>Cloud log</summary>

```
[passman] Error: /appinfo/app.php is not loaded when \OCP\AppFramework\Bootstrap\IBootstrap on the application class is used. Migrate everything from app.php to the Application class.
POST /nextcloud/settings/apps/disable
from 88.xxx.xxx.xxx by administrator at 2021-04-27T09:51:43+00:00
```
</details>

## Feature request

**User type**: Logged-in or public user

**User level**: Beginners, intermediate or advanced

### Sponsorship

 
**Are you a developer willing to implement this feature?**: yes/no

**Can you sponsor the development of this feature or do you know someone who can?**: yes/no

**Comment by binsky08** [comment]
#683
