### ISSUE TITLE
Error while upgrading from 2.3.7 to 2.3.8

### ISSUE THREAD

**Issue by hms4242** [nextcloud/passman#697]
### Steps to reproduce
I had an error message trying to update passman from admin page. I ended trying the update via occ, here's the message I got : 
ArgumentCountError: Too few arguments to function OCA\Passman\Migration\ServerSideEncryption::__construct(), 0 passed in /var/www/nextcloud/lib/private/Repair.php on line 127 and exactly 7 expected in /var/www/nextcloud/apps/passman/migration/serversideencryption.php:63

### Expected behaviour
Update should go fine

### Actual behaviour
update via occ returned a stacktrace with this error on top:
ArgumentCountError: Too few arguments to function OCA\Passman\Migration\ServerSideEncryption::__construct(), 0 passed in /var/www/nextcloud/lib/private/Repair.php on line 127 and exactly 7 expected in /var/www/nextcloud/apps/passman/migration/serversideencryption.php:63

### Configuration
**Operating system**:   

**Extensions that might cause interference**:   

**Passman version**:   2.3.7 --> 2.3.8 (upgrading)

**Operating system**: raspbian 

**Web server:** nginx

**Database:** mysql

**PHP version:**7.3.11
      
**cloud server:** Nextcloud 

**cloud version:** 20.0.4
  
   
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>   

#### Cloud log

<details>
<summary>Cloud log</summary>

```
Insert your cloud log here
```
</details>

## Feature request

**User type**: Logged-in or public user

**User level**: Beginners, intermediate or advanced

### Sponsorship

 
**Are you a developer willing to implement this feature?**: yes/no

**Can you sponsor the development of this feature or do you know someone who can?**: yes/no

**Comment by binsky08** [comment]
hmm, I thought the NextCloud updater would check the required php version specified in the appinfo/info.xml.
The error arises because the wrong php version is being used.
For Passman 2.3.8 it is php 7.4 (https://github.com/nextcloud/passman/blob/2.3.8/appinfo/info.xml#L40)

**Comment by hms4242** [comment]
Thanks, that solved my issue!
