### ISSUE TITLE
NC 22 - Removed support for database.xml

### ISSUE THREAD

**Issue by intellirat** [nextcloud/passman#698]
## Bug report
NC22 has removed support for database.xml, and this prevents Passman from being enabled
### Steps to reproduce
1. Upgrade from NC 21 to 22
2. See Passman is in disabled apps, so try to enable
3. Error is thrown - Exception: The appinfo/database.xml file is not longer supported. Used in passman

### Expected behaviour
Passman should start fine!

### Actual behaviour
Passman cannot be enabled

### Configuration
**Passman version**:    
2.3.8
**cloud server:** Nextcloud or ownCloud
Nextcloud
**cloud version:** (see admin page or version.php)
22
   
#### Cloud log

<details>
<summary>Cloud log</summary>
settings	Exception: The appinfo/database.xml file is not longer supported. Used in passman
/var/www/html/apps/settings/lib/Controller/AppSettingsController.php - line 447:
OC\Installer->installApp("passman")
/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 217:
OCA\Settings\Controller\AppSettingsController->enableApps([ "passman"], [])
/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 126:
OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings ... {}, "enableApps")
/var/www/html/lib/private/AppFramework/App.php - line 156:
OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings ... {}, "enableApps")
/var/www/html/lib/private/Route/Router.php - line 301:
OC\AppFramework\App::main("OCA\\Settin ... r", "enableApps", OC\AppFramew ... {}, { _route: "s ... "})
/var/www/html/lib/base.php - line 1000:
OC\Route\Router->match("/settings/apps/enable")
/var/www/html/index.php - line 36:
OC::handleRequest()
</details>

### Description
This just looks like a change in config for NC22.

As a workaround you can rename database.xml (I went to database.xml.bak), in appinfo folder, and try to start Passman again - it works then, as I already had a pre-configured environment, so db was already there!

**Comment by voileux** [comment]
Thank's for your patch, it work's perfectly on NC22.

**Comment by eluminare** [comment]
Worked like a charm! @binsky08

**Comment by anpct** [comment]
Issue still exists in fresh install for N22

**Comment by binsky08** [comment]
Have you manually deleted the database.xml and added the migration file before activating the Passman app?
