### ISSUE TITLE
Share password with a link

### ISSUE THREAD

**Issue by brantje** [nextcloud/passman#7]
Users should be able to share the password with a link.
Sharing with a link is always read only.
Include the features:
- #6 Share for until a specific date / time
- #5 Share for xx views

**Comment by animalillo** [comment]
this is the weaker spot of sharing passwords as the sharing shared key would be exposed to the public...
I suggest allowing nexcloud admin to disable this feature

**Comment by s-brand** [comment]
Agreed, NC admin should have the ability to enable / disabled Credential sharing via link.

**Comment by brantje** [comment]
Fixed in: 294b9f7201e3ddbf122bc177f31fe8c3d30c01c0
