### ISSUE TITLE
Restore passwords from a backup of nextcloud 

### ISSUE THREAD

**Issue by xXTeraXx** [nextcloud/passman#700]
Sorry for not following the template but this is not really an issue,  I had passman running in nextcloud 21 on debian 10.  Last week the install had corrupted itself so I had to reinstall debian but I have a backup of the nextcloud data folder (bind-mounted to /var/www/html).  Is there any way I can get the passwords back, or are they gone?  Thanks in advance 

Edit: I was using a SQLite database (I know its bad but I have no clue how to setup MySQL or MariaDB)

**Comment by OS3DrNick** [comment]
I dont know the specifics, in your case.
In general if you have a working copy of your db and a backup of your nextcloud config.php file, 
You can place them both back and you should already be up and running again.

Passmans encryption is based on the 'secret' in the configuration file. All the data in the database is encrypted with this, so you will need this info.

In my testing scenarios, placing all files (var www) back and restore older version of db, I could hop versions back and forward.

**Comment by xXTeraXx** [comment]
Thanks, but I had completely forgotten to take a backup of the dB.  However my automatic backup process did export the passwords out of the vault into the json file.  (i forgot it did that). So I just reinstalled nextcloud 21 and passman and reimported the passwords.
