### ISSUE TITLE
Too short column -> "Modified"

### ISSUE THREAD

**Issue by pawlosck** [nextcloud/passman#701]
### Steps to reproduce
Open Nextcloud Passwords with polish translation

### Expected behaviour
Polish translation should be shorter or column should be longer

### Actual behaviour
![image](https://user-images.githubusercontent.com/3769853/125827150-233c7fa7-2076-4f48-a554-9b2754640a75.png)

**Browser**:      
Firefox 89.0.2 (64-bit)

**Passman version**:    
2021.7.22

**Operating system**:
Ubuntu 21.04

**Web server:**
Apache

**Database:**
sqlite

**PHP version:**
      

**cloud server:** Nextcloud or ownCloud
Nextcloud 21.0.2

**Comment by binsky08** [comment]
[Nextcloud Passwords](https://git.mdns.eu/nextcloud/passwords) is not Passman
