### ISSUE TITLE
Multiple errors  in integrity check report

### ISSUE THREAD

**Issue by geosphere** [nextcloud/passman#716]
## Bug report
Multiple errors  in integrity check report after update passman to 2.3.10  

As far as I understand, the files I have relevant to the files in the release archive and the signature.json has the same content.

**Comment by binsky08** [comment]
Hmm, have you tried to deactivate and delete the app and install it again?

If the error is still there, after you have done this and after an integrity rescan, could you provide the list of corrupt files here.

**Comment by geosphere** [comment]
Thanks for your response. Full delete the app + reinstall completely safe for the stored password data? Or should I backup something like a key?

**Comment by binsky08** [comment]
*Doing a Backup is always a good idea.*
But removing the app should not touch any Passman data in the database (like your passwords).

**Comment by geosphere** [comment]
Thx. I reinstalled the app, the issue still exists. As far as I understand, `signature.json` contains information about the path of the dev environment, such as `- .git/*` and `node_modules/*` that are missing (for obvious reasons ) in the release. 
[report.txt](https://github.com/nextcloud/passman/files/7109239/report.txt)

**Comment by binsky08** [comment]
have you installed the app via the nextcloud integrated app store?

**Comment by geosphere** [comment]
Exactly! I specifically reinstalled from the app store.

**Comment by animalillo** [comment]
did you fully remove the passman app dir prior to reinstalling from the app store?

**Comment by geosphere** [comment]
Yep. I'm quite sure of that. I have removed the app from the web interface. After that, I checked if there were any obsolete files. The folder `apps2/passman` was missing.

**Comment by pacbidouandco** [comment]
hi,

I have the same problem

**Comment by jsalatiel** [comment]
Same problem here on nextcloud 21.

**Comment by felipealb** [comment]
The same here. Updated from 2.3.8 to 2.3.10 on Nextcloud 21.0.4. Even reinstalled, the error persists.

**Comment by binsky08** [comment]
I tried it with upgrading the app from 2.3.7 to 2.3.10, I tried fresh installations of 2.3.10 but I was not able to reproduce the problem on Nextcloud 21.0.4 and 22.1.0.
I have no idea.

Could you please try it again and ...
- deactivate the app in your Nextcloud
- remove the complete app folder manually !!! from the filesystem (usually `apps/passman` or `custom_apps/passman`, depends on the installation)
- reload the Apps page from your Nextcloud and be sure, that the app is not just deactivated and has to be downloaded and activated again
- download and activate Passman using the Nextcloud Apps page
- test if Passman works (maybe a reload of the Passman app page is required)
- check, if the (new automatically downloaded) Passman app folder still contains a `.git` folder
- (hopefully it's not there)
- rerun the integrity check

**Comment by felipealb** [comment]
> The same here. Updated from 2.3.8 to 2.3.10 on Nextcloud 21.0.4. Even reinstalled, the error persists.

I executed the procedure sent by email (manually disable, delete app folder and install again) but the problem still persists.

**Comment by binsky08** [comment]
It's not fixed yet, but we could find the problem in our release script. As soon as we have time we will release a new version that will hopefully fix the problem.

**Comment by geosphere** [comment]
I confirm that the latest release has fixed this issue

**Comment by vladas-palubinskas** [comment]
Passman crached Nextcloud [again](//github.com/nextcloud/server/issues/28559), in similar way to #709:

> Update for **Passman** to version 2.3.1334 is available

    \OC\Updater::maintenanceEnabled: Turned on maintenance mode
    starting upgrade from 21.0.4.1 to 21.0.4.1

Passman is forcing Nextcloud upgrade from 21.0.4.1 to the same 21.0.4.1 version? Immediately, without asking, with no confirmation?!

    Deprecated event type for \OC\Repair::step: Symfony\Component\EventDispatcher\GenericEvent is used

What?! No such app and never was on my cloud!

    \OC\Repair::step: Repair step: Repair MySQL collation
    Deprecated event type for \OC\Repair::info: Symfony\Component\EventDispatcher\GenericEvent is used
    \OC\Repair::info: Repair info: All tables already have the correct collation -> nothing to do
    Deprecated event type for \OC\Repair::step: Symfony\Component\EventDispatcher\GenericEvent is used

and so on, many steps until

    Exception: Database error when running migration latest for app passman

with 5 + 15 + 14 + 14 error log messages.

Debian 9 on Linux 4.9.0-16-686-pae on i686,
MariaDB 10.1.48, PHP 8.0.3,
Mozilla Firefox, Vivaldi, etc.

![20210929passman](https://user-images.githubusercontent.com/44341097/135435904-a3b7c640-5bac-4093-84d2-12471388592b.png)

**Comment by binsky08** [comment]
**your issue has nothing to do with integrity checks, so please do not append your issues to others, if it is not the same problem!**


> \OC\Updater::maintenanceEnabled: Turned on maintenance mode
> starting upgrade from 21.0.4.1 to 21.0.4.1

uhmm, thats weird.
Could you try to disable the app and enable it again, like this:
```
sudo -u www-data php /var/www/html/occ app:disable passman
sudo -u www-data php /var/www/html/occ app:enable passman
```

if enabling was successful you can disable the maintenance mode with
`sudo -u www-data php /var/www/html/occ maintenance:mode --off`

**If the problem persists, please open a new issue for that.**

**Comment by vladas-palubinskas** [comment]
Yes, I have disabled Passman, uninstalled, removed its lib/Migration/(older).php, installed again — with the same crash, though. Eventually disabled it — I can live without Passman, and not willing to destroy important data on the cloud. Sorry for my report out of place.
