### ISSUE TITLE
An error occurred during decryption when updating a shared credential

### ISSUE THREAD

**Issue by binsky08** [nextcloud/passman#737]
### Steps to reproduce
1. Share credential with a second user
2. Edit shared credential with the second user account
3. Press the save button

### Expected behaviour
- Only getting the notification "Credential updated"
- Successfully updated credential

### Actual behaviour
- Browser console shows an error
- Get the notification "Credential updated"
- Get the notification "An error occurred during decryption"
- Successfully updated credential

Same behavior when sharing and editing with multiple users.

### Configuration
**Operating client system**:   NixOS 21.11

**Browser**:   Firefox 99.0.1

**Extensions that might cause interference**:   

**Passman version**:    2.4.0

**Operating server system**:    Ubuntu 20.04.4

**Web server:**    nginx 1.18.0-0ubuntu1.3

**Database:**    8.0.27-18.1 Percona XtraDB Cluster

**PHP version:**    php7.4-fpm 7.4.3-4ubuntu2.10
      
**cloud server:** Nextcloud

**cloud version:** 23.0.3
  
   
#### Browser log
```
Object { toString: toString(), message: "ccm: tag doesn't match" }
[edit_credential.js:407:33](https://localhost:8443/apps/passman/js/app/controllers/edit_credential.js?v=2f1d0958-0)
```

**Comment by JKF1** [comment]
exactly same problem here (including browser log)

Passman version: 2.4.0
OS: Debian 10
php8.0-fpm, mysql-common 5.8+1.0.7, nginx 1.20.2-1
Nextcloud 23.0.3
