### ISSUE TITLE
Found a stop when importing from BitWarden

### ISSUE THREAD

**Issue by Kitanit** [nextcloud/passman#742]
@brantje found a stop when importing from BitWarden
*already stuck like this for a couple of minutes, the server is not loaded
![image](https://user-images.githubusercontent.com/65107731/168229453-10349f3c-a570-46e0-bfe7-ebfc11f6bf7e.png)

_Originally posted by @Kitanit in https://github.com/nextcloud/passman/issues/404#issuecomment-1125724074_

**Comment by Kitanit** [comment]
![image](https://user-images.githubusercontent.com/65107731/168550792-b9f0e03a-cc1a-400b-bda3-59a190ec1df8.png)

**Comment by sudheer1994** [comment]
I am stuck with the same issue. Anyone here to help?

**Comment by binsky08** [comment]
could you provide an example bitwarden file that breaks the import?

**Comment by binsky08** [comment]
since the generic CSV import has been improved with #791 and my test with an own bitwarden csv export had no issues, I assume that's already fixed
