### ISSUE TITLE
"Destruction request pending " 

### ISSUE THREAD

**Issue by panspectron2017** [nextcloud/passman#744]
This is not a bug, but I cannot find a way to actually delete a vault. 
The vaul has "Destruction request pending" but who or where can I delete the vault in the end?
I cannot find any hint in the documentation.

**Comment by animalillo** [comment]
Only an admin can finalize the vault destruction, the process is completed in the nextcloud settings on the passman section.

**Comment by panspectron2017** [comment]
Thanks Animalillo, at last I found the settings.
Stupid me did not scroll down the "additional settings"-page to the end the last time(s) ;-)
