### ISSUE TITLE
passman, The login window that resets when I click elsewhere

### ISSUE THREAD

**Issue by pwepwe973** [nextcloud/passman#746]
Hello,

is it possible that the small window that allows you to identify yourself remains open when I go to look for my passwords in keepass because it resets and I have to re-enter everything again

Sincerely, SYLVAIN

**Comment by RossComputerGuy** [comment]
I have the same problem except when I slightly move my mouse. I can't get past the vaults screen.

**Comment by binsky08** [comment]
You talking about the browser extension?

**Comment by RossComputerGuy** [comment]
Yes, I've had this issue with the browser extension.

**Comment by binsky08** [comment]
duplicate of https://github.com/nextcloud/passman-webextension/issues/336 in the wrong repository
