### ISSUE TITLE
Window with the Credentials not visible

### ISSUE THREAD

**Issue by Ordam786** [nextcloud/passman#750]
### Steps to reproduce
1.Login on Nextcloud and click on Passman
2. Click on the vault and enter the Password
3. => I only the see the field with "Tags...Bad Strength...Medium Strength...Good Strength...Expired"
4. When i change the browser zoom from 100% to 250% suddenly the window with the password is visible

### Expected behaviour
The windows with the password list..should open
### Actual behaviour
I only the see the field with "Tags...Bad Strength...Medium Strength...Good Strength...Expired"

### Configuration
Client Windows 10 Server: Managed Server

**Browser**:      
Tested with Firefox and Edge

**Extensions that might cause interference**:   

no special Extension installed
![Passman2](https://user-images.githubusercontent.com/116266355/196915762-1ce1dd7c-29ae-4819-9106-b83fe0f50253.jpg)
![passman1](https://user-images.githubusercontent.com/116266355/196915768-ab8aac60-d6bb-4b99-9eb3-960b755460e2.jpg)

**Passman version**:    
2,4,1

**Operating system**:
Linux Managed Server

 
**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
      8.1.11
**cloud server:** Nextcloud or ownCloud
Nextcloud
**cloud version:** (see admin page or version.php)
  25
   
#### Browser log
no log
  

#### Cloud log

<details>
<summary>Cloud log</summary>
no log entry
```




### Description
<!--
Please try to give as much information as you can about your request

 

When i login in Passman, the window with my passwords is not visible.
I only the see the field with the "Tags...Bad Strength...Medium Strength...Good Strength...Expired"
When i  zoom in in my browser to 250% i suddenly see the list with my passwords on the left side.
Nextcloud Version 25..Browser...Firefox and Edge


![Passman2](https://user-images.githubusercontent.com/116266355/196911146-95426ae5-604b-40ee-aa85-ec8db679aaf4.jpg)
![passman1](https://user-images.githubusercontent.com/116266355/196911151-4d445528-ca82-4bd6-be5e-bdc941ede7b3.jpg)

**Comment by binsky08** [comment]
Hi @Ordam786, nextcloud 25 is not supported yet.
I'm currently working on an update, but it will probably take a few more days.

**Comment by lcuis** [comment]
Thanks a lot @binsky08 for the fast adaptation!

@Ordam786 , if it helps, I just noticed that the Android app can still give you access to your passwords while waiting for the fix to be deployed. Thanks for reporting!

**Comment by secco04** [comment]
the creds are there but not visible, ive tried to customise the  css and failed cause i'm not a pro :D 
if you need creds on your PC Browser resize the window and it will appear like on the smartphone ....

**Comment by Ordam786** [comment]
great thx
