### ISSUE TITLE
OTP uploaded photo is overlapping the generated codes on OTP tab

### ISSUE THREAD

**Issue by mustafaatatuzun** [nextcloud/passman#754]
### Steps to reproduce
1. Go to OTP tab and upload a QR code 
2.
3.

### Expected behaviour
OTP QR Barcode photo and the generated OTP code should be side by side on OTP tab

### Actual behaviour
OTP QR Barcode photo is overlapping the generated OTP code on OTP tab

### Configuration
**Operating system**:   win 10

**Browser**:      chrome Version 108.0.5359.99 (Official Build) (64-bit)

**Extensions that might cause interference**:   

**Passman version**:    2.4.2

**Operating system**: Linux 5.4.0-100-generic x86_64

**Web server:**

**Database:**mysql  10.6.7

**PHP version:** 8.0.15
      
**cloud server:** Nextcloud

**cloud version:**  25.0.2
  
   
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>   

#### Cloud log

<details>
<summary>Cloud log</summary>

</details>

**Comment by binsky08** [comment]
could not reproduce in chrome with passman 2.4.2 and nc 25.0.2

![grafik](https://user-images.githubusercontent.com/30630233/210022872-034b08f1-32d1-4cee-bcb6-f39209afde62.png)
