### ISSUE TITLE
Upgrade to NextCloud 25 breaks vault decryption if secret not set

### ISSUE THREAD

**Issue by jurassic-c** [nextcloud/passman#755]
## Bug report

On NextCloud instances without the config variable `secret` set, upgrading to NextCloud 25 enforces the setting of this configuration variable. Doing so changes causes any existing vaults to become unusable, since the secret has changed. The direct symptom of this is that decrypting a vault no longer works when using what was previously the correct password.

### Steps to reproduce

1. Install any version of NextCloud prior to version 25, without setting the `secret` config variable in `config.php`
2. Install passman
3. Create a vault
4. Upgrade to NextCloud version 25. You will be warned that the secret is not set. This can be set automatically by running `occ maintenance:repair`, or by setting it manually in `config.php`
5. Finish NextCloud upgrade
6. Log in
7. Navigate to Passman
8. Attempt to decrypt your vault
9. Note that it no longer works

### Expected behaviour

After upgrading to version 25 of NextCloud and setting a previously nonexistent secret value, decrypting of previously created vaults should be possible using the same password as before.

### Actual behaviour

Vaults are unable to be decrypted with the previous password

### Configuration

**Operating system**:  Manjaro with all current updates

**Browser**: 

- Firefox 108.0.1 (64-bit)
- Chromium 108.0.5359.124 (Official Build) Arch Linux (64-bit)

**Extensions that might cause interference**:   

**Passman version**:   2.4.2

**Operating system**: Manjaro with all current updates

**Web server:** Ubuntu 20.04.04 hosting Docker image `nextcloud:25` with Nginx as reverse proxy

**Database:** mysqld  Ver 10.6.4-MariaDB-1:10.6.4+maria~focal for debian-linux-gnu on x86_64 (mariadb.org binary distribution)

**PHP version:** PHP 8.0.26 (cli) (built: Dec  6 2022 06:18:10)
      
**cloud server:** Nextcloud

**cloud version:** 24.0.8.2, 25.*

**Comment by binsky08** [comment]
I can't change the upgrade process of nextcloud, but nc 25 works with an empty secret. Just tested with 25.0.2.
The documentation tells me that too.

![grafik](https://user-images.githubusercontent.com/30630233/210024024-43ea49c7-a7e3-499b-a520-304b607f8425.png)
