### ISSUE TITLE
Column not found: 1054 Unknown column 'compromised' in 'field list'"

### ISSUE THREAD

**Issue by mpiscaer** [nextcloud/passman#757]
I used in 2017 passman for a short while. After that I removed the app. Now I installed it fresh and I saw the old vault again. So the database was still there.

I'm unable to create a new vault and I see the following error:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'compromised' in 'field list'"

How can I solve this?

**Comment by binsky08** [comment]
hi @mpiscaer, sorry for that problem, there's already an issue: #726 

But if you don't mind deleting all Passman tables / data you can run there steps to recreate all passman tables:

- disable the Passman app
- run sql in the database:
```mysql
drop table oc_passman_credentials, oc_passman_delete_vault_request, oc_passman_files, oc_passman_revisions, oc_passman_share_request, oc_passman_sharing_acl, oc_passman_vaults;
delete from oc_migrations where app="passman";
```
- enable the Passman app (missing tables should now be recreated automatically)

**Comment by mpiscaer** [comment]
thank you very much, that solved my issue.
