### ISSUE TITLE
Recovery of Lost Vault Password

### ISSUE THREAD

**Issue by compumatter** [nextcloud/passman#758]
This is not an issue yet.  However I am trying to insure there is a built-in way to avoid a catastrophic ending well in advance of it happening

We are using Nextcloud 25 on Ubuntu 22.04 with Mysql 8.0.

If my client is using the Passman application on Nextcloud and for any reason loose or forget or change and forget their Passman vault password, is there a disaster recovery method in place to restore access to their password data.

If so, can you provide a brief walk through on this.  I'm sure others have this question yet searching online did not turn up the answer.

Thank you.

Jay / CompuMatter

**Comment by animalillo** [comment]
There's no restore methods on passman, the password is your encryption key, pick a secure one and don't forget it, or you will need to create a new vault!
