### ISSUE TITLE
Prevent Passman on offline Nextcloud instance sending request to GitHub

### ISSUE THREAD

**Issue by proton2b** [nextcloud/passman#765]
## Bug report
Hi, 
we are using nextcloud in an offline environment where the instance has no internet access.
The system is getting regular updates manually. To prevent nextcloud to request every time resources on the internet when accessing the administrator pages (which causes long loading times until the timeout is reached) we set the settings:

 'updatechecker' => false,
 'has_internet_connection' => false,

But it seems that the passman app is not using those parameters because when we go to additional settings (where passman shows its settings) this page is loading also the version from GitHub and without internet this pages loads for almost 1-2 minutes (timeout) until it shows up.

The Nextcloud log then shows following message:
Error| passman | Error fetching latest GitHub release version in lib/Admin:getForm()

### Steps to reproduce
1. Disable internet Access for the Nextcloud System
2. Then go to https://YOURNEXTCLOUDINSTANCE/settings/admin/additional
3. This pages is loading until the Request to GitHub from passman times out

### Expected behaviour
When operating nextcloud in offline mode over the parameter in the nextcloud config.php `'has_internet_connection' => false,` the plugin should also prevent sending requests to the internet.

### Actual behaviour
Passman is sending the request to GitHub anyway.

### Configuration
**Operating system**:   Debian Linux 11

**Browser**:     Google Chrome

**Extensions that might cause interference**:   Passman

**Passman version**:    2.4.4

**Operating system**:

**Web server:** Nginx 1.23

**Database:** MariaDB

**PHP version:** 8.0.1

**Comment by binsky08** [comment]
From the next release, the has_internet_connection option will be taken into account.
Until then, the version check can be deactivated with the "Check for new version" option.

![image](https://user-images.githubusercontent.com/30630233/233834440-fa483ee4-46bd-4a63-8dc3-e64f07f984ef.png)
