### ISSUE TITLE
NC25 - the app disables itself after being enabled

### ISSUE THREAD

**Issue by ataraxiafr** [nextcloud/passman#773]
## Bug report

NC22 has removed support for database.xml, and this prevents Passman from being enabled
### Steps to reproduce

     1. Upgrade from NC 20 to 25 (through several intermediate versions)
 
     2. See Passman is in disabled apps, so try to enable
 
     3. Error is thrown - Exception: The appinfo/database.xml file is not longer supported. Used in passman
     4. I have tried the fix in #698 
     5. I enable the app
     6. The app disables itself
 
 
 ### Expected behaviour
 
 Passman should keep being enabled.
 ### Actual behaviour
 
 Passman becomes disabled after being enabled.
 ### Configuration
 
 **Passman version**: 2.3.5 **cloud server:** Nextcloud or ownCloud Nextcloud **cloud version:** (see admin page or version.php) 25
 #### Cloud log
 Cloud log
Occ says the app is enabled. I can enable it through the GUI too. Therefore, the app desactivates itself.
 
### Description
There are issues with the code integrity check as well with the app.

**Comment by binsky08** [comment]
You have to update Passman to the latest version (see https://github.com/nextcloud/passman/releases).
2.3.5 is very outdated, the database.xml got removed in the meantime.

**Comment by ataraxiafr** [comment]
How could I upgrade passman without losing the password database ?
I have tried occ app:update but nothing happened
