### ISSUE TITLE
Internal Server Error with 26.0.0

### ISSUE THREAD

**Issue by rougerouter** [nextcloud/passman#788]
### Steps to reproduce
1. Latest update loaded
2.
3.

### Expected behaviour
Tell us what should happen

Should open the app

### Actual behaviour
Tell us what happens instead

It didn't: Internal Server Error

The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.

### Configuration
**Operating system**:   

**Browser**:      

**Extensions that might cause interference**:   

**Passman version**:    
Latest
**Operating system**:

**Web server:**

**Database:**

**PHP version:**
   Nextcloud
**cloud version:** (see admin page or version.php)
  26.0.0
   
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>   

#### Cloud log

<details>
<summary>Cloud log</summary>

```
Insert your cloud log here
```
</details>

## Feature request

**User type**: Logged-in or public user

**User level**: Beginners, intermediate or advanced

### Risk / caveats

I just started using this app and was curious to see if there were going to be issues. And there are, now I am going back to may old dependable keypass. If you are going to make an app and it breaks nobody will trust you and nobody will use it. So disappointed!!!
### Sponsorship

 
**Are you a developer willing to implement this feature?**: yes/no

**Can you sponsor the development of this feature or do you know someone who can?**: yes/no

**Comment by binsky08** [comment]
can't help you without a detailed configuration description, a concrete error description or a server error log

maybe this will help you since it's a recent behavior: https://github.com/nextcloud/passman/issues/787#issuecomment-1607019046

Please update your bug report with useful information or close the issue.

**Comment by rougerouter** [comment]
I will just go back to using KeePass. This is not reliable.

**Comment by paulcalabro** [comment]
@rougerouter It's pretty reliable. I've only had a couple issues over the years. 

Anyways, I had the same error after the upgrade. Try restarting your server. That should resolve it.

**Comment by rougerouter** [comment]
I will try this, but I already am looking into other password app. I would
rather not go through this for every update. Thanks for your help though!
Tom
