### ISSUE TITLE
Export to CSV reports errors

### ISSUE THREAD

**Issue by juergen852** [nextcloud/passman#790]
### Steps to reproduce
1. After Update to Nextcloud Hub 4 (26.0.3) and fixing #789 many errors in NC-Log
2. Exporting passwords to CSV file.
3. The CSV is created, but it may contain errors / not all data.

### Expected behaviour
No errors in NC-Logfile.

### Actual behaviour
See copy of NC log output below.

### Configuration
**Passman version**:    
2.4.6

**Operating system**:
Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-75-generic x86_64)

**Web server:**
nginx/1.25.1

**Database:**
mysql 10.8.8

**PHP version:**
Version: 8.1.13

**cloud server:** Nextcloud or ownCloud
Nextcloud

**cloud version:** (see admin page or version.php)
 26.0.3
   
#### Browser log
Export gestartet
Anmeldeinformationen werden entschlüsselt
Fehler beim Entschlüsseln mittels = Error while decrypting using....
..... Error shows up 50 times
Fertig.

#### Cloud log

<details>
<summary>Cloud log</summary>

```
[index] Fehler: Exception: OCA\Passman\Service\FileService::getFile(): Argument #1 ($fileId) must be of type int, string given, called in /var/www/nextcloud/apps/passman/lib/Controller/FileController.php on line 62 in file '/var/www/nextcloud/apps/passman/lib/Service/FileService.php' line 57 at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch()
1. /var/www/nextcloud/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main()
4. /var/www/nextcloud/lib/base.php line 1060
   OC\Route\Router->match()
5. /var/www/nextcloud/index.php line 36
   OC::handleRequest()

Caused by:

TypeError: OCA\Passman\Service\FileService::getFile(): Argument #1 ($fileId) must be of type int, string given, called in /var/www/nextcloud/apps/passman/lib/Controller/FileController.php on line 62 at <<closure>>

0. /var/www/nextcloud/apps/passman/lib/Controller/FileController.php line 62
   OCA\Passman\Service\FileService->getFile()
1. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 230
   OCA\Passman\Controller\FileController->getFile()
2. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 137
   OC\AppFramework\Http\Dispatcher->executeController()
3. /var/www/nextcloud/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch()
6. /var/www/nextcloud/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main()
7. /var/www/nextcloud/lib/base.php line 1060
   OC\Route\Router->match()
8. /var/www/nextcloud/index.php line 36
   OC::handleRequest()

GET /apps/passman/api/v2/file/undefined
from 10.8.2.100 by *username* at 2023-06-27T10:54:46+02:00
```
</details>

## Feature request

**User type**: Logged-in or public user

**User level**: Beginners, intermediate or advanced

### Sponsorship

 
**Are you a developer willing to implement this feature?**: yes/no
No
**Can you sponsor the development of this feature or do you know someone who can?**: yes/no
PP donnation € 50.- of today to this great project.

**Comment by binsky08** [comment]
Hi @juergen852, I will take a look at it soon. In the meantime I recommend using Passman JSON export.
Would be interesting to know, if a JSON export produces the same errors.

**Comment by juergen852** [comment]
@binsky08 
Yes, JSON also leaves errors in NC log, as well as:


#### Frontend
<details>
<summary>Frontend</summary>

Export gestartet
Anmeldeinformationen werden entschlüsselt
Fehler beim Entschlüsseln mittels 
....... 203 times
Fehler beim Entschlüsseln mittels 
Fertig
</details>

I have 312 passwords, "Fehler beim Entschlüsseln mittels " is only reported 200 times, so not every pwd seems to trigger the error. I have lots of 2FA, or QR code immages stored, but not 200 pcs.

#### Cloud log

<details>
<summary>Cloud log</summary>
```
[index] Fehler: Exception: OCA\Passman\Service\FileService::getFile(): Argument #1 ($fileId) must be of type int, string given, called in /var/www/nextcloud/apps/passman/lib/Controller/FileController.php on line 62 in file '/var/www/nextcloud/apps/passman/lib/Service/FileService.php' line 57 at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch()
1. /var/www/nextcloud/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main()
2. /var/www/nextcloud/lib/base.php line 1060
   OC\Route\Router->match()
3. /var/www/nextcloud/index.php line 36
   OC::handleRequest()

Caused by:

TypeError: OCA\Passman\Service\FileService::getFile(): Argument #1 ($fileId) must be of type int, string given, called in /var/www/nextcloud/apps/passman/lib/Controller/FileController.php on line 62 at <<closure>>

0. /var/www/nextcloud/apps/passman/lib/Controller/FileController.php line 62
   OCA\Passman\Service\FileService->getFile()
1. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 230
   OCA\Passman\Controller\FileController->getFile()
2. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 137
   OC\AppFramework\Http\Dispatcher->executeController()
3. /var/www/nextcloud/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch()
4. /var/www/nextcloud/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main()
5. /var/www/nextcloud/lib/base.php line 1060
   OC\Route\Router->match()
6. /var/www/nextcloud/index.php line 36
   OC::handleRequest()

GET /apps/passman/api/v2/file/undefined
from 10.8.2.100 by username at 2023-06-27T12:37:39+02:00

```

**Comment by binsky08** [comment]
Even if the frontend source code is kinda creepy, I have tried to improve the generic importer/exporter logic a bit.
Would be nice if you could try the current approach from #791.

If you don't want to checkout the sources, it should be enough to replace the css and js directories with the ones from the dist.zip, I added for you to the pr. After replacing, don't forget to reload Passman with Ctrl+R (to invalidate browser website cache). And please do backup the original css and js dirs.

**Comment by juergen852** [comment]
JS and CSS from dist.zip seems to work, error messages in logs and frontend are gone.
I did only replace js and css. Had to delete browser cache manually.
