### ISSUE TITLE
Buttons in headerbar overlap each other

### ISSUE THREAD

**Issue by mossymossmoss** [nextcloud/passman#798]
# Configuration
**Browser**: Firefox 
**Server operating system**: Debian 11
**Passman version**: 2.4.6
**Database:** mysql
**PHP version:** 8.1.20
**Cloud server:** Nextcloud
**Cloud version:** Nextcloud Hub 4 (26.0.3)

# Description
"Home" and "Vault" buttons in headerbar overlap each other

![image](https://github.com/nextcloud/passman/assets/56167669/9c8cdd7d-22b5-46f1-a592-09b0cb56df00)

**Comment by binsky08** [comment]
already fixed in #792 
will be released as soon as the pr is reviewed by @animalillo - poke :)
