### ISSUE TITLE
Sharing discussion

### ISSUE THREAD

**Issue by brantje** [nextcloud/passman#8]
Separate issue for discussing sharing.
Was thinking about using this lib: https://github.com/foxwoods/cryptico

Related issues:
- #3 Share password read only 
- #4 Share password read + write 
- #5 Share for xx views
- #6 Share for until a specific date / time
- #7 Share password with a link

**Comment by maestroi** [comment]
Will it be a one time use? 
that will be most secure 👍 

other than that i approve!

**Comment by animalillo** [comment]
@maestroi RSA keys, you never see other people private keys ;)

**Comment by brantje** [comment]
Since sharing is already implemented, i don't see a point of keeping this discussion open.
If you have any suggestions / complaints about sharing, send a pr or create an issue.
