### ISSUE TITLE
Sharing WRITE ACL do nothing more than READ

### ISSUE THREAD

**Issue by rmarso** [nextcloud/passman#815]
Hi,
First, Many Thanks for this App !!
Best regards.

## Bug report

Sharing WRITE ACL do nothing more than READ

with READ+WRITE ACL => MODIFY is KO => button appears but when i click nothing appends
with READ+WRITE+FILE ACL => MODIFY is OK => button appears and when i click it opens the window 

FILE ACL is mandatory to MODIFY a password or is it a bug ?

### Steps to reproduce

1. Login with account1 (admin group), create new entry and sharing with account2
2. Login with account2 (admin group), create new entry and sharing with account1
3. Sharing passwords between each other and tested on each side

### Configuration

tested on fresh rocky 9 install with apache + php-fpm + mariadb
with nextcloud and passman in their last version
not tested with any previous
not tested with docker

**Comment by binsky08** [comment]
thanks for report @rmarso , I'll try to look into it soon

**Comment by binsky08** [comment]
It seems that the frontend tries to decrypt the files field even if the sharing permission for that is missing. 
Positive: decryption of that field fails :)
Todo: it should not even try that
