### ISSUE TITLE
Can't be installed via Nextcloud Appstore because of no DNS record releases.passman.cc

### ISSUE THREAD

**Issue by JohnWalkerx** [nextcloud/passman#821]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Steps to reproduce
1. Got to NextCloud app store and try to install the Passman app

### Expected behaviour
App gets installed

### Actual behaviour
Message is shown: "No DNS record found for releases.passman.cc"
![Image](https://github.com/user-attachments/assets/c9a57fa6-6c4d-427a-825d-09434c9a46fb)

Also demo and complete passman.cc site is not reachable.

### Server configuration

**Web server:** Apache

**Database:** PostgreSQL

**PHP version:** 8.2

**Nextcloud version:** 29.0.7

### Browser

**Browser name:** Firefox

**Browser version:** 131

**Operating system:** NixOS

**Comment by binsky08** [comment]
Hey, thanks for the hint. We're trying to solve that.

**Comment by binsky08** [comment]
https://passman.cc/ is available again
